//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;

// ----------------- Float Types Definitions ------------------

typedef long double float80_t;

// ------------------------ Structures ------------------------

struct vtable_26f0_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t *);
    int32_t (*e2)(int32_t);
};

struct vtable_2928_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t *);
};

struct vtable_2968_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t *);
    int32_t (*e2)(int32_t);
    int32_t (*e3)(int32_t);
};

// ------------------------- Classes --------------------------

// N5boost16exception_detail10bad_alloc_E
// N5boost16exception_detail10clone_baseE
// N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE (base classes: N5boost16exception_detail10clone_baseE, N5boost16exception_detail10bad_alloc_E)
// N5boost6detail15sp_counted_baseE
// N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE (base classes: N5boost6detail15sp_counted_baseE)
// N5boost6system12system_errorE
// N5boost9exceptionE

// ------------------- Function Prototypes --------------------

void _7e_clone_impl(int32_t this, int32_t __in_chrg);
int32_t _GLOBAL__sub_I__ZN11Checkpoints8fEnabledE(void);
void _ZN11Checkpoints10CheckBlockEiRK7uint256(int32_t nHeight, int32_t hash);
int32_t _ZN11Checkpoints11CheckpointsEv(void);
void _ZN11Checkpoints17GetLastCheckpointERKSt3mapI7uint256P11CBlockIndexSt4lessIS1_ESaISt4pairIKS1_S3_EEE(int32_t mapBlockIndex);
void _ZN11Checkpoints22GetTotalBlocksEstimateEv(void);
void _ZN11Checkpoints25GuessVerificationProgressEP11CBlockIndex(int32_t pindex);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1);
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t * a1);
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t a2);
int32_t _ZN5boost6assign11map_list_ofIi7uint256EENS_13assign_detail12generic_listISt4pairINS3_12assign_decayIT_E4typeENS6_IT0_E4typeEEEERKS7_RKSA_(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(void);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(int32_t a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t * a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1);
int32_t _ZN5boost6system12system_errorD0Ev(int32_t * a1);
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1);
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t * a1);
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1);
int32_t _ZN5boost9exceptionD0Ev(int32_t a1);
int32_t _ZN5boost9exceptionD1Ev(int32_t * a1);
int32_t _ZN9base_uintILj256EE6SetHexEPKc(int32_t * a1, int32_t a2);
int32_t _ZNK5boost13assign_detail12generic_listISt4pairIi7uint256EEcvT_ISt3mapIiS3_St4lessIiESaIS2_IKiS3_EEEEEv(int32_t result, int32_t a2);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1);
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t * a2, int32_t a3);
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt11_Deque_baseISt4pairIi7uint256ESaIS2_EE17_M_initialize_mapEj(int32_t a1, uint32_t a2);
int32_t _ZNSt11_Deque_baseISt4pairIi7uint256ESaIS2_EED1Ev(int32_t * a1);
int32_t _ZNSt3mapIi7uint256St4lessIiESaISt4pairIKiS0_EEED1Ev(int32_t a1);
int32_t _ZNSt5dequeISt4pairIi7uint256ESaIS2_EE16_M_push_back_auxERKS2_(int32_t * a1, int32_t a2);
int32_t _ZNSt5dequeISt4pairIi7uint256ESaIS2_EE17_M_reallocate_mapEjb(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE10_M_insert_EPKSt18_Rb_tree_node_baseSC_RKS3_(int32_t a1);
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE16_M_insert_uniqueERKS3_(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE16_M_insert_uniqueISt15_Deque_iteratorIS0_IiS2_ERSC_PSC_EEEvT_SG_(int32_t a1, int32_t * a2, int32_t a3);
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE17_M_insert_unique_ESt23_Rb_tree_const_iteratorIS3_ERKS3_(int32_t a1, int32_t a2, int32_t a3, int32_t * a4);
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE8_M_eraseEPSt13_Rb_tree_nodeIS3_E(int32_t a1, int32_t a2);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(uint32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(uint32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
int32_t function_107e(void);
int32_t function_10e2(int32_t a1, int32_t a2);
int32_t function_14b2(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_14e8(int32_t a1, int32_t a2);
int32_t function_15af(void);
int32_t function_15b4(void);
int32_t function_15d4(void);
int32_t function_15dd(int32_t a1);
int32_t function_15e8(void);
int32_t function_160a(void);
int32_t function_1612(void);
int32_t function_169a(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_174c(void);
int32_t function_1761(void);
int32_t function_17b3(void);
int32_t function_17d0(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_17e4(void);
int32_t function_1830(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_18df(void);
int32_t function_18f3(void);
int32_t function_18f8(void);
int32_t function_1903(uint32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
int32_t function_1989(void);
int32_t function_1991(void);
int32_t function_1997(void);
int32_t function_19c2(void);
int32_t function_1a6b(void);
int32_t function_1a70(int32_t a1);
int32_t function_1af4(void);
int32_t function_1b40(void);
int32_t function_1b57(void);
int32_t function_1b59(void);
int32_t function_1b5e(void);
int32_t function_1b8(void);
int32_t function_1ba9(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1c18(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1c38(int32_t a1);
int32_t function_1d2(void);
int32_t function_1ea(void);
int32_t function_1ed1(void);
int32_t function_1f60(int32_t a1);
int32_t function_1fa0(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_1fd0(int32_t a1);
int32_t function_1fe0(int32_t a1);
int32_t function_1fe7(void);
int32_t function_20a0(int32_t result);
int32_t function_20d3(void);
int32_t function_216c(void);
int32_t function_2198(void);
int32_t function_21cd(void);
int32_t function_21e8(int32_t a1);
int32_t function_2228(void);
int32_t function_2230(void);
int32_t function_2258(void);
int32_t function_225e(void);
int32_t function_226(void);
int32_t function_2267(void);
int32_t function_22e0(int32_t a1);
int32_t function_22f0(void);
int32_t function_240(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_244(void);
int32_t function_247d(void);
int32_t function_2497(void);
int32_t function_25c1(int32_t a1, int32_t a2, int32_t a3);
int32_t function_260c(void);
int32_t function_2611(void);
int32_t function_2616(void);
int32_t function_2622(void);
int32_t function_2632(void);
int32_t function_2636(void);
int32_t function_2640(void);
int32_t function_270(int64_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_2c8(int32_t a1);
int32_t function_2d0(void);
float80_t function_2da(void);
int32_t function_31d(int32_t a1);
int32_t function_481(void);
int32_t function_48d(void);
int32_t function_55b(void);
int32_t function_565(int32_t a1);
int32_t function_588(int32_t a1);
int32_t function_59f(int32_t a1);
int32_t function_5b6(void);
int32_t function_5bc(void);
int32_t function_8b3(int32_t a1);
int32_t function_8d902c8d(int32_t a1);
int32_t function_9b2(void);
int32_t function_c7f(void);
int32_t function_cb0(void);
int32_t function_cd0(void);
int32_t function_cd2(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_ce3(void);
int32_t function_cf4(void);
int32_t function_cfa(void);
int32_t function_d00(void);
int32_t function_d03(void);
int32_t function_de6(int32_t a1, int32_t a2);
int32_t function_e00(void);
int32_t function_e7e(int32_t a1, int32_t a2);
int32_t function_e98(void);
int32_t function_ebd(void);
int32_t function_ebf(void);
int32_t function_ec4(void);
int32_t function_f33(int32_t a1);
int32_t function_ff2(int32_t a1);
int32_t function_fffa8301(void);
int32_t unknown_2fe0(int32_t a1, int32_t a2);
int32_t unknown_3040(int32_t a1, int32_t a2);
int32_t unknown_33b0(int32_t a1);
int32_t unknown_34d0(int32_t a1, int32_t a2);
int32_t unknown_3540(int32_t a1, int32_t a2, int32_t a3);
int32_t unknown_37b0(int32_t a1, int32_t a2);
int32_t unknown_3ee0(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t unknown_3fd0(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t unknown_40d0(int32_t a1, int32_t a2);
int32_t unknown_45c0(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

bool g1 = false; // cf
int32_t g2 = 0; // eax
int32_t g3 = 0; // ebp
int32_t g4 = 0; // ebx
int32_t g5 = 0; // ecx
int32_t g6 = 0; // edi
int32_t g7 = 0; // esi
int32_t g8 = 0; // esp
int3_t g9 = 0; // fpu_stat_TOP
char * g10 = "\xec\x2c\x65\xa1\x14";
int32_t g11 = 1680;
char * g13;
char g19 = 15;
int32_t g14 = 0;
int32_t g16 = 3904;
int32_t g17 = 0;
int32_t g20 = 1536;
int32_t g21 = 8;
char * g23 = "\xa1\x14";
char g24 = 0;
int32_t g25 = 0x24448900;
char g26 = -125;
bool g27 = false; // of
bool g28 = false; // sf
float80_t g29 = 0.0L; // st0
bool g30 = false; // zf
struct vtable_26f0_type g12 = {
    .e0 = _ZN5boost6system12system_errorD1Ev,
    .e1 = _ZN5boost6system12system_errorD0Ev,
    .e2 = _ZNK5boost6system12system_error4whatEv
};
struct vtable_2928_type g15 = {
    .e0 = _ZN5boost16exception_detail10bad_alloc_D1Ev,
    .e1 = _ZN5boost16exception_detail10bad_alloc_D0Ev
};
struct vtable_2968_type g18 = {
    .e0 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev,
    .e1 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev,
    .e2 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv,
    .e3 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv
};
char * g22[3] = {
    "N5boost6detail15sp_counted_baseE",
    (char *)&g25,
    "N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE"
};

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x3
// Demangled:     Checkpoints::Checkpoints()
int32_t _ZN11Checkpoints11CheckpointsEv(void) {
    // 0x0
    return 0;
}

// From module:   /usr/include/boost/exception/exception.hpp
// Address range: 0x20 - 0x3f
// Line range:    404 - 561
void _7e_clone_impl(int32_t this, int32_t __in_chrg) {
    char * v1 = (char *)0x1cb801f8; // bp+20
    unsigned char v2 = *v1; // bp+20
    int32_t v3 = 0; // eax
    unsigned char v4 = (char)v3; // bp+20
    unsigned char v5 = v4 + v2; // bp+20
    *v1 = v5;
    unsigned char v6 = (char)v3; // bp+26
    bool v7 = v6 > 153 | v5 < v2; // bp+26
    int32_t v8;
    if (v4 % 16 + v2 % 16 > 15 || (v6 & 14) > 9) {
        // bb
        v8 = (int32_t)((v7 ? 102 : 6) + v6) | v3 & -256;
        // branch -> bb102
    } else {
        char v9 = v7 ? v6 + (char)&g24 : v6; // bp+26
        v8 = (int32_t)v9 | v3 & -256;
        // branch -> bb102
    }
    char * v10 = (char *)v8; // bp+27
    *v10 = *v10 + (char)v8;
    if ((*(int32_t *)20 ^ this) != 0) {
        // 0x3f
        return;
    }
}

// From module:   /parallelcoin/src/checkpoints.cpp
// Address range: 0x50 - 0x180
// Line range:    68 - 132
// Demangled:     Checkpoints::CheckBlock(int, uint256 const &)
void _ZN11Checkpoints10CheckBlockEiRK7uint256(int32_t nHeight, int32_t hash) {
    // 0x50
    int32_t v1; // bp-92
    int32_t v2 = &v1; // bp+58
    if (*(char *)1480 != 0) {
        // 0xa6
        // branch -> 0xb9
      lab_0xb9:
        while (true) {
            // branch -> 0xb9
            while (true) {
                // 0xb9
                int32_t v3;
                if (*(int32_t *)(v3 + 16) < nHeight) {
                    // 0xbe
                    v3 += 12;
                    if (v3 == 0) {
                        // break -> 0xce
                        break;
                    }
                    // continue -> 0xb9
                    continue;
                } else {
                    int32_t v4 = *(int32_t *)(v3 + (int32_t)&g25);
                    if (v4 == 0) {
                        // break (via goto) -> 0xce
                        goto lab_0xce;
                    }
                    v3 = v4;
                    // continue (via goto) -> 0xb9
                    goto lab_0xb9;
                }
              lab_0xce:
                // 0xce
                if (*(int32_t *)(v3 + 16) <= nHeight) {
                    int32_t v5 = 0; // bp+152
                    // branch -> 0x148
                    while (true) {
                        int32_t v6 = 4 * v5; // bp+148
                        if (*(int32_t *)(v2 + 12 + v6) != *(int32_t *)(v2 + 44 + v6)) {
                            // 0x168
                            // branch -> 0x78
                        } else {
                            // 0x152
                            if (v5 == 8 - (int32_t)&g10) {
                                // break -> 0x15a
                                break;
                            }
                            v5 += (int32_t)&g10;
                            // continue -> 0x148
                            continue;
                        }
                        // 0x8b
                        return;
                    }
                    // 0x15a
                    // branch -> 0x78
                }
                // 0x8b
                return;
            }
        }
    }
}

// From module:   /parallelcoin/src/checkpoints.cpp
// Address range: 0x180 - 0x1b2
// Line range:    81 - 109
// Demangled:     Checkpoints::GuessVerificationProgress(CBlockIndex *)
void _ZN11Checkpoints25GuessVerificationProgressEP11CBlockIndex(int32_t pindex) {
    // 0x180
    g2 = 0;
    if (pindex == 0) {
        // bb
        function_2c8(*(int32_t *)20);
        // branch -> 0x1ab
    }
}

// Address range: 0x1b8 - 0x1bb
int32_t function_1b8(void) {
    // 0x1b8
    return 0;
}

// Address range: 0x1d2 - 0x1d5
int32_t function_1d2(void) {
    // 0x1d2
    return 0;
}

// Address range: 0x1ea - 0x1eb
int32_t function_1ea(void) {
    // 0x1ea
    return g2;
}

// Address range: 0x226 - 0x22b
int32_t function_226(void) {
    // 0x226
    return 0;
}

// Address range: 0x240 - 0x241
int32_t function_240(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x240
    return g2;
}

// Address range: 0x244 - 0x269
int32_t function_244(void) {
    // 0x244
    int32_t v1;
    if (*(int32_t *)20 != v1) {
        // bb
        function_2da();
        // branch -> 0x255
    }
    // 0x255
    return g2;
}

// Address range: 0x270 - 0x2c8
int32_t function_270(int64_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x270
    int32_t v1; // bp+270
    if (!(bool)false) {
        // bb
        v1 = function_2d0();
        g2 = v1;
        // branch -> 0x272
    } else {
        // 0x270
        v1 = g2;
        // branch -> 0x272
    }
    uint32_t v2 = (int32_t)a1; // bp+280
    return function_240(v1, 0, g7 - v2, (int32_t)(g7 < v2) - a2);
}

// Address range: 0x2c8 - 0x2cf
int32_t function_2c8(int32_t a1) {
    // 0x2c8
    g29 = 0.0L;
    g9 -= (int3_t)&g10;
    return function_244();
}

// Address range: 0x2d0 - 0x2da
int32_t function_2d0(void) {
    int32_t v1 = g2;
    int32_t result = v1;
    if (v1 > g7) {
        // bb
        result = function_1ea();
        // branch -> 0x2d8
    }
    // 0x2d8
    return result;
}

// Address range: 0x2da - 0x2e0
float80_t function_2da(void) {
    // 0x2da
    return g29;
}

// From module:   /parallelcoin/src/checkpoints.cpp
// Address range: 0x2f0 - 0x315
// Line range:    111 - 119
// Demangled:     Checkpoints::GetTotalBlocksEstimate()
void _ZN11Checkpoints22GetTotalBlocksEstimateEv(void) {
    // 0x2f0
    g2 = 0;
    function_31d(*(int32_t *)20);
}

// Address range: 0x31d - 0x32e
int32_t function_31d(int32_t a1) {
    // 0x31d
    if (*(int32_t *)20 != a1) {
        // 0x32e
        return g2;
    }
    // 0x32a
    return g2;
}

// From module:   /parallelcoin/src/checkpoints.cpp
// Address range: 0x340 - 0x3a1
// Line range:    121 - 136
// Demangled:     Checkpoints::GetLastCheckpoint(std::map<uint256, CBlockIndex *, std::less<uint256>, std::allocator<std::pair<uint256 const, CBlockIndex *> > > const &)
void _ZN11Checkpoints17GetLastCheckpointERKSt3mapI7uint256P11CBlockIndexSt4lessIS1_ESaISt4pairIKS1_S3_EEE(int32_t mapBlockIndex) {
    // 0x340
    g4 = 0;
    int32_t v1 = *(int32_t *)function_565(*(int32_t *)20); // bp+374
    int32_t v2 = v1 + (int32_t)&g23; // bp+376
    if (v2 == *(int32_t *)(v1 + 12)) {
        // bb
        function_565(v2);
        // branch -> 0x38c
    }
}

// Address range: 0x481 - 0x488
int32_t function_481(void) {
    // 0x481
    return function_fffa8301();
}

// Address range: 0x48d - 0x48e
int32_t function_48d(void) {
    // 0x48d
    return g2;
}

// Address range: 0x55b - 0x562
int32_t function_55b(void) {
    // 0x55b
    return function_fffa8301();
}

// Address range: 0x565 - 0x582
int32_t function_565(int32_t a1) {
    // 0x565
    g2 = g4;
    int32_t result = g4; // bp+581
    if (*(int32_t *)20 != a1) {
        // bb
        result = function_5bc();
        // branch -> 0x577
    }
    // 0x577
    return result;
}

// Address range: 0x588 - 0x594
int32_t function_588(int32_t a1) {
    // 0x588
    g2 = a1;
    return function_48d();
}

// Address range: 0x59f - 0x5b6
int32_t function_59f(int32_t a1) {
    int32_t * v1 = (int32_t *)-0x74d3dbbc;
    *v1 = *v1 - (int32_t)&g10;
    g4 = 0;
    int32_t * v2;
    return function_565((int32_t)&v2);
}

// Address range: 0x5b6 - 0x5bc
int32_t function_5b6(void) {
    // 0x5b6
    return 0;
}

// Address range: 0x5bc - 0x5c0
int32_t function_5bc(void) {
    // 0x5bc
    return g2;
}

// Address range: 0x5d0 - 0x5ff
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1) {
    // 0x5d0
    *a1 = (int32_t)&g17;
    // 0x5f6
    return 0;
}

// Address range: 0x600 - 0x62a
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1) {
    // 0x600
    *a1 = (int32_t)&g20;
    // 0x626
    return 0;
}

// Address range: 0x630 - 0x680
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_base::destroy()
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(int32_t * a1) {
    // 0x630
    if (a1 == NULL) {
        // 0x675
        return 0;
        // 0x679
        return 0;
    }
    // 0x655
    return *(int32_t *)(*a1 + (int32_t)&g23);
    // 0x679
    return 0;
}

// Address range: 0x690 - 0x6ba
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1) {
    // 0x690
    *a1 = (int32_t)&g11;
    // 0x6b6
    return 0;
}

// Address range: 0x6c0 - 0x6f4
// Demangled:     boost::system::error_category::default_error_condition(int) const
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t result = (int32_t)a1;
    *a1 = a3;
    *(int32_t *)(result + (int32_t)&g23) = a2;
    // 0x6ee
    return result;
}

// Address range: 0x700 - 0x75f
// Demangled:     boost::system::error_category::equivalent(int, boost::system::error_condition const &) const
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t result = 0;
    int32_t v1;
    if (*(int32_t *)(a3 + (int32_t)&g23) == v1) {
        // 0x758
        int32_t v2;
        result = *(int32_t *)a3 == v2;
        // branch -> 0x744
    }
    // 0x744
    int32_t v3;
    if (*(int32_t *)20 != v3) {
        // 0x75f
    }
    // 0x751
    return result;
}

// Address range: 0x770 - 0x7af
// Demangled:     boost::system::error_category::equivalent(boost::system::error_code const &, int) const
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t * a2, int32_t a3) {
    int32_t result = 0;
    if (*(int32_t *)((int32_t)a2 + (int32_t)&g23) == a1) {
        // 0x7a8
        result = *a2 == a3;
        // branch -> 0x791
    }
    // 0x79e
    return result;
}

// Address range: 0x7c0 - 0x7ea
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1) {
    // 0x7c0
    *a1 = (int32_t)&g20;
    // 0x7e6
    return 0;
}

// Address range: 0x7f0 - 0x840
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::dispose()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(int32_t a1) {
    int32_t v1 = *(int32_t *)(a1 + 12); // bp+803
    if (v1 == 0) {
        // 0x835
        return 0;
        // 0x839
        return 0;
    }
    // 0x817
    return *(int32_t *)(*(int32_t *)v1 + 4);
    // 0x839
    return 0;
}

// Address range: 0x850 - 0x875
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::get_deleter(std::type_info const &)
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(void) {
    // 0x86c
    return 0;
}

// Address range: 0x880 - 0x8ae
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t * a1) {
    // 0x880
    g2 = (int32_t)a1;
    *a1 = (int32_t)&g20;
    int32_t result;
    // 0x880
    result = g2;
    // branch -> 0x8a7
    // 0x8a7
    return result;
}

// Address range: 0x8b3 - 0x8b4
int32_t function_8b3(int32_t a1) {
    // 0x8b3
    return g2;
}

// Address range: 0x8c0 - 0x8f8
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t * a1) {
    // 0x8c0
    *a1 = (int32_t)&g20;
    // 0x8e7
    // branch -> 0x8f3
    // 0x8f3
    return (int32_t)a1;
}

// Address range: 0x900 - 0x938
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t * a1) {
    // 0x900
    *a1 = (int32_t)&g17;
    // 0x927
    // branch -> 0x933
    // 0x933
    return (int32_t)a1;
}

// Address range: 0x940 - 0x978
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t * a1) {
    // 0x940
    *a1 = (int32_t)&g11;
    // 0x967
    // branch -> 0x973
    // 0x973
    return (int32_t)a1;
}

// Address range: 0x980 - 0x987
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    // 0x980
    return _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(a1 - 24);
}

// Address range: 0x990 - 0x9ac
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::rethrow() const
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    // 0x990
    return 0;
}

// Address range: 0x9b2 - 0x9b3
int32_t function_9b2(void) {
    // 0x9b2
    return 0;
}

// Address range: 0xb50 - 0xb57
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1) {
    // 0xb50
    return _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(a1 - 24);
}

// Address range: 0xb60 - 0xbe9
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1) {
    // 0xb60
    abort();
    // UNREACHABLE
}

// Address range: 0xc00 - 0xc60
// From class:    N5boost6system12system_errorE
// Type:          virtual member function
// Demangled:     boost::system::system_error::what() const
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1) {
    int32_t result = *(int32_t *)(a1 + 16);
    if (*(int32_t *)(result - 12) == 0) {
        // 0xc50
        return 0;
    }
    // 0xc29
    g2 = result;
    // 0xc3c
    return result;
}

// Address range: 0xc7f - 0xc80
int32_t function_c7f(void) {
    // 0xc7f
    return g2;
}

// Address range: 0xcb0 - 0xcb8
int32_t function_cb0(void) {
    // 0xcb0
    return 0;
}

// Address range: 0xcd0 - 0xcd2
int32_t function_cd0(void) {
    // 0xcd0
    return function_c7f();
}

// Address range: 0xcd2 - 0xcdc
int32_t function_cd2(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0xcd2
    return g2;
}

// Address range: 0xce3 - 0xce4
int32_t function_ce3(void) {
    // 0xce3
    return g2;
}

// Address range: 0xcf4 - 0xcf5
int32_t function_cf4(void) {
    // 0xcf4
    return 0;
}

// Address range: 0xcfa - 0xcff
int32_t function_cfa(void) {
    // 0xcfa
    return 0;
}

// Address range: 0xd00 - 0xd02
int32_t function_d00(void) {
    // 0xd00
    return function_ce3();
}

// Address range: 0xd03 - 0xd06
int32_t function_d03(void) {
    // 0xd03
    return 0;
}

// Address range: 0xd20 - 0xda5
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::~shared_ptr()
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1) {
    int32_t v1 = *(int32_t *)(a1 + (int32_t)&g23);
    if (v1 != 0) {
        int32_t * v2 = (int32_t *)(v1 + (int32_t)&g23);
        int32_t v3 = *v2 - 1;
        *v2 = v3;
        if (v3 == 0) {
            int32_t * v4 = (int32_t *)(v1 + (int32_t)&g25);
            int32_t v5 = *v4;
            *v4 = v5 - 1;
            if (v5 == 1) {
                // 0xd8f
                return *(int32_t *)(*(int32_t *)v1 + 12);
            }
            // 0xd60
            return 0;
        }
    }
    // 0xd60
    return 0;
}

// Address range: 0xdb0 - 0xdd7
// From class:    N5boost6system12system_errorE
// Type:          constructor
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1) {
    // 0xdb0
    *a1 = (int32_t)&g12;
    return *(int32_t *)((int32_t)a1 + 16);
}

// Address range: 0xde6 - 0xe00
int32_t function_de6(int32_t a1, int32_t a2) {
    int32_t * v1 = (int32_t *)0x651c2444;
    *v1 = *v1 - 1;
    return *(int32_t *)20;
}

// Address range: 0xe00 - 0xe01
int32_t function_e00(void) {
    // 0xe00
    return 0;
}

// Address range: 0xe40 - 0xe67
// From class:    N5boost6system12system_errorE
// Type:          constructor
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD0Ev(int32_t * a1) {
    // 0xe40
    *a1 = (int32_t)&g12;
    return *(int32_t *)((int32_t)a1 + 16);
}

// Address range: 0xe7e - 0xe98
int32_t function_e7e(int32_t a1, int32_t a2) {
    int32_t * v1 = (int32_t *)0x651c2444;
    *v1 = *v1 - 1;
    int32_t v2 = *(int32_t *)20;
    g2 = v2;
    int32_t result = v2;
    if (v2 != 0) {
        // bb
        result = function_ebf();
        // branch -> 0xe8c
    }
    // 0xe8c
    return result;
}

// Address range: 0xe98 - 0xe99
int32_t function_e98(void) {
    // 0xe98
    return 0;
}

// Address range: 0xebd - 0xebf
int32_t function_ebd(void) {
    // 0xebd
    return 0;
}

// Address range: 0xebf - 0xec4
int32_t function_ebf(void) {
    // 0xebf
    return g2;
}

// Address range: 0xec4 - 0xecf
int32_t function_ec4(void) {
    int32_t result = 0; // eax
    int32_t * v1 = (int32_t *)(result - 4);
    *v1 = *v1 - 1;
    return result;
}

// Address range: 0xed0 - 0xf2e
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = *(int32_t *)(v1 + (int32_t)&g23);
    *a1 = (int32_t)&g14;
    if (v2 != 0) {
        // 0xef1
        if ((char)v2 != 0) {
            // 0xf18
            *(int32_t *)(v1 + (int32_t)&g23) = 0;
            // branch -> 0xefd
        }
    }
    // 0xefd
    g2 = 0;
    // 0xf0a
    return 0;
    // 0xf2e
    return 0;
}

// Address range: 0xf33 - 0xf34
int32_t function_f33(int32_t a1) {
    // 0xf33
    return g2;
}

// Address range: 0xf40 - 0xf4a
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1) {
    // 0xf40
    return 0;
}

// Address range: 0xf50 - 0xf9b
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1) {
    // 0xf50
    *a1 = (int32_t)&g15;
    *(int32_t *)((int32_t)a1 + 20) = (int32_t)&g16;
    // 0xf89
    return 0;
}

// Address range: 0xfa0 - 0xfaa
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(uint32_t a1) {
    // 0xfa0
    g1 = a1 < 24;
    return function_1f60(a1 - 24);
}

// Address range: 0xfb0 - 0xfba
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(uint32_t a1) {
    // 0xfb0
    g1 = a1 < 20;
    return function_1f60(a1 - 20);
}

// Address range: 0xfc0 - 0xfee
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(int32_t *)(v1 + 24) = (int32_t)&g17;
    *(int32_t *)v1 = (int32_t)&g15;
    *(int32_t *)(v1 + 20) = (int32_t)&g16;
    return v1 + 20;
}

// Address range: 0xff2 - 0x100d
int32_t function_ff2(int32_t a1) {
    int32_t * v1 = (int32_t *)0x651c2444;
    *v1 = *v1 - 1;
    int32_t result = *(int32_t *)20;
    if (result != 0) {
        // 0x100d
        return result;
    }
    // 0x1000
    return result;
}

// Address range: 0x1020 - 0x1027
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1) {
    // 0x1020
    return _ZN5boost16exception_detail10bad_alloc_D0Ev((int32_t *)(a1 - 20));
}

// Address range: 0x1030 - 0x1079
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g15;
    *(int32_t *)(v1 + 20) = (int32_t)&g16;
    _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE10_M_insert_EPKSt18_Rb_tree_node_baseSC_RKS3_(v1);
    g2 = 0;
    // 0x1071
    return 0;
}

// Address range: 0x107e - 0x107f
int32_t function_107e(void) {
    // 0x107e
    return g2;
}

// Address range: 0x1090 - 0x1097
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    // 0x1090
    return _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev((int32_t *)(a1 - 24));
}

// Address range: 0x10a0 - 0x10a7
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    // 0x10a0
    return _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev((int32_t *)(a1 - 20));
}

// Address range: 0x10b0 - 0x10de
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *(int32_t *)(v1 + 24) = (int32_t)&g17;
    *(int32_t *)v1 = (int32_t)&g15;
    *(int32_t *)(v1 + 20) = (int32_t)&g16;
    return v1 + 20;
}

// Address range: 0x10e2 - 0x1105
int32_t function_10e2(int32_t a1, int32_t a2) {
    int32_t * v1 = (int32_t *)0x75e8241c; // 0x10e2
    *v1 = *v1 - 1;
    int32_t v2 = 0; // 0x10e9
    *(char *)v2 = (char)v2 + *(char *)&g2;
    int32_t result = *(int32_t *)20 ^ a1; // 0x10ef
    if (result == 0) {
        // 0x10f8
        // branch -> 0x1105
    }
    // 0x1105
    return result;
}

// Address range: 0x1110 - 0x114b
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD0Ev(int32_t a1) {
    // 0x1110
    g2 = 0;
    function_1fe0(a1);
    // 0x1139
    // branch -> 0x1146
    // 0x1146
    return 0;
}

// Address range: 0x1150 - 0x1195
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::~refcount_ptr()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t * a1) {
    int32_t v1 = *a1; // 0x1164
    if (v1 != 0) {
        // 0x116a
        if ((char)v1 != 0) {
            // 0x1188
            *a1 = 0;
            // branch -> 0x1176
        }
    }
    // 0x1183
    return 0;
}

// Address range: 0x11a0 - 0x12cb
// Demangled:     boost::exception_detail::copy_boost_exception(boost::exception *, boost::exception const *)
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t a2) {
    // 0x11a0
    g7 = a1;
    if (*(int32_t *)(a2 + (int32_t)&g23) != 0) {
        // 0x11da
        int32_t v1;
        if (v1 != 0) {
            // 0x11f9
            // branch -> 0x1201
        }
        // 0x1201
        // branch -> 0x1229
    }
    int32_t v2 = 0; // edi
    *(int32_t *)(a1 + 12) = *(int32_t *)(a2 + 12);
    *(int32_t *)(g7 + 16) = *(int32_t *)(a2 + 16);
    int32_t v3 = *(int32_t *)(a2 + (int32_t)&g25); // 0x1235
    *(int32_t *)(g7 + (int32_t)&g25) = v3;
    int32_t v4 = *(int32_t *)(g7 + (int32_t)&g23); // 0x123b
    if (v4 != 0) {
        // 0x1242
        *(int32_t *)g8 = v4;
        // branch -> 0x124a
    }
    // 0x124a
    *(int32_t *)(g7 + (int32_t)&g23) = v2;
    if (v2 != 0) {
        // 0x1251
        *(int32_t *)g8 = v2;
        // branch -> 0x1259
    }
    int32_t v5 = *(int32_t *)(g8 + 20); // 0x1259
    int32_t v6 = g8; // 0x12ab
    if (v5 != 0) {
        // 0x1261
        *(int32_t *)g8 = v5;
        v6 = g8;
        // branch -> 0x1269
    }
    int32_t result = *(int32_t *)20 ^ *(int32_t *)(v6 + 28); // 0x126d
    g1 = false;
    g2 = result;
    if (result == 0) {
        // 0x1276
        return result;
    }
    // 0x12a4
    g4 = result;
    int32_t v7; // bp-36
    *(int32_t *)v6 = (int32_t)&v7;
    function_22f0();
    // branch -> 0x12b3
    while (true) {
        int32_t v8 = g8 + 20; // 0x12b3
        g2 = v8;
        *(int32_t *)g8 = v8;
        function_22f0();
        *(int32_t *)g8 = g4;
        // branch -> 0x12b3
    }
}

// Address range: 0x1390 - 0x148a
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t * a1) {
    // 0x1390
    g2 = 0;
    int32_t v1 = (int32_t)&g15; // bp-56
    int32_t v2 = (int32_t)&g18; // bp-84
    function_14e8((int32_t)&v2, (int32_t)&v1);
    *a1 = 0;
    *(int32_t *)((int32_t)a1 + (int32_t)&g23) = (int32_t)&g21;
    *(int32_t *)&g22 = (int32_t)"N5boost6detail15sp_counted_baseE" + 1;
    int32_t v3; // bp-64
    return &v3;
}

// Address range: 0x14b2 - 0x14e4
int32_t function_14b2(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t * v1 = (int32_t *)-0x5a17dbc4; // 0x14b2
    *v1 = *v1 - (int32_t)&g10;
    int32_t result = -0x27770000; // 0x14b8
    g2 = result;
    if (*(int32_t *)20 != a1) {
        // bb
        result = function_15b4();
        // branch -> 0x14ce
    }
    // 0x14ce
    return result;
}

// Address range: 0x14e8 - 0x14ef
int32_t function_14e8(int32_t a1, int32_t a2) {
    // 0x14e8
    return g2;
}

// Address range: 0x15af - 0x15b4
int32_t function_15af(void) {
    // 0x15af
    return 0;
}

// Address range: 0x15b4 - 0x15b5
int32_t function_15b4(void) {
    // 0x15b4
    return g2;
}

// Address range: 0x15d4 - 0x15d5
int32_t function_15d4(void) {
    // 0x15d4
    return 0;
}

// Address range: 0x15dd - 0x15de
int32_t function_15dd(int32_t a1) {
    // 0x15dd
    return g2;
}

// Address range: 0x15e8 - 0x160a
int32_t function_15e8(void) {
    int32_t * v1 = (int32_t *)0x5fe82434; // 0x15e8
    *v1 = *v1 - 1;
    int32_t v2 = 0; // eax
    unsigned char v3 = (char)v2 & -24; // 0x15f3
    int32_t v4 = v2 & -0x3c890100 | (int32_t)v3 | 0x3c890000; // 0x15f3
    g2 = v4;
    char * v5 = (char *)v4; // 0x15f7
    *v5 = *v5 + v3;
    return function_15dd(0);
}

// Address range: 0x160a - 0x1612
int32_t function_160a(void) {
    // 0x160a
    int32_t * v1;
    return function_15dd((int32_t)&v1);
}

// Address range: 0x1612 - 0x1626
int32_t function_1612(void) {
    // 0x1612
    int32_t v1;
    return function_22e0(v1);
}

// Address range: 0x1630 - 0x1696
int32_t _ZN9base_uintILj256EE6SetHexEPKc(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    *a1 = 0;
    *(int32_t *)(v1 + (int32_t)&g23) = 0;
    *(int32_t *)(v1 + (int32_t)&g25) = 0;
    *(int32_t *)(v1 + 12) = 0;
    *(int32_t *)(v1 + 16) = 0;
    *(int32_t *)(v1 + 20) = 0;
    *(int32_t *)(v1 + 24) = 0;
    *(int32_t *)(v1 + 28) = 0;
    return (int32_t)*(char *)a2;
}

// Address range: 0x169a - 0x1747
int32_t function_169a(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t * v1 = (int32_t *)-0x76168a40; // 0x169a
    *v1 = *v1 + (int32_t)&g10;
    int32_t v2 = 0; // ebx
    int32_t v3 = 0; // 0x16ac
    int32_t v4 = v3 % 256; // 0x16b0
    int32_t v5 = v2; // 0x16c0
    int32_t v6; // eax
    int32_t v7; // edi
    int32_t v8; // 0x16d9
    int32_t v9; // 0x16dc
    int32_t v10; // 0x16fe
    int32_t v11; // 0x16c0
    int32_t v12; // 0x16d9
    int32_t v13; // 0x16e17
    int32_t v14; // 0x16c3
    int32_t v15; // 0x16e1
    if (*(char *)(v4 + (int32_t)&g13) == 0) {
        v8 = v2;
        // 0x16d4
        if ((char)v3 != 48) {
            // 0x16d9
            v12 = v8 - (int32_t)&g10;
            v6 = v12;
            v7 = 0;
            v9 = v7;
            int32_t v16 = v12;
            uint32_t v17 = v9; // 0x16df
            // branch -> 0x16df
            while (true) {
                // 0x16df
                v15 = (int32_t)(v17 < v9 + 32) | v4 & -256;
                v10 = v16;
                // branch -> 0x16ea
              lab_0x16ea_2:
                while (true) {
                    // 0x16ea
                    if (v2 <= v10) {
                        // 0x16ee
                        if ((char)v15 != 0) {
                            int32_t v18 = (int32_t)*(char *)v10; // 0x16f4
                            unsigned char v19 = *(char *)(v18 + (int32_t)&g13); // 0x16f7
                            int32_t v20 = v19; // ecx
                            int32_t v21 = v10 - 1; // 0x16fe
                            int32_t v22 = v21; // edx
                            *(char *)v7 = v19;
                            if (v2 < v21 || v2 == v21) {
                                uint32_t v23 = v6; // 0x1707
                                int32_t v24 = (int32_t)*(char *)(v23 - 1); // 0x1707
                                v6 = v23 - 2;
                                unsigned char v25 = *(char *)(v24 + (int32_t)&g13); // 0x170e
                                int32_t v26 = (int32_t)v25 << (int32_t)&g23; // 0x1715
                                *(char *)v7 = (char)(v20 | v26);
                                int32_t v27 = v7 + (int32_t)&g10; // 0x171c
                                v7 = v27;
                                v16 = v6;
                                v4 = v26;
                                v17 = v27;
                                // branch -> 0x16df
                                break;
                            } else {
                                v6 = v22;
                                v10 = v22;
                                // branch -> 0x16ea
                                continue;
                            }
                        }
                    }
                    int32_t result = *(int32_t *)20 ^ a1; // 0x172c
                    g2 = result;
                    if (result == 0) {
                        // 0x1735
                        return result;
                    }
                    // bb
                    // branch -> 0x1735
                    // 0x1735
                    return function_1761();
                }
            }
        } else {
            v5 = v8;
        }
        while (true) {
          lab_0x16c0:
            // 0x16c0
            v11 = v5 + (int32_t)&g10;
            v14 = (int32_t)*(char *)v11;
            if (*(char *)(v14 + (int32_t)&g13) == 0) {
                v13 = v14;
                v8 = v11;
                // break -> 0x16d4
                break;
            }
            v5 = v11;
            // continue -> 0x16c0
        }
        // 0x16d4
        if ((char)v14 == 48) {
            v5 = v8;
            goto lab_0x16c0;
        }
        // 0x16d9
        v12 = v8 - (int32_t)&g10;
        v6 = v12;
        v9 = v7;
        // branch -> 0x16df
        while (true) {
            // 0x16df
            v15 = (int32_t)(v9 < v9 + 32) | v13 & -256;
            v10 = v12;
            // branch -> 0x16ea
            goto lab_0x16ea_2;
        }
    }
    while (true) {
      lab_0x16c0_2:
        // 0x16c0
        v11 = v5 + (int32_t)&g10;
        v14 = (int32_t)*(char *)v11;
        if (*(char *)(v14 + (int32_t)&g13) == 0) {
            v13 = v14;
            v8 = v11;
            // break -> 0x16d4
            break;
        }
        v5 = v11;
        // continue -> 0x16c0
    }
    // 0x16d4
    if ((char)v14 == 48) {
        v5 = v8;
        goto lab_0x16c0_2;
    }
    // 0x16d9
    v12 = v8 - (int32_t)&g10;
    v6 = v12;
    v9 = v7;
    // branch -> 0x16df
    while (true) {
        // 0x16df
        v15 = (int32_t)(v9 < v9 + 32) | v13 & -256;
        v10 = v12;
        // branch -> 0x16ea
        goto lab_0x16ea_2;
    }
}

// Address range: 0x174c - 0x1761
int32_t function_174c(void) {
    // 0x174c
    return 0;
}

// Address range: 0x1761 - 0x1762
int32_t function_1761(void) {
    // 0x1761
    return g2;
}

// Address range: 0x1770 - 0x17a8
// Demangled:     std::_Deque_base<std::pair<int, uint256>, std::allocator<std::pair<int, uint256> > >::~_Deque_base()
int32_t _ZNSt11_Deque_baseISt4pairIi7uint256ESaIS2_EED1Ev(int32_t * a1) {
    int32_t v1 = *a1; // 0x1786
    g2 = v1;
    int32_t v2 = (int32_t)a1; // 0x178c
    if (v1 == 0) {
        // bb
        g2 = function_17d0(*(int32_t *)20, 0, 0, 0);
        v2 = g6;
        // branch -> 0x178c
    }
    int32_t v3 = *(int32_t *)(v2 + 20); // 0x178f
    int32_t v4; // 0x17a0
    if (*(int32_t *)(v2 + 36) + 4 <= v3) {
        // bb106
        function_17b3();
        v4 = g4;
        // branch -> 0x1799
    } else {
        v4 = v3;
    }
    // 0x1799
    return *(int32_t *)v4;
}

// Address range: 0x17b3 - 0x17ca
int32_t function_17b3(void) {
    // 0x17b3
    int32_t v1;
    int32_t result; // 0x17c9
    if (*(int32_t *)20 != v1) {
        // bb
        result = function_17e4();
        // branch -> 0x17c0
    } else {
        // 0x17b3
        result = g2;
        // branch -> 0x17c0
    }
    // 0x17c0
    return result;
}

// Address range: 0x17d0 - 0x17e4
int32_t function_17d0(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = *(int32_t *)20 ^ a1; // 0x17d4
    g2 = v1;
    int32_t result = v1; // 0x17e3
    if (v1 != 0) {
        // bb
        result = function_17e4();
        // branch -> 0x17dd
    }
    // 0x17dd
    g6 = a4;
    return result;
}

// Address range: 0x17e4 - 0x17e5
int32_t function_17e4(void) {
    // 0x17e4
    return g2;
}

// Address range: 0x17f0 - 0x1827
// Demangled:     std::_Rb_tree<int, std::pair<int const, uint256>, std::_Select1st<std::pair<int const, uint256> >, std::less<int>, std::allocator<std::pair<int const, uint256> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, uint256> > *)
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE8_M_eraseEPSt13_Rb_tree_nodeIS3_E(int32_t a1, int32_t a2) {
    // 0x17f0
    if (a2 != 0) {
        // 0x1812
        return unknown_2fe0(a1, *(int32_t *)(a2 + 12));
    }
    // 0x180e
    return function_1830(*(int32_t *)20, 0, 0, 0);
}

// Address range: 0x1830 - 0x1844
int32_t function_1830(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t result = *(int32_t *)20 ^ a1; // 0x1834
    if (result != 0) {
        // 0x1844
    }
    // 0x183d
    return result;
}

// Address range: 0x1850 - 0x1884
// Demangled:     std::map<int, uint256, std::less<int>, std::allocator<std::pair<int const, uint256> > >::~map()
int32_t _ZNSt3mapIi7uint256St4lessIiESaISt4pairIKiS0_EEED1Ev(int32_t a1) {
    // 0x1850
    unknown_3040(a1, *(int32_t *)(a1 + (int32_t)&g25));
    // 0x1880
    return 0;
}

// Address range: 0x1890 - 0x18d9
// Demangled:     std::_Deque_base<std::pair<int, uint256>, std::allocator<std::pair<int, uint256> > >::_M_initialize_map(unsigned int)
int32_t _ZNSt11_Deque_baseISt4pairIi7uint256ESaIS2_EE17_M_initialize_mapEj(int32_t a1, uint32_t a2) {
    uint32_t v1 = (a2 >> (int32_t)&g10) / 7 + 3; // 0x18c7
    int32_t v2 = v1 < 8 ? (int32_t)&g25 : v1; // 0x18cd
    *(int32_t *)(a1 + (int32_t)&g23) = v2;
    return &g25;
}

// Address range: 0x18df - 0x18eb
int32_t function_18df(void) {
    int32_t v1 = 0; // eax
    g2 = v1 + (int32_t)(char)&g19 & 255 | v1 & -256;
    int32_t v2;
    return function_8d902c8d(v2);
}

// Address range: 0x18f3 - 0x18f5
int32_t function_18f3(void) {
    // 0x18f3
    return 0;
}

// Address range: 0x18f8 - 0x18f9
int32_t function_18f8(void) {
    // 0x18f8
    return g2;
}

// Address range: 0x1903 - 0x196e
int32_t function_1903(uint32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t * v1 = (int32_t *)0x4c38303; // 0x1903
    *v1 = *v1 - 1;
    int32_t v2 = 0; // esi
    if (v2 > 0) {
        // bb
        function_18f8();
        // branch -> 0x190d
    }
    int32_t v3 = 0; // ebp
    int32_t v4 = 0; // edi
    *(int32_t *)(v4 + 20) = v3;
    *(int32_t *)(v4 + 16) = v3 + 504;
    *(int32_t *)(v4 + 12) = v3;
    *(int32_t *)(v4 + 36) = v2 - 4;
    int32_t v5 = *(int32_t *)(v2 - 4); // ecx
    *(int32_t *)(v4 + (int32_t)&g25) = v3;
    *(int32_t *)(v4 + 32) = v5 + 504;
    *(int32_t *)(v4 + 28) = v5;
    int32_t v6 = 14 * (a1 >> (int32_t)&g10) / 2 / 4; // 0x194b
    *(int32_t *)(v4 + 24) = 36 * (a1 - v6) + v5;
    int32_t v7 = *(int32_t *)20 ^ a2; // 0x195d
    g2 = v7;
    int32_t result = v7; // 0x196d
    if (v7 != 0) {
        // bb105
        result = function_1991();
        // branch -> 0x1966
    }
    // 0x1966
    return result;
}

// Address range: 0x1989 - 0x198b
int32_t function_1989(void) {
    // 0x1989
    return 0;
}

// Address range: 0x1991 - 0x1992
int32_t function_1991(void) {
    // 0x1991
    return g2;
}

// Address range: 0x1997 - 0x1998
int32_t function_1997(void) {
    // 0x1997
    return 0;
}

// Address range: 0x19c2 - 0x19c3
int32_t function_19c2(void) {
    // 0x19c2
    return 0;
}

// Address range: 0x19d0 - 0x1a66
// Demangled:     std::deque<std::pair<int, uint256>, std::allocator<std::pair<int, uint256> > >::_M_reallocate_map(unsigned int, bool)
int32_t _ZNSt5dequeISt4pairIi7uint256ESaIS2_EE17_M_reallocate_mapEjb(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t v1 = (int32_t)a1;
    g4 = v1;
    g7 = a2;
    int32_t v2 = *(int32_t *)(v1 + 36); // 0x19f8
    int32_t v3 = *(int32_t *)(v1 + 20); // 0x19fb
    g2 = v3;
    int32_t v4 = *(int32_t *)(v1 + (int32_t)&g23); // 0x1a06
    g3 = v4;
    int32_t v5 = (v2 - v3) / 4 + 1; // 0x1a10
    g6 = v5;
    int32_t v6 = v5 + a2; // 0x1a13
    int32_t v7 = v4; // 0x1a21
    if (v4 <= 2 * v6) {
        int32_t v8 = function_1a70(v2); // 0x1a1f
        g2 = v8;
        v1 = g4;
        v3 = v8;
        a2 = g7;
        v7 = g3;
        // branch -> 0x1a21
    }
    int32_t v9 = (char)a3 != 0 ? 4 * a2 : 0; // 0x1a33
    int32_t v10 = v2 + (int32_t)&g23 - v3; // 0x1a3c
    int32_t v11 = *(int32_t *)v1; // 0x1a3e
    int32_t v12 = v11 + (v7 - v6) / 2 * (int32_t)&g23 + v9; // 0x1a3e
    g7 = v12;
    int32_t v13 = v10 / 4; // 0x1a40
    g5 = v13;
    if (v3 > v12) {
        // bb117
        function_1b40();
        // branch -> 0x1a4b
    }
    // 0x1a4b
    if (v10 < 4) {
        // bb118
        function_1af4();
        // branch -> 0x1a53
    }
    // 0x1a53
    return g6 * (int32_t)&g23 + g7 + -4 * v13;
}

// Address range: 0x1a6b - 0x1a70
int32_t function_1a6b(void) {
    // 0x1a6b
    return function_1af4();
}

// Address range: 0x1a70 - 0x1a98
int32_t function_1a70(int32_t a1) {
    uint32_t v1 = g3; // 0x1a70
    int32_t v2 = g7 >= v1 ? g7 : v1; // 0x1a74
    g2 = v2;
    int32_t v3 = v1 + 2 + v2; // 0x1a77
    g3 = v3;
    int32_t v4; // 0x1a87
    if (v3 >= 0x40000000) {
        // bb
        function_1b59();
        v4 = g3;
        // branch -> 0x1a87
    } else {
        v4 = v3;
    }
    // 0x1a87
    g7 *= 4;
    return v4 * (int32_t)&g23;
}

// Address range: 0x1af4 - 0x1b39
int32_t function_1af4(void) {
    // 0x1af4
    *(int32_t *)(g4 + 20) = g7;
    *(int32_t *)(g4 + 12) = g7;
    *(int32_t *)(g4 + 16) = g7 + 504;
    int32_t v1 = g7 - 4 + g6 * (int32_t)&g23; // 0x1b04
    *(int32_t *)(g4 + 36) = v1;
    int32_t v2 = *(int32_t *)v1; // 0x1b0b
    *(int32_t *)(g4 + 28) = v2;
    int32_t v3 = v2 + 504; // 0x1b10
    g2 = v3;
    int32_t v4;
    int32_t v5 = *(int32_t *)20 ^ v4; // 0x1b19
    g5 = v5;
    *(int32_t *)(g4 + 32) = v3;
    int32_t result; // 0x1b38
    if (v5 != 0) {
        // bb
        result = function_1b5e();
        // branch -> 0x1b25
    } else {
        // 0x1af4
        result = g2;
        // branch -> 0x1b25
    }
    // 0x1b25
    g27 = (g8 + 76 & (g8 ^ -0x80000000)) < 0;
    return result;
}

// Address range: 0x1b40 - 0x1b52
int32_t function_1b40(void) {
    // 0x1b40
    int32_t result; // 0x1b4f
    if (g5 == 0) {
        // bb
        result = function_1af4();
        // branch -> 0x1b44
    } else {
        // 0x1b40
        result = g2;
        // branch -> 0x1b44
    }
    // 0x1b44
    return result;
}

// Address range: 0x1b57 - 0x1b59
int32_t function_1b57(void) {
    // 0x1b57
    return function_1af4();
}

// Address range: 0x1b59 - 0x1b5a
int32_t function_1b59(void) {
    // 0x1b59
    return g2;
}

// Address range: 0x1b5e - 0x1b60
int32_t function_1b5e(void) {
    // 0x1b5e
    return g2;
}

// Address range: 0x1b70 - 0x1ba5
// Demangled:     std::deque<std::pair<int, uint256>, std::allocator<std::pair<int, uint256> > >::_M_push_back_aux(std::pair<int, uint256> const &)
int32_t _ZNSt5dequeISt4pairIi7uint256ESaIS2_EE16_M_push_back_auxERKS2_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    g4 = v1;
    int32_t v2 = *(int32_t *)(v1 + (int32_t)&g23); // 0x1b96
    int32_t v3 = v2 - (*(int32_t *)(v1 + 36) - *a1) / 4; // 0x1b96
    int32_t result = v3; // 0x1b9e
    if ((v3 || 1) == 1) {
        // bb
        result = function_1c18(*(int32_t *)20, 0, 0, 0);
        // branch -> 0x1b9e
    }
    // 0x1b9e
    return result;
}

// Address range: 0x1ba9 - 0x1c17
int32_t function_1ba9(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t * v1 = (int32_t *)0x438b0447; // 0x1ba9
    *v1 = *v1 - 1;
    char * v2 = (char *)-0x74cb8b40; // 0x1baf
    int32_t v3 = 0; // eax
    *v2 = *v2 - (char)v3 + (char)false;
    *(int32_t *)v3 = 0;
    int32_t v4 = 0; // esi
    int32_t v5 = *(int32_t *)(v4 + (int32_t)&g23); // 0x1bb8
    *(int32_t *)(v3 + (int32_t)&g23) = v5;
    int32_t v6 = *(int32_t *)(v4 + (int32_t)&g25); // 0x1bbe
    *(int32_t *)(v3 + (int32_t)&g25) = v6;
    *(int32_t *)(v3 + 12) = *(int32_t *)(v4 + 12);
    *(int32_t *)(v3 + 16) = *(int32_t *)(v4 + 16);
    *(int32_t *)(v3 + 20) = *(int32_t *)(v4 + 20);
    *(int32_t *)(v3 + 24) = *(int32_t *)(v4 + 24);
    *(int32_t *)(v3 + 28) = *(int32_t *)(v4 + 28);
    *(int32_t *)(v3 + 32) = *(int32_t *)(v4 + 32);
    int32_t v7 = 0; // ebx
    int32_t * v8 = (int32_t *)(v7 + 36); // 0x1be8
    int32_t v9 = *v8; // 0x1be8
    *v8 = v9 + 4;
    int32_t v10 = *(int32_t *)(v9 + 4); // 0x1bf1
    *(int32_t *)(v7 + 28) = v10;
    *(int32_t *)(v7 + 24) = v10;
    int32_t v11 = *(int32_t *)20 ^ a1; // 0x1c04
    g2 = v11;
    *(int32_t *)(v7 + 32) = v10 + 504;
    int32_t result; // 0x1c16
    if (v11 != 0) {
        // bb
        result = function_1c38((int32_t)0);
        // branch -> 0x1c10
    } else {
        // 0x1ba9
        result = g2;
        // branch -> 0x1c10
    }
    // 0x1c10
    return result;
}

// Address range: 0x1c18 - 0x1c38
int32_t function_1c18(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x1c18
    return unknown_3540(g4, (int32_t)&g10, 0);
}

// Address range: 0x1c38 - 0x1c39
int32_t function_1c38(int32_t a1) {
    // 0x1c38
    return g2;
}

// Address range: 0x1c40 - 0x1ecb
// Demangled:     boost::assign_detail::generic_list<std::pair<boost::assign_detail::assign_decay<int>::type, boost::assign_detail::assign_decay<uint256>::type> > boost::assign::map_list_of<int, uint256>(int const &, uint256 const &)
int32_t _ZN5boost6assign11map_list_ofIi7uint256EENS_13assign_detail12generic_listISt4pairINS3_12assign_decayIT_E4typeENS6_IT0_E4typeEEEERKS7_RKSA_(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    // 0x1c40
    int32_t v1; // bp-144
    int32_t v2 = &v1; // 0x1c5e
    int32_t result = (int32_t)a1; // esi
    __asm_rep_stosd_memset((char *)&v1, 0, 10);
    unknown_34d0(v2, 0);
    int32_t v3 = *(int32_t *)(a3 + (int32_t)&g23); // 0x1c95
    int32_t v4 = *(int32_t *)a2; // 0x1c9c
    int32_t v5 = v4; // bp-104
    int32_t v6;
    int32_t v7;
    int32_t v8;
    if (v7 == v8 - 36) {
        // 0x1eae
        unknown_37b0(v2, (int32_t)&v5);
        v6 = v7;
        // branch -> 0x1d58
    } else {
        // 0x1d13
        if (v7 != 0) {
            // 0x1d17
            *(int32_t *)v7 = v4;
            *(int32_t *)(v7 + (int32_t)&g23) = *(int32_t *)a3;
            *(int32_t *)(v7 + (int32_t)&g25) = v3;
            *(int32_t *)(v7 + 12) = *(int32_t *)(a3 + (int32_t)&g25);
            *(int32_t *)(v7 + 16) = *(int32_t *)(a3 + 12);
            *(int32_t *)(v7 + 20) = *(int32_t *)(a3 + 16);
            *(int32_t *)(v7 + 24) = *(int32_t *)(a3 + 20);
            *(int32_t *)(v7 + 28) = *(int32_t *)(a3 + 24);
            *(int32_t *)(v7 + 32) = *(int32_t *)(a3 + 28);
            // branch -> 0x1d51
        }
        // 0x1d51
        v6 = v7 + 36;
        // branch -> 0x1d58
    }
    // 0x1d58
    *(int32_t *)result = 0;
    *(int32_t *)(result + (int32_t)&g23) = 0;
    *(int32_t *)(result + (int32_t)&g25) = 0;
    *(int32_t *)(result + 12) = 0;
    int32_t v9;
    int32_t v10 = 0x38e38e39 * (v6 - v9) / 4; // 0x1d91
    *(int32_t *)(result + 16) = 0;
    *(int32_t *)(result + 20) = 0;
    *(int32_t *)(result + 24) = 0;
    *(int32_t *)(result + 28) = 0;
    *(int32_t *)(result + 32) = 0;
    *(int32_t *)(result + 36) = 0;
    int32_t v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15 = v10 + 14 * (v14 - v13) / 4 - 14 + 0x38e38e39 * (v12 - v11) / 4; // 0x1dce
    int32_t result2 = unknown_34d0(result, v15); // eax
    int32_t v16 = *(int32_t *)(result + (int32_t)&g25); // 0x1ddf
    if (v6 == v11) {
        // 0x1e68
        unknown_33b0(v2);
        // 0x1e86
        return result;
    }
    // 0x1e04
    *(int32_t *)v16 = *(int32_t *)v11;
    int32_t v17 = *(int32_t *)(result2 + (int32_t)&g23); // 0x1e0c
    *(int32_t *)(v16 + (int32_t)&g23) = v17;
    int32_t v18 = *(int32_t *)(result2 + (int32_t)&g25); // 0x1e12
    *(int32_t *)(v16 + (int32_t)&g25) = v18;
    *(int32_t *)(v16 + 12) = *(int32_t *)(result2 + 12);
    return result2;
}

// Address range: 0x1ed1 - 0x1ed2
int32_t function_1ed1(void) {
    // 0x1ed1
    return 0;
}

// Address range: 0x1ef0 - 0x1f42
// Demangled:     std::_Rb_tree<int, std::pair<int const, uint256>, std::_Select1st<std::pair<int const, uint256> >, std::less<int>, std::allocator<std::pair<int const, uint256> > >::_M_insert_(std::_Rb_tree_node_base const *, std::_Rb_tree_node_base const *, std::pair<int const, uint256> const &)
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE10_M_insert_EPKSt18_Rb_tree_node_baseSC_RKS3_(int32_t a1) {
    // 0x1ef0
    int32_t v1;
    int32_t result = v1; // 0x1f3b
    if (v1 == 0) {
        // bb
        int32_t v2;
        result = function_1fd0(v2 + (int32_t)&g23);
        // branch -> 0x1f37
    }
    // 0x1f37
    return result;
}

// Address range: 0x1f60 - 0x1f9c
int32_t function_1f60(int32_t a1) {
    char * v1 = (char *)(g4 + 0x48890c4b); // 0x1f60
    unsigned char v2 = *v1; // 0x1f60
    unsigned char v3 = (char)g5; // 0x1f60
    char v4 = g1; // 0x1f60
    char v5 = v2 - v3; // 0x1f60
    *v1 = v5 + v4;
    int32_t v6 = g2; // 0x1f66
    bool v7 = g1 ? v3 != -1 | v2 < v5 - v4 : v2 < v3; // 0x1f66
    bool v8 = v7 | (char)v6 < 139; // 0x1f66
    int32_t v9 = (v6 - (int32_t)(char)&g26 + (int32_t)v7) % 256 | v6 & -256; // eax
    char * v10 = (char *)(g5 + 0x4b8b2048); // 0x1f69
    unsigned char v11 = *v10; // 0x1f69
    unsigned char v12 = v11 + (char)g5; // 0x1f69
    unsigned char v13 = v12 + (char)v8; // 0x1f69
    *v10 = v13;
    int32_t v14 = v9; // 0x1f6f
    bool v15 = v8 ? v13 <= v11 : v12 < v11; // 0x1f6f
    v9 = ((v14 + 137 + (int32_t)v15) % 256 | v14 & -256) - (int32_t)&g10 & ((int32_t)(char)&g26 | -256);
    char * v16 = (char *)(g5 + 0x4b8b2848); // 0x1f75
    unsigned char v17 = *v16; // 0x1f75
    unsigned char v18 = (char)g5; // 0x1f75
    bool v19 = v17 < v18; // cf
    *v16 = v17 - v18;
    int32_t v20 = ((v9 + 119 + (int32_t)v19) % 256 | v9 & -256) - (int32_t)&g10; // 0x1f7d
    v9 = v20 - (int32_t)(char)&g26 & 255 | v20 & -256;
    char * v21 = (char *)(g5 + 0x4c8b3058); // 0x1f81
    *v21 = *v21 & (char)g5;
    return v9 & -236;
}

// Address range: 0x1fa0 - 0x1fd0
int32_t function_1fa0(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t * v1 = (int32_t *)-0x7ce3dbbc; // 0x1fa0
    *v1 = *v1 - (int32_t)&g10;
    int32_t v2 = 0; // 0x1fa7
    int32_t v3 = (v2 + (int32_t)(char)&g10 + (int32_t)false) % 256 | v2 & -256; // 0x1fa7
    int32_t result = 0; // edi
    *(int32_t *)result = v3;
    g2 = result;
    if (*(int32_t *)20 != a1) {
        // bb
        result = function_1fe7();
        // branch -> 0x1fba
    }
    // 0x1fba
    return result;
}

// Address range: 0x1fd0 - 0x1fe7
int32_t function_1fd0(int32_t a1) {
    // 0x1fd0
    return *(int32_t *)(g3 + 16);
}

// Address range: 0x1fe0 - 0x1fe1
int32_t function_1fe0(int32_t a1) {
    // 0x1fe0
    return g2;
}

// Address range: 0x1fe7 - 0x1fec
int32_t function_1fe7(void) {
    // 0x1fe7
    return g2;
}

// Address range: 0x1ff0 - 0x2088
// Demangled:     std::_Rb_tree<int, std::pair<int const, uint256>, std::_Select1st<std::pair<int const, uint256> >, std::less<int>, std::allocator<std::pair<int const, uint256> > >::_M_insert_unique(std::pair<int const, uint256> const &)
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE16_M_insert_uniqueERKS3_(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t v1 = (int32_t)a1;
    g6 = a2;
    g4 = v1;
    int32_t result = *(int32_t *)(a2 + (int32_t)&g25); // 0x200f
    g7 = result;
    int32_t v2; // 0x2077
    if (result == 0) {
        // 0x2077
        v2 = a2 + (int32_t)&g23;
        g7 = v2;
        // branch -> 0x2080
    } else {
        int32_t v3 = *(int32_t *)a3; // 0x201e
        // branch -> 0x2036
        while (true) {
            int32_t v4 = *(int32_t *)(result + 16); // 0x2036
            int32_t v5; // 0x2058
            int32_t result3; // 0x2069
            int32_t v6; // 0x2058
            int32_t result2; // 0x2083
            int32_t v7; // 0x2028
            int32_t v8; // 0x2056
            if (v4 > v3) {
                // 0x2028
                v7 = *(int32_t *)(result + 8);
                if (v7 == 0) {
                    // 0x2046
                    if ((char)&g10 != 0) {
                        // 0x2080
                        if (result != *(int32_t *)(a2 + 12)) {
                            // 0x2085
                            return result;
                        }
                        // bb130
                        result2 = function_20a0(v4);
                        // branch -> 0x2085
                        // 0x2085
                        return result2;
                    }
                    // 0x2052
                    v6 = v1;
                    v5 = result;
                    if (v4 < v3) {
                        // bb
                        v8 = function_20a0(v4);
                        v6 = g4;
                        v5 = v8;
                        // branch -> 0x2058
                    }
                    // 0x2058
                    *(int32_t *)v6 = v5;
                    *(char *)(g4 + (int32_t)&g23) = 0;
                    result3 = g4;
                    g2 = result3;
                    // 0x206d
                    return result3;
                }
            } else {
                int32_t v9 = *(int32_t *)(result + 12); // 0x203d
                if (v9 == 0) {
                    // 0x2052
                    v6 = v1;
                    v5 = result;
                    if (v4 < v3) {
                        // bb
                        v8 = function_20a0(v4);
                        v6 = g4;
                        v5 = v8;
                        // branch -> 0x2058
                    }
                    // 0x2058
                    *(int32_t *)v6 = v5;
                    *(char *)(g4 + (int32_t)&g23) = 0;
                    result3 = g4;
                    g2 = result3;
                    // 0x206d
                    return result3;
                }
                v7 = v9;
            }
            // 0x2034
            g7 = v7;
            result = v7;
            // branch -> 0x2036
        }
    }
    int32_t result4 = 0; // 0x2085
    if (v2 == *(int32_t *)(a2 + 12)) {
        // bb130
        int32_t v10;
        result4 = function_20a0(v10);
        // branch -> 0x2085
    }
    // 0x2085
    return result4;
}

// Address range: 0x20a0 - 0x20d3
int32_t function_20a0(int32_t result) {
    // 0x20a0
    int32_t v1; // bp+44
    unknown_3ee0((int32_t)&v1, g6, 0, g7, result);
    *(char *)(g4 + (int32_t)&g23) = (char)&g10;
    *(int32_t *)g4 = result;
    return result;
}

// Address range: 0x20d3 - 0x20d4
int32_t function_20d3(void) {
    // 0x20d3
    return g2;
}

// Address range: 0x20e0 - 0x2134
// Demangled:     std::_Rb_tree<int, std::pair<int const, uint256>, std::_Select1st<std::pair<int const, uint256> >, std::less<int>, std::allocator<std::pair<int const, uint256> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<int const, uint256> >, std::pair<int const, uint256> const &)
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE17_M_insert_unique_ESt23_Rb_tree_const_iteratorIS3_ERKS3_(int32_t a1, int32_t a2, int32_t a3, int32_t * a4) {
    int32_t v1 = (int32_t)a4;
    g6 = a2;
    g4 = a3;
    g7 = a1;
    g3 = v1;
    int32_t v2 = a3; // 0x211d
    if (a2 + (int32_t)&g23 == a3) {
        // bb
        function_21e8(*(int32_t *)20);
        v2 = g4;
        v1 = g3;
        // branch -> 0x211a
    }
    uint32_t v3 = *(int32_t *)v1; // 0x211a
    uint32_t v4 = *(int32_t *)(v2 + 16); // 0x211d
    int32_t v5 = v3 - v4; // 0x211d
    g27 = ((v5 ^ v3) & (v4 ^ v3)) < 0;
    g30 = v5 == 0;
    g28 = v5 < 0;
    if (v3 >= v4) {
        // bb115
        function_2198();
        v2 = g4;
        // branch -> 0x2122
    }
    int32_t v6 = *(int32_t *)(g6 + 12); // 0x2122
    g2 = v6;
    int32_t result = v6; // 0x2130
    if (v6 == v2) {
        // bb116
        result = function_225e();
        // branch -> 0x212d
    }
    // 0x212d
    return result;
}

// Address range: 0x216c - 0x2195
int32_t function_216c(void) {
    // 0x216c
    g2 = g7;
    int32_t result = g7; // 0x2192
    int32_t v1;
    if (*(int32_t *)20 != v1) {
        // bb
        result = function_2267();
        // branch -> 0x217f
    }
    // 0x217f
    return result;
}

// Address range: 0x2198 - 0x21b0
int32_t function_2198(void) {
    // 0x2198
    if (g30 || g28 != g27) {
        // bb
        function_2228();
        // branch -> 0x219e
    }
    int32_t v1 = *(int32_t *)(g6 + 16); // 0x219e
    g2 = v1;
    int32_t result = v1; // 0x21ac
    if (v1 == g4) {
        // bb3
        result = function_2230();
        // branch -> 0x21a9
    }
    // 0x21a9
    return result;
}

// Address range: 0x21cd - 0x21e6
int32_t function_21cd(void) {
    int32_t v1 = g2; // 0x21cd
    unknown_3fd0(g7, g6, v1, v1);
    return function_216c();
}

// Address range: 0x21e8 - 0x2222
int32_t function_21e8(int32_t a1) {
    // 0x21e8
    int32_t v1; // bp+40
    if (*(int32_t *)(g6 + 20) == 0) {
        // 0x2200
        unknown_40d0((int32_t)&v1, g6);
        *(int32_t *)g7 = a1;
        return function_216c();
    }
    int32_t v2 = *(int32_t *)(g6 + 16); // 0x21ef
    g2 = v2;
    if (*(int32_t *)(v2 + 16) < g3) {
        // bb
        function_2230();
        // branch -> 0x2200
    }
    // 0x2200
    unknown_40d0((int32_t)&v1, g6);
    *(int32_t *)g7 = a1;
    return function_216c();
}

// Address range: 0x2228 - 0x222f
int32_t function_2228(void) {
    // 0x2228
    *(int32_t *)g7 = g4;
    return function_216c();
}

// Address range: 0x2230 - 0x2254
int32_t function_2230(void) {
    // 0x2230
    unknown_3fd0(g7, g6, 0, g2);
    return function_216c();
}

// Address range: 0x2258 - 0x225e
int32_t function_2258(void) {
    // 0x2258
    return 0;
}

// Address range: 0x225e - 0x2267
int32_t function_225e(void) {
    // 0x225e
    return function_21cd();
}

// Address range: 0x2267 - 0x2268
int32_t function_2267(void) {
    // 0x2267
    return g2;
}

// Address range: 0x2270 - 0x229e
// Demangled:     void std::_Rb_tree<int, std::pair<int const, uint256>, std::_Select1st<std::pair<int const, uint256> >, std::less<int>, std::allocator<std::pair<int const, uint256> > >::_M_insert_unique<std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256> &, std::pair<int, uint256> *> >(std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256> &, std::pair<int, uint256> *>, std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256> &, std::pair<int, uint256> *>)
int32_t _ZNSt8_Rb_treeIiSt4pairIKi7uint256ESt10_Select1stIS3_ESt4lessIiESaIS3_EE16_M_insert_uniqueISt15_Deque_iteratorIS0_IiS2_ERSC_PSC_EEEvT_SG_(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x2270
    return *a2;
}

// Address range: 0x22e0 - 0x22ed
int32_t function_22e0(int32_t a1) {
    // 0x22e0
    int32_t v1; // bp+41
    return &v1;
}

// Address range: 0x22f0 - 0x2344
int32_t function_22f0(void) {
    char * v1 = (char *)(g5 - 0x17f7dbbc); // 0x22f0
    *v1 = *v1 - (char)g5 + (char)g1;
    int32_t v2 = g2; // 0x22f7
    *(char *)v2 = (char)v2 & *(char *)&g2;
    char * v3 = (char *)(g4 + 0x24c08303); // 0x22f9
    *v3 = (char)g5 + *v3;
    *(int32_t *)g4 = g2;
    int32_t v4 = g2; // 0x2304
    int32_t result = v4; // 0x2342
    if (v4 == *(int32_t *)(g4 + (int32_t)&g25)) {
        int32_t * v5 = (int32_t *)(g4 + 12); // 0x2328
        int32_t v6 = *v5; // 0x2328
        *v5 = v6 + 4;
        int32_t v7 = *(int32_t *)(v6 + 4); // 0x2331
        *(int32_t *)(g4 + (int32_t)&g23) = v7;
        *(int32_t *)(g4 + (int32_t)&g25) = v7 + 504;
        *(int32_t *)g4 = v7;
        result = v7;
        // branch -> 0x2309
    }
    // 0x2309
    g1 = false;
    int32_t v8;
    if ((*(int32_t *)20 ^ v8) != 0) {
        // 0x2344
        return result;
    }
    // 0x231a
    g1 = g8 > 0xffffffa3;
    return result;
}

// Address range: 0x2350 - 0x240b
int32_t _ZNK5boost13assign_detail12generic_listISt4pairIi7uint256EEcvT_ISt3mapIiS3_St4lessIiESaIS2_IKiS3_EEEEEv(int32_t result, int32_t a2) {
    int32_t v1 = *(int32_t *)(a2 + (int32_t)&g25); // bp-48
    int32_t v2 = *(int32_t *)(a2 + 24); // bp-64
    int32_t v3 = result + (int32_t)&g23; // 0x23ac
    *(int32_t *)(result + 12) = v3;
    *(int32_t *)(result + 16) = v3;
    *(int32_t *)(result + (int32_t)&g23) = 0;
    *(int32_t *)(result + (int32_t)&g25) = 0;
    *(int32_t *)(result + 20) = 0;
    unknown_45c0(result, (int32_t)&v1, (int32_t)&v2);
    // 0x23f5
    return result;
}

// Address range: 0x2430 - 0x244f
int32_t _GLOBAL__sub_I__ZN11Checkpoints8fEnabledE(void) {
    // 0x2430
    return 0;
}

// Address range: 0x247d - 0x247e
int32_t function_247d(void) {
    // 0x247d
    return g2;
}

// Address range: 0x2497 - 0x249d
int32_t function_2497(void) {
    // 0x2497
    return 0;
}

// Address range: 0x25c1 - 0x25dc
int32_t function_25c1(int32_t a1, int32_t a2, int32_t a3) {
    int32_t * v1 = (int32_t *)0xbc2484; // 0x25c1
    *v1 = *v1 - 1;
    int32_t v2 = 0; // eax
    *(char *)v2 = (char)v2 + *(char *)&g2;
    int32_t v3 = *(int32_t *)20 ^ v2; // 0x25c9
    g2 = v3;
    int32_t result = v3; // 0x25db
    if (v3 != 0) {
        // bb
        result = function_2611();
        // branch -> 0x25d2
    }
    // 0x25d2
    return result;
}

// Address range: 0x260c - 0x2611
int32_t function_260c(void) {
    // 0x260c
    return function_247d();
}

// Address range: 0x2611 - 0x2612
int32_t function_2611(void) {
    // 0x2611
    return g2;
}

// Address range: 0x2616 - 0x2617
int32_t function_2616(void) {
    // 0x2616
    return g2;
}

// Address range: 0x2622 - 0x2623
int32_t function_2622(void) {
    // 0x2622
    return g2;
}

// Address range: 0x2632 - 0x2636
int32_t function_2632(void) {
    // 0x2632
    return function_2622();
}

// Address range: 0x2636 - 0x2638
int32_t function_2636(void) {
    // 0x2636
    return function_2616();
}

// Address range: 0x2640 - 0x2642
int32_t function_2640(void) {
    // 0x2640
    return function_2632();
}

// Address range: 0x8d902c8d - 0x8d902c8e
int32_t function_8d902c8d(int32_t a1) {
    // 0x8d902c8d
    return g2;
}

// Address range: 0xfffa8301 - 0xfffa8302
int32_t function_fffa8301(void) {
    // 0xfffa8301
    return g2;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected language: C++
// Detected functions: 163
// Decompilation date: 2018-06-10 00:05:04
