//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct Status {
    char * e0;
};

struct vtable_2b68_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
    int32_t (*e3)(int32_t *);
    int32_t (*e4)(int32_t, int32_t);
};

struct vtable_2c38_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
    int32_t (*e3)(int32_t);
};

struct vtable_2c98_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
};

struct vtable_2cc0_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
};

struct vtable_2cd8_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
};

// ------------------------- Classes --------------------------

// leveldb_error
// N5boost16exception_detail10bad_alloc_E
// N5boost16exception_detail10clone_baseE
// N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE (base classes: N5boost16exception_detail10clone_baseE, N5boost16exception_detail10bad_alloc_E)
// N5boost6detail15sp_counted_baseE
// N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE (base classes: N5boost6detail15sp_counted_baseE)
// N5boost6system12system_errorE
// N5boost9exceptionE

// ------------------- Function Prototypes --------------------

void _7e_CLevelDB(int32_t this, int32_t __in_chrg);
void _7e_clone_impl(int32_t this, int32_t __in_chrg);
void __static_initialization_and_destruction_0(int32_t __initialize_p, int32_t __priority);
void _GLOBAL__sub_I__Z11HandleErrorRKN7leveldb6StatusE(void);
int32_t _Z11HandleErrorRKN7leveldb6StatusE(int32_t a1);
int32_t _ZN13leveldb_errorC1ERKSs(int32_t result, int32_t a2);
int32_t _ZN13leveldb_errorD0Ev(int32_t result);
int32_t _ZN13leveldb_errorD1Ev(int32_t * a1);
int32_t _ZN5boost10error_infoINS_11throw_file_EPKcEC1ES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10error_infoINS_11throw_line_EiEC1Ei(int32_t * a1, int32_t a2);
int32_t _ZN5boost10error_infoINS_15throw_function_EPKcEC1ES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1ERKS4_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1INS1_10clone_implINS1_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1);
int32_t _ZN5boost11filesystem316create_directoryERKNS0_4pathE(int32_t result);
int32_t _ZN5boost12noncopyable_11noncopyableD1Ev(int32_t a1);
int32_t _ZN5boost14checked_deleteINS_16exception_detail10clone_implINS1_10bad_alloc_EEEEEvPT_(int32_t * a1);
int32_t _ZN5boost16exception_detail10bad_alloc_C1ERKS1_(void);
int32_t _ZN5boost16exception_detail10bad_alloc_C1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t a1);
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseC1ERKS1_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_baseC1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t result);
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS2_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t result);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE5adoptEPS2_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7add_refEv(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7releaseEv(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEaSERKS3_(int32_t a1, int32_t * a2);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1ERKS3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t a1);
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t a1);
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t a2);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_file_EPKcEE(int32_t a1, int32_t * a2);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_line_EiEE(void);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_15throw_function_EPKcEE(int32_t a1, int32_t * a2);
int32_t _ZN5boost3argILi1EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi2EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi3EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi4EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi5EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi6EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi7EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi8EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi9EEC1Ev(void);
int32_t _ZN5boost6detail12shared_countC1ERKS1_(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail12shared_countC1INS_16exception_detail10clone_implINS3_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail12shared_countD1Ev(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_base12add_ref_copyEv(int32_t a1);
int32_t _ZN5boost6detail15sp_counted_base12weak_releaseEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_base7releaseEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseC1Ev(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t result);
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1);
int32_t _ZN5boost6detail16atomic_incrementEPi(int32_t * a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(int32_t a1, int32_t a2);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(int32_t a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEC1EPS5_(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t result);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1);
int32_t _ZN5boost6detail23atomic_exchange_and_addEPii(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail26sp_enable_shared_from_thisEz(void);
int32_t _ZN5boost6system12system_errorD0Ev(int32_t result);
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1);
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t result);
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1);
int32_t _ZN5boost6system15error_conditionC1EiRKNS0_14error_categoryE(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZN5boost6systemeqERKNS0_15error_conditionES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost9exceptionC1ERKS0_(int32_t * a1, int32_t a2);
int32_t _ZN5boost9exceptionC1Ev(int32_t * a1);
int32_t _ZN5boost9exceptionD0Ev(int32_t result);
int32_t _ZN5boost9exceptionD1Ev(int32_t * a1);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_file_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_line_EiEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKS8_E4typeESB_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_15throw_function_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2);
int32_t _ZN7leveldb11ReadOptionsC1Ev(char * a1);
int32_t _ZN7leveldb12WriteOptionsC1Ev(char * a1);
int32_t _ZN7leveldb6StatusD1Ev(int32_t * a1);
void _ZN8CLevelDB10WriteBatchER13CLevelDBBatchb(int32_t this, int32_t batch, bool fSync);
int32_t _ZNK5boost11filesystem34path6stringEv(int32_t a1);
void _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t this);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(int32_t a1);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
int32_t _ZNK5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE3getEv(int32_t * a1);
int32_t _ZNK5boost6system10error_code5valueEv(int32_t * a1);
int32_t _ZNK5boost6system10error_code7messageEv(int32_t a1, int32_t a2);
int32_t _ZNK5boost6system10error_code8categoryEv(int32_t a1);
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1);
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t a1, int32_t result);
int32_t _ZNK5boost6system14error_categoryeqERKS1_(int32_t a1, int32_t a2);
int32_t _ZNK7leveldb6Status10IsNotFoundEv(int32_t a1);
int32_t _ZNK7leveldb6Status12IsCorruptionEv(int32_t a1);
int32_t _ZNK7leveldb6Status2okEv(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNK7leveldb6Status4codeEv(int32_t * a1);
int32_t _ZNK7leveldb6Status9IsIOErrorEv(int32_t a1);
int32_t _ZNSt9bad_allocC1ERKS_(int32_t * a1, int32_t a2);
int32_t _ZNSt9bad_allocC1Ev(int32_t result);
int32_t _ZNSt9exceptionC1ERKS_(int32_t * a1, int32_t a2);
int32_t _ZNSt9exceptionC1Ev(int32_t result);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
void CLevelDB(int32_t this, int32_t path, int32_t nCacheSize, bool fMemory, bool fWipe);
int32_t function_1079(int32_t a1);
int32_t function_108a(void);
int32_t function_10c9(void);
int32_t function_1208(void);
int32_t function_12bc(int32_t a1);
int32_t function_1444(int32_t a1);
int32_t function_149(void);
int32_t function_1531(int32_t a1, int32_t a2);
int32_t function_1561(int32_t a1);
int32_t function_161d(void);
int32_t function_1659(void);
int32_t function_16a2(void);
int32_t function_16e3(int32_t a1);
int32_t function_1769(void);
int32_t function_17a9(void);
int32_t function_17e3(int32_t a1, int32_t a2);
int32_t function_182b(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1885(void);
int32_t function_18b5(int32_t a1);
int32_t function_18e6(int32_t a1);
int32_t function_194b(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1964(int32_t a1);
int32_t function_19a2(void);
int32_t function_1a0f(void);
int32_t function_1ad4(void);
int32_t function_1afe(void);
int32_t function_1b0f(void);
int32_t function_1b53(void);
int32_t function_1b90(void);
int32_t function_1ba(void);
int32_t function_1c11(void);
int32_t function_1c25(void);
int32_t function_1c31(void);
int32_t function_1c3a(int32_t a1);
int32_t function_1c49(void);
int32_t function_1c4f(void);
int32_t function_1c66(void);
int32_t function_1c6b(void);
int32_t function_1c9b(int32_t a1);
int32_t function_1ce6(void);
int32_t function_1d5d(void);
int32_t function_1d96(void);
int32_t function_1de8(void);
int32_t function_1e24(void);
int32_t function_1e7a(void);
int32_t function_1ebb(void);
int32_t function_1eef(int32_t a1);
int32_t function_1f25(void);
int32_t function_1f55(int32_t a1);
int32_t function_1f9d(void);
int32_t function_1fd7(int32_t a1, int32_t a2);
int32_t function_2002(int32_t a1);
int32_t function_202c(int32_t a1);
int32_t function_2056(int32_t a1);
int32_t function_2080(int32_t a1);
int32_t function_20aa(int32_t a1);
int32_t function_20c3(int32_t a1, int32_t a2);
int32_t function_20ce(int32_t a1);
int32_t function_20d5(int32_t a1);
int32_t function_20fe(int32_t a1);
int32_t function_2128(int32_t a1);
int32_t function_212b(int32_t a1, int32_t a2);
int32_t function_2152(int32_t a1);
int32_t function_2190(int32_t a1);
int32_t function_21a0(void);
int32_t function_21e5(void);
int32_t function_223c(void);
int32_t function_22b2(void);
int32_t function_22d(void);
int32_t function_22f(void);
int32_t function_22f4(int32_t a1);
int32_t function_22fb(void);
int32_t function_233(void);
int32_t function_2350(int32_t a1);
int32_t function_242d(void);
int32_t function_246(void);
int32_t function_2503(void);
int32_t function_258f(void);
int32_t function_25a8(void);
int32_t function_25aa(void);
int32_t function_25ac(void);
int32_t function_25b9(void);
int32_t function_25bb(void);
int32_t function_25d0(void);
int32_t function_25d5(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_25e(void);
int32_t function_260(void);
int32_t function_264(void);
int32_t function_268d(void);
int32_t function_26c1(int32_t a1);
int32_t function_2734(void);
int32_t function_2758(void);
int32_t function_2769(void);
int32_t function_277(void);
int32_t function_27e8(void);
int32_t function_27f9(void);
int32_t function_2847(void);
int32_t function_288a(void);
int32_t function_28c(void);
int32_t function_28cc(void);
int32_t function_28e(void);
int32_t function_290e(void);
int32_t function_292(void);
int32_t function_2984(void);
int32_t function_29c2(int32_t a1, int32_t a2);
int32_t function_2a00(int32_t a1, int32_t a2);
int32_t function_2a0a(int32_t a1);
int32_t function_2a3e(void);
int32_t function_2a5(void);
int32_t function_2a74(void);
int32_t function_2a7a(void);
int32_t function_2a98(void);
int32_t function_2a9e(int32_t a1);
int32_t function_2ac0(void);
int32_t function_2ac5(void);
int32_t function_2b17(void);
int32_t function_2b59(void);
int32_t function_2ba(void);
int32_t function_2bbe(void);
int32_t function_2bc(void);
int32_t function_2bcf(void);
int32_t function_2c0(void);
int32_t function_2c04(int32_t a1);
int32_t function_2c10(void);
int32_t function_2c40(int32_t a1);
int32_t function_2d2(void);
int32_t function_2d3(void);
int32_t function_2d74(int32_t a1);
int32_t function_2d9(void);
int32_t function_2daa(int32_t a1);
int32_t function_2e6(void);
int32_t function_2f44(int32_t a1, int32_t a2);
int32_t function_2fe2(int32_t a1, int32_t a2);
int32_t function_2ff(int32_t a1, int32_t a2);
int32_t function_2ff6(void);
int32_t function_302b(int32_t a1, int32_t a2);
int32_t function_305a(void);
int32_t function_309e(void);
int32_t function_30a3(void);
int32_t function_30d8(void);
int32_t function_3138(int32_t a1, int32_t a2, int32_t a3);
int32_t function_33e(void);
int32_t function_346(void);
int32_t function_360(void);
int32_t function_38e(void);
int32_t function_4486(int32_t a1);
int32_t function_49(void);
int32_t function_4a3(void);
int32_t function_4bb(void);
int32_t function_4ef3(int32_t a1);
int32_t function_516(void);
int32_t function_598(void);
int32_t function_5ba(void);
int32_t function_626(void);
int32_t function_64d(void);
int32_t function_64f(void);
int32_t function_651(void);
int32_t function_65e(void);
int32_t function_660(int32_t a1);
int32_t function_66c(void);
int32_t function_66e(int32_t a1);
int32_t function_683(void);
int32_t function_688(void);
int32_t function_765(void);
int32_t function_81b(void);
int32_t function_82d(void);
int32_t function_85c(void);
int32_t function_85e(void);
int32_t function_862(void);
int32_t function_880(void);
int32_t function_888(void);
int32_t function_88d(void);
int32_t function_8d0000f7(void);
int32_t function_8f5(void);
int32_t function_8ff(void);
int32_t function_909(void);
int32_t function_9bc(int32_t a1, int32_t a2);
int32_t function_9cd(void);
int32_t function_a05(void);
int32_t function_a39(void);
int32_t function_aa2(int32_t a1);
int32_t function_ada(int32_t a1, int32_t a2);
int32_t function_b12(int32_t a1, int32_t a2);
int32_t function_b4a(int32_t a1, int32_t a2);
int32_t function_ba9(void);
int32_t function_bf1(void);
int32_t function_c08(void);
int32_t function_c19(void);
int32_t function_c9(void);
int32_t function_db(void);
int32_t function_df5(void);
int32_t function_e2f(int32_t a1);
int32_t function_e6e(void);
int32_t function_f4d(void);
int32_t function_f5c(void);
int32_t function_f5e(void);
int32_t function_f73(void);
int32_t function_f78(void);
int32_t GetOptions(int32_t nCacheSize);
int32_t unknown_2c24(int32_t a1);
int32_t unknown_2c7c(int32_t a1);
int32_t unknown_2d34(int32_t a1);
int32_t unknown_2dda(int32_t a1, int32_t a2, int32_t a3);
int32_t unknown_2e82(int32_t a1);
int32_t unknown_2f0c(int32_t a1, int32_t a2);
int32_t unknown_2f6a(int32_t a1);
int32_t unknown_3170(int32_t a1);
int32_t unknown_31be(int32_t a1, int32_t a2);
int32_t unknown_31d3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t unknown_329a(int32_t a1);
int32_t unknown_32ca(int32_t a1);
int32_t unknown_3546(int32_t a1, int32_t a2);
int32_t unknown_357c(int32_t a1);
int32_t unknown_3598(int32_t a1);
int32_t unknown_37f8(int32_t a1, int32_t a2);
int32_t unknown_3ac6(int32_t a1);
int32_t unknown_3baa(int32_t a1, int32_t a2, int32_t a3);
int32_t unknown_3bbe(int32_t a1);
int32_t unknown_3ca6(int32_t a1);
int32_t unknown_3e8c(int32_t a1, int32_t a2);
int32_t unknown_4034(int32_t a1, int32_t a2);
int32_t unknown_40ac(int32_t a1, int32_t a2);
int32_t unknown_4358(int32_t a1, int32_t a2);
int32_t unknown_44d2(int32_t a1);
int32_t unknown_44fe(int32_t a1);
int32_t unknown_4618(int32_t a1);
int32_t unknown_4648(int32_t a1, int32_t a2);
int32_t unknown_4678(int32_t a1);
int32_t unknown_4702(int32_t a1, int32_t a2);
int32_t unknown_4734(int32_t a1);
int32_t unknown_479a(int32_t a1);
int32_t unknown_47e8(int32_t a1);
int32_t unknown_49cc(int32_t a1);
int32_t unknown_4a0e(int32_t a1, int32_t a2);
int32_t unknown_4af4(int32_t a1, int32_t a2);
int32_t unknown_4bb4(int32_t a1);
int32_t unknown_4c7a(int32_t a1, int32_t a2);
int32_t unknown_4cbc(int32_t a1, int32_t a2);
int32_t unknown_4cfe(int32_t a1, int32_t a2);
int32_t unknown_4d54(int32_t a1);
int32_t unknown_4f80(int32_t a1);
int32_t unknown_51d0(int32_t a1, int32_t a2);
int32_t unknown_5250(int32_t a1, int32_t a2);
int32_t unknown_52d0(int32_t a1, int32_t a2);
int32_t unknown_5350(int32_t a1, int32_t a2);
int32_t unknown_53e6(int32_t a1, int32_t a2);
int32_t unknown_550c(int32_t a1);
int32_t unknown_574e(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp
int32_t g3 = 0; // ebx
int32_t g4 = 0; // ecx
int32_t g5 = 0; // edx
int32_t g6 = 0; // esi
int32_t g7 = 0; // esp
int32_t g8 = 0x14a1;
int32_t g9 = -0x1bba7700;
int32_t g12 = 0x2779;
int32_t g13 = 0x302e;
int32_t g15 = 0x223e;
int32_t g18 = 0x1716;
int32_t g19 = 0x1042;
int32_t g20 = 0;
int32_t g21 = 0;
char * g22 = "\x89\x04\x24\xe8\xac\x15";
char * g23 = "\x84\xc0\x74\x71\xc7\x04\x24\x08";
int32_t g24 = 0x65c44589;
struct vtable_2b68_type g10 = {
    .e0 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev,
    .e1 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev,
    .e2 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv,
    .e3 = _ZN5boost6detail15sp_counted_base7destroyEv,
    .e4 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info
};
struct vtable_2c38_type g11 = {
    .e0 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev,
    .e1 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev,
    .e2 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2,
    .e3 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv
};
struct vtable_2c98_type g14 = {
    .e0 = _ZN5boost16exception_detail10bad_alloc_D1Ev,
    .e1 = _ZN5boost16exception_detail10bad_alloc_D0Ev
};
struct vtable_2cc0_type g16 = {
    .e0 = _ZN13leveldb_errorD1Ev,
    .e1 = _ZN13leveldb_errorD0Ev,
    .e2 = _Z11HandleErrorRKN7leveldb6StatusE
};
struct vtable_2cd8_type g17 = {
    .e0 = _ZN5boost6system12system_errorD1Ev,
    .e1 = _ZN5boost6system12system_errorD0Ev,
    .e2 = _ZNK5boost6system12system_error4whatEv
};

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x4
// From class:    leveldb_error
// Type:          virtual member function
// Demangled:     HandleError(leveldb::Status const &)
int32_t _Z11HandleErrorRKN7leveldb6StatusE(int32_t a1) {
    // 0x0
    return g1;
}

// From module:   /usr/include/boost/exception/exception.hpp
// Address range: 0x8 - 0xc
// Line range:    411 - 92
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone() const
void _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t this) {
    // 0x8
    return;
}

// From module:   /usr/include/boost/exception/exception.hpp
// Address range: 0xe - 0x13
// Line range:    404 - 71
void _7e_clone_impl(int32_t this, int32_t __in_chrg) {
    // 0xe
    return;
}

// Address range: 0x49 - 0x4a
int32_t function_49(void) {
    // 0x49
    return 0;
}

// Address range: 0xc9 - 0xca
int32_t function_c9(void) {
    // 0xc9
    return 0;
}

// Address range: 0xdb - 0xe5
int32_t function_db(void) {
    // 0xdb
    g1 = 0;
    return function_8d0000f7();
}

// Address range: 0x149 - 0x14a
int32_t function_149(void) {
    // 0x149
    return 0;
}

// Address range: 0x1ba - 0x1bb
int32_t function_1ba(void) {
    // 0x1ba
    return 0;
}

// Address range: 0x22d - 0x22f
int32_t function_22d(void) {
    // 0x22d
    return function_233();
}

// Address range: 0x22f - 0x233
int32_t function_22f(void) {
    // 0x22f
    return 0;
}

// Address range: 0x233 - 0x239
int32_t function_233(void) {
    // 0x233
    return g2 - 32;
}

// Address range: 0x246 - 0x24f
int32_t function_246(void) {
    // 0x246
    return function_2d9();
}

// Address range: 0x25e - 0x260
int32_t function_25e(void) {
    // 0x25e
    return function_264();
}

// Address range: 0x260 - 0x264
int32_t function_260(void) {
    // 0x260
    return 0;
}

// Address range: 0x264 - 0x26a
int32_t function_264(void) {
    // 0x264
    return g2 - 31;
}

// Address range: 0x277 - 0x27d
int32_t function_277(void) {
    // 0x277
    return function_2d9();
}

// Address range: 0x28c - 0x28e
int32_t function_28c(void) {
    // 0x28c
    return function_292();
}

// Address range: 0x28e - 0x292
int32_t function_28e(void) {
    // 0x28e
    return 0;
}

// Address range: 0x292 - 0x298
int32_t function_292(void) {
    // 0x292
    return g2 - 30;
}

// Address range: 0x2a5 - 0x2ab
int32_t function_2a5(void) {
    // 0x2a5
    return function_2d9();
}

// Address range: 0x2ba - 0x2bc
int32_t function_2ba(void) {
    // 0x2ba
    return function_2c0();
}

// Address range: 0x2bc - 0x2c0
int32_t function_2bc(void) {
    // 0x2bc
    return 0;
}

// Address range: 0x2c0 - 0x2c6
int32_t function_2c0(void) {
    // 0x2c0
    return g2 - 29;
}

// Address range: 0x2d2 - 0x2d3
int32_t function_2d2(void) {
    // 0x2d2
    return g1;
}

// Address range: 0x2d3 - 0x2d9
int32_t function_2d3(void) {
    // 0x2d3
    return function_2d9();
}

// Address range: 0x2d9 - 0x2e1
int32_t function_2d9(void) {
    // 0x2d9
    int32_t result;
    if (g5 == -1) {
        // bb
        result = function_2e6();
        // branch -> 0x2de
    } else {
        // 0x2d9
        result = g1;
        // branch -> 0x2de
    }
    // 0x2de
    return result;
}

// Address range: 0x2e6 - 0x2e9
int32_t function_2e6(void) {
    // 0x2e6
    return g1;
}

// Address range: 0x2ff - 0x308
int32_t function_2ff(int32_t a1, int32_t a2) {
    int32_t * v1 = (int32_t *)0x5e5b4cc4;
    *v1 = *v1 + 1;
    return 0;
}

// From module:   /parallelcoin/src/leveldb.cpp
// Address range: 0x308 - 0x32b
// Line range:    27 - 35
int32_t GetOptions(int32_t nCacheSize) {
    // 0x308
    return nCacheSize;
}

// Address range: 0x33e - 0x341
int32_t function_33e(void) {
    // 0x33e
    return 0;
}

// Address range: 0x346 - 0x34c
int32_t function_346(void) {
    // 0x346
    int32_t v1;
    int32_t result; // bp+349
    if (v1 == -1 || false) {
        // 0x346
        result = g1;
        // branch -> 0x349
    } else {
        // bb
        result = function_2d2();
        // branch -> 0x349
    }
    // 0x349
    return result;
}

// Address range: 0x360 - 0x363
int32_t function_360(void) {
    // 0x360
    return 0;
}

// Address range: 0x38e - 0x393
int32_t function_38e(void) {
    // 0x38e
    return 0;
}

// From module:   /parallelcoin/src/leveldb.h
// Address range: 0x394 - 0x497
// Line range:    37 - 60
void CLevelDB(int32_t this, int32_t path, int32_t nCacheSize, bool fMemory, bool fWipe) {
    char * v1 = (char *)(this + (int32_t)&g22);
    _ZN7leveldb11ReadOptionsC1Ev(v1);
    char * v2 = (char *)(this + (int32_t)&g23);
    _ZN7leveldb11ReadOptionsC1Ev(v2);
    _ZN7leveldb12WriteOptionsC1Ev((char *)(this + 64));
    char * v3 = (char *)(this + 65); // bp+403
    _ZN7leveldb12WriteOptionsC1Ev(v3);
    *(int32_t *)this = 0;
    *v1 = 1;
    *v2 = 1;
    *(char *)(this + 57) = 0;
    *v3 = 1;
    int32_t v4; // bp-124
    GetOptions((int32_t)&v4);
    *(int32_t *)(this + 4) = v4;
    *(char *)(this + 8) = 1;
    if (!fMemory) {
        // bb
        function_4bb();
        // branch -> 0x497
    }
}

// Address range: 0x4a3 - 0x4bb
int32_t function_4a3(void) {
    int32_t * v1 = (int32_t *)-0x2bba743e;
    *v1 = *v1 - 1;
    *(int32_t *)0 = 0;
    int32_t * v2 = (int32_t *)-44;
    int32_t result = *v2;
    *(int32_t *)(result + (int32_t)&g24) = *(int32_t *)*v2;
    return result;
}

// Address range: 0x4bb - 0x503
int32_t function_4bb(void) {
    // 0x4bb
    if (*(char *)(g2 - 60) == 0) {
        // bb
        function_516();
        // branch -> 0x4c1
    }
    // 0x4c1
    _ZNK5boost11filesystem34path6stringEv(*(int32_t *)(g2 - 48));
    return _ZNK5boost11filesystem34path6stringEv(*(int32_t *)(g2 - 48));
}

// Address range: 0x516 - 0x56d
int32_t function_516(void) {
    // 0x516
    _ZN5boost11filesystem316create_directoryERKNS0_4pathE(*(int32_t *)(g2 - 48));
    _ZNK5boost11filesystem34path6stringEv(*(int32_t *)(g2 - 48));
    return _ZNK5boost11filesystem34path6stringEv(*(int32_t *)(g2 - 48));
}

// Address range: 0x598 - 0x599
int32_t function_598(void) {
    // 0x598
    return 0;
}

// Address range: 0x5ba - 0x5bd
int32_t function_5ba(void) {
    // 0x5ba
    return 0;
}

// Address range: 0x626 - 0x640
int32_t function_626(void) {
    int32_t * v1 = (int32_t *)(g2 + 0x489e445); // bp+626
    *v1 = *v1 - 1;
    int32_t v2 = 0;
    unsigned char v3 = (char)v2 & -24;
    char * v4 = (char *)((int32_t)v3 | v2 & -256); // bp+630
    *v4 = *v4 + v3;
    int32_t v5 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // bp+635
    g1 = v5;
    if (v5 == 0) {
        // bb
        g1 = function_688();
        // branch -> 0x63e
    }
    // 0x63e
    return function_683();
}

// Address range: 0x64d - 0x64f
int32_t function_64d(void) {
    // 0x64d
    return function_651();
}

// Address range: 0x64f - 0x651
int32_t function_64f(void) {
    // 0x64f
    return 0;
}

// Address range: 0x651 - 0x65e
int32_t function_651(void) {
    // 0x651
    return function_660(g2 - 16);
}

// Address range: 0x65e - 0x660
int32_t function_65e(void) {
    // 0x65e
    return 0;
}

// Address range: 0x660 - 0x66c
int32_t function_660(int32_t a1) {
    int32_t v1 = g3; // bp+660
    g3 = g6;
    return function_66e(v1);
}

// Address range: 0x66c - 0x66e
int32_t function_66c(void) {
    // 0x66c
    return 0;
}

// Address range: 0x66e - 0x67e
int32_t function_66e(int32_t a1) {
    // 0x66e
    _ZN7leveldb6StatusD1Ev((int32_t *)(g2 - 28));
    return g3;
}

// Address range: 0x683 - 0x688
int32_t function_683(void) {
    // 0x683
    return g1;
}

// Address range: 0x688 - 0x68f
int32_t function_688(void) {
    // 0x688
    return g1;
}

// From module:   /parallelcoin/src/leveldb.h
// Address range: 0x690 - 0x760
// Line range:    62 - 71
void _7e_CLevelDB(int32_t this, int32_t __in_chrg) {
    int32_t * v1 = (int32_t *)(this + 68);
    if (*v1 != 0) {
        // 0x6b1
        // branch -> 0x6c9
    }
    // 0x6c9
    *v1 = 0;
    int32_t * v2 = (int32_t *)(this + 44);
    if (*v2 != 0) {
        // 0x6dd
        // branch -> 0x6f5
    }
    // 0x6f5
    *v2 = 0;
    int32_t * v3 = (int32_t *)(this + 28); // bp+702
    if (*v3 != 0) {
        // 0x709
        // branch -> 0x721
    }
    // 0x721
    *v3 = 0;
    if (*(int32_t *)this != 0) {
        // 0x734
        // branch -> 0x74a
    }
    // 0x74a
    *(int32_t *)(this + (int32_t)&g24) = 0;
    g1 = 0;
    function_765();
}

// Address range: 0x765 - 0x767
int32_t function_765(void) {
    // 0x765
    return g1;
}

// From module:   /parallelcoin/src/leveldb.h
// Address range: 0x768 - 0x7ed
// Line range:    73 - 81
// Demangled:     CLevelDB::WriteBatch(CLevelDBBatch &, bool)
void _ZN8CLevelDB10WriteBatchER13CLevelDBBatchb(int32_t this, int32_t batch, bool fSync) {
    struct Status status; // bp-32
    struct Status v1; // bp+776
    // 0x768
    v1 = (struct Status){
        .e0 = NULL
    };
    v1.e0 = (char *)this;
    status = v1;
    int32_t v2 = *(int32_t *)&status;
    int32_t v3 = !fSync ? 64 : 65;
    int32_t v4 = *(int32_t *)(v2 + 68);
    int32_t v5 = 0; // bp-24
    int32_t v6 = _ZNK7leveldb6Status2okEv(&v5, (int32_t)&v5, v4, v2 + v3, batch);
    if ((char)(v6 ^ 1) == 0) {
        // bb
        function_82d();
        // branch -> 0x7e0
    }
}

// Address range: 0x81b - 0x82d
int32_t function_81b(void) {
    // 0x81b
    int32_t v1;
    int32_t v2 = v1 - 20;
    g1 = v2;
    return _Z11HandleErrorRKN7leveldb6StatusE(v2);
}

// Address range: 0x82d - 0x84d
int32_t function_82d(void) {
    // 0x82d
    _ZN7leveldb6StatusD1Ev((int32_t *)(g2 - 20));
    g1 = 1;
    if (*(int32_t *)(g2 - 12) == -0x1bba7700) {
        // bb
        g1 = function_88d();
        // branch -> 0x84b
    }
    // 0x84b
    return function_888();
}

// Address range: 0x85c - 0x85e
int32_t function_85c(void) {
    // 0x85c
    return function_862();
}

// Address range: 0x85e - 0x862
int32_t function_85e(void) {
    // 0x85e
    return 0;
}

// Address range: 0x862 - 0x87b
int32_t function_862(void) {
    // 0x862
    _ZN7leveldb6StatusD1Ev((int32_t *)(g2 - 20));
    g1 = g6;
    int32_t result = g6; // bp+878
    if (g3 == -1) {
        // bb
        result = function_880();
        // branch -> 0x878
    }
    // 0x878
    return result;
}

// Address range: 0x880 - 0x883
int32_t function_880(void) {
    // 0x880
    return g1;
}

// Address range: 0x888 - 0x889
int32_t function_888(void) {
    // 0x888
    return g1;
}

// Address range: 0x88d - 0x894
int32_t function_88d(void) {
    // 0x88d
    return g1;
}

// Address range: 0x894 - 0x8cf
// Line range:    0 - 81
void __static_initialization_and_destruction_0(int32_t __initialize_p, int32_t __priority) {
    // 0x894
    if (__initialize_p != 1) {
        // bb
        function_9bc(__priority, __initialize_p);
        // branch -> 0x8bb
    }
    // 0x8bb
    if (__priority != 0xffff) {
        // bb7
        int32_t * v1;
        function_9bc(-0x1bba7700, (int32_t)&v1);
        // branch -> 0x8c8
    }
}

// Address range: 0x8f5 - 0x8fb
int32_t function_8f5(void) {
    // 0x8f5
    return 0;
}

// Address range: 0x8ff - 0x905
int32_t function_8ff(void) {
    // 0x8ff
    return 0;
}

// Address range: 0x909 - 0x90f
int32_t function_909(void) {
    // 0x909
    return 0;
}

// Address range: 0x9bc - 0x9c8
int32_t function_9bc(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700;
    g1 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_9cd();
        // branch -> 0x9c8
    }
    // 0x9c8
    return result;
}

// Address range: 0x9cd - 0x9cf
int32_t function_9cd(void) {
    // 0x9cd
    return g1;
}

// Address range: 0x9cf - 0xa00
// Line range:    0 - 81
void _GLOBAL__sub_I__Z11HandleErrorRKN7leveldb6StatusE(void) {
    // 0x9cf
    __static_initialization_and_destruction_0(1, 0xffff);
    g1 = 0;
    function_a05();
}

// Address range: 0xa05 - 0xa07
int32_t function_a05(void) {
    // 0xa05
    return g1;
}

// Address range: 0xa08 - 0xa22
// Demangled:     std::exception::exception()
int32_t _ZNSt9exceptionC1Ev(int32_t result) {
    // 0xa08
    return result;
}

// Address range: 0xa39 - 0xa3b
int32_t function_a39(void) {
    // 0xa39
    return 0;
}

// Address range: 0xa3c - 0xa61
// Demangled:     std::bad_alloc::bad_alloc()
int32_t _ZNSt9bad_allocC1Ev(int32_t result) {
    // 0xa3c
    g1 = result;
    function_1444(result);
    return result;
}

// Address range: 0xa7a - 0xa9d
// Demangled:     boost::noncopyable_::noncopyable::~noncopyable()
int32_t _ZN5boost12noncopyable_11noncopyableD1Ev(int32_t a1) {
    // 0xa7a
    g1 = 0;
    return function_aa2(a1);
}

// Address range: 0xaa2 - 0xaa4
int32_t function_aa2(int32_t a1) {
    // 0xaa2
    return g1;
}

// Address range: 0xaa4 - 0xad5
// Demangled:     boost::error_info<boost::throw_function_, char const *>::error_info(char const *)
int32_t _ZN5boost10error_infoINS_15throw_function_EPKcEC1ES3_(int32_t * a1, int32_t a2) {
    // 0xaa4
    *a1 = a2;
    g1 = 0;
    return function_ada(a2, (int32_t)a1);
}

// Address range: 0xada - 0xadc
int32_t function_ada(int32_t a1, int32_t a2) {
    // 0xada
    return g1;
}

// Address range: 0xadc - 0xb0d
// Demangled:     boost::error_info<boost::throw_file_, char const *>::error_info(char const *)
int32_t _ZN5boost10error_infoINS_11throw_file_EPKcEC1ES3_(int32_t * a1, int32_t a2) {
    // 0xadc
    *a1 = a2;
    g1 = 0;
    return function_b12(a2, (int32_t)a1);
}

// Address range: 0xb12 - 0xb14
int32_t function_b12(int32_t a1, int32_t a2) {
    // 0xb12
    return g1;
}

// Address range: 0xb14 - 0xb45
// Demangled:     boost::error_info<boost::throw_line_, int>::error_info(int)
int32_t _ZN5boost10error_infoINS_11throw_line_EiEC1Ei(int32_t * a1, int32_t a2) {
    // 0xb14
    *a1 = a2;
    g1 = 0;
    return function_b4a(a2, (int32_t)a1);
}

// Address range: 0xb4a - 0xb4c
int32_t function_b4a(int32_t a1, int32_t a2) {
    // 0xb4a
    return g1;
}

// Address range: 0xb4c - 0xba4
// Demangled:     boost::exception::exception()
int32_t _ZN5boost9exceptionC1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g21;
    int32_t v2 = v1 + 4;
    g1 = v2;
    function_2a0a(v2);
    *(int32_t *)(v1 + 8) = 0;
    *(int32_t *)(v1 + (int32_t)&g24) = 0;
    *(int32_t *)(v1 + (int32_t)&g8) = -1;
    g1 = 0;
    return function_ba9();
}

// Address range: 0xba9 - 0xbab
int32_t function_ba9(void) {
    // 0xba9
    return g1;
}

// Address range: 0xbac - 0xbec
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g21;
    function_2a9e(result + 4);
    function_c08();
    return result;
}

// Address range: 0xbf1 - 0xbf3
int32_t function_bf1(void) {
    // 0xbf1
    return function_c08();
}

// Address range: 0xc08 - 0xc14
int32_t function_c08(void) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700;
    g1 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_c19();
        // branch -> 0xc14
    }
    // 0xc14
    return result;
}

// Address range: 0xc19 - 0xc1b
int32_t function_c19(void) {
    // 0xc19
    return g1;
}

// Address range: 0xdb8 - 0xde0
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD0Ev(int32_t result) {
    // 0xdb8
    function_1964(result);
    return result;
}

// Address range: 0xdf5 - 0xdf8
int32_t function_df5(void) {
    // 0xdf5
    return 0;
}

// Address range: 0xdf8 - 0xe2a
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g20;
    function_e2f(result);
    return result;
}

// Address range: 0xe2f - 0xe42
int32_t function_e2f(int32_t a1) {
    // 0xe2f
    return *(int32_t *)(g2 - 12) ^ -0x1bba7700;
}

// Address range: 0xe42 - 0xe6a
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t result) {
    // 0xe42
    g1 = result;
    function_1c3a(result);
    return result;
}

// Address range: 0xe6e - 0xe82
int32_t function_e6e(void) {
    int32_t * v1 = (int32_t *)0x3365f445;
    *v1 = *v1 - 1;
    return &g9;
}

// Address range: 0xe82 - 0xf4d
// Demangled:     boost::exception_detail::copy_boost_exception(boost::exception *, boost::exception const *)
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t a2) {
    // 0xe82
    int32_t v1; // bp-28
    int32_t v2 = &v1;
    __cxa_pure_virtual(v2);
    int32_t v3 = a2 + 4;
    g1 = v3;
    int32_t v4 = v3; // bp-60
    int32_t v5 = function_2daa(v3);
    int32_t v6;
    if (v5 != 0) {
        // 0xec2
        int32_t v7; // bp-24
        v6 = &v7;
        v4 = v6;
        unknown_2dda(v2, v6, v5);
        g1 = v6;
        function_2d74(v6);
        // branch -> 0xefb
    } else {
        int32_t v8;
        v5 = v8;
    }
    int32_t v9 = *(int32_t *)(a2 + (int32_t)&g24);
    *(int32_t *)(a1 + (int32_t)&g24) = v9;
    int32_t v10 = *(int32_t *)(a2 + (int32_t)&g8);
    *(int32_t *)(a1 + (int32_t)&g8) = v10;
    *(int32_t *)(a1 + 8) = *(int32_t *)(a2 + 8);
    *(int32_t *)(g7 + 4) = v2;
    *(int32_t *)g7 = a1 + 4;
    unknown_2dda(v6, v4, v5);
    g1 = v2;
    *(int32_t *)g7 = v2;
    function_2d74(v6);
    g1 = 0;
    g1 = function_f78();
    return function_f73();
}

// Address range: 0xf4d - 0xf5c
int32_t function_f4d(void) {
    // 0xf4d
    g3 = 0;
    int32_t v1 = g2 - 20;
    g1 = v1;
    function_2d74(v1);
    return function_f5e();
}

// Address range: 0xf5c - 0xf5e
int32_t function_f5c(void) {
    // 0xf5c
    return 0;
}

// Address range: 0xf5e - 0xf6e
int32_t function_f5e(void) {
    int32_t v1 = g2 - 24;
    g1 = v1;
    function_2d74(v1);
    return g3;
}

// Address range: 0xf73 - 0xf78
int32_t function_f73(void) {
    // 0xf73
    return g1;
}

// Address range: 0xf78 - 0xf7d
int32_t function_f78(void) {
    // 0xf78
    return g1;
}

// Address range: 0xf7d - 0xfc7
// Demangled:     boost::detail::atomic_exchange_and_add(int *, int)
int32_t _ZN5boost6detail23atomic_exchange_and_addEPii(int32_t * a1, int32_t a2) {
    int32_t result = *a1;
    *a1 = result + a2;
    return result;
}

// Address range: 0xfc7 - 0xffa
// Demangled:     boost::detail::atomic_increment(int *)
int32_t _ZN5boost6detail16atomic_incrementEPi(int32_t * a1) {
    // 0xfc7
    *a1 = *a1 + 1;
    return 0;
}

// Address range: 0xffa - 0x1041
// Demangled:     boost::detail::sp_counted_base::sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseC1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g19;
    *(int32_t *)(v1 + 4) = 1;
    *(int32_t *)(v1 + 8) = 1;
    return 0;
}

// Address range: 0x1042 - 0x1074
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g19;
    function_1079(result);
    return result;
}

// Address range: 0x1079 - 0x1085
int32_t function_1079(int32_t a1) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x107c
    g1 = v1;
    int32_t result = v1; // 0x1083
    if (v1 == 0) {
        // bb
        result = function_108a();
        // branch -> 0x1085
    }
    // 0x1085
    return result;
}

// Address range: 0x108a - 0x108c
int32_t function_108a(void) {
    // 0x108a
    return g1;
}

// Address range: 0x108c - 0x10b4
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t result) {
    // 0x108c
    g1 = result;
    function_20ce(result);
    return result;
}

// Address range: 0x10c9 - 0x10cc
int32_t function_10c9(void) {
    // 0x10c9
    return 0;
}

// Address range: 0x10cc - 0x110e
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_base::destroy()
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(int32_t * a1) {
    // 0x10cc
    if (a1 != NULL) {
        // 0x10e9
        // branch -> 0x10fb
    }
    // 0x10fb
    return 0;
}

// Address range: 0x110e - 0x1146
// Demangled:     boost::detail::sp_counted_base::add_ref_copy()
int32_t _ZN5boost6detail15sp_counted_base12add_ref_copyEv(int32_t a1) {
    int32_t v1 = a1 + 4; // 0x1128
    g1 = v1;
    function_20d5(v1);
    return 0;
}

// Address range: 0x1146 - 0x11ad
// Demangled:     boost::detail::sp_counted_base::release()
int32_t _ZN5boost6detail15sp_counted_base7releaseEv(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    if (function_20c3(v1 + 4, -1) == 1) {
        // 0x117d
        g5 = *(int32_t *)(*a1 + 8);
        g1 = v1;
        function_22f4(v1);
        // branch -> 0x119a
    }
    // 0x119a
    return 0;
}

// Address range: 0x11ae - 0x1203
// Demangled:     boost::detail::sp_counted_base::weak_release()
int32_t _ZN5boost6detail15sp_counted_base12weak_releaseEv(int32_t * a1) {
    // 0x11ae
    if (function_212b((int32_t)a1 + 8, -1) == 1) {
        // 0x11e5
        // branch -> 0x11f7
    }
    // 0x11f7
    g1 = 0;
    return function_1208();
}

// Address range: 0x1208 - 0x120a
int32_t function_1208(void) {
    // 0x1208
    return g1;
}

// Address range: 0x120a - 0x124a
// Demangled:     boost::detail::shared_count::~shared_count()
int32_t _ZN5boost6detail12shared_countD1Ev(int32_t * a1) {
    int32_t v1 = 0; // bp-4
    g2 = &v1;
    if (*a1 != 0) {
        // 0x122a
        function_2350(*a1);
        // branch -> 0x1237
    }
    // 0x1237
    return 0;
}

// Address range: 0x124a - 0x129a
// Demangled:     boost::detail::shared_count::shared_count(boost::detail::shared_count const &)
int32_t _ZN5boost6detail12shared_countC1ERKS1_(int32_t * a1, int32_t a2) {
    int32_t v1 = *(int32_t *)a2; // 0x126a
    *a1 = v1;
    if (v1 != 0) {
        // 0x127a
        // branch -> 0x1287
    }
    // 0x1287
    return 0;
}

// Address range: 0x129a - 0x12b7
// Demangled:     boost::detail::sp_enable_shared_from_this(ellipsis)
int32_t _ZN5boost6detail26sp_enable_shared_from_thisEz(void) {
    // 0x129a
    g1 = 0;
    return function_12bc(-0x1bba7700);
}

// Address range: 0x12bc - 0x12be
int32_t function_12bc(int32_t a1) {
    // 0x12bc
    return g1;
}

// Address range: 0x1444 - 0x1445
int32_t function_1444(int32_t a1) {
    // 0x1444
    return g1;
}

// Address range: 0x14fa - 0x152c
// Demangled:     std::exception::exception(std::exception const &)
int32_t _ZNSt9exceptionC1ERKS_(int32_t * a1, int32_t a2) {
    // 0x14fa
    *a1 = 8;
    g1 = 0;
    return function_1531(a2, (int32_t)a1);
}

// Address range: 0x1531 - 0x1533
int32_t function_1531(int32_t a1, int32_t a2) {
    // 0x1531
    return g1;
}

// Address range: 0x1534 - 0x155c
// Demangled:     leveldb::Status::~Status()
int32_t _ZN7leveldb6StatusD1Ev(int32_t * a1) {
    // 0x1534
    if (*a1 == 0) {
        // bb
        function_1561((int32_t)a1);
        // branch -> 0x1554
    }
    // 0x1554
    return *a1;
}

// Address range: 0x1561 - 0x1574
int32_t function_1561(int32_t a1) {
    // 0x1561
    return *(int32_t *)(g2 - 12) ^ -0x1bba7700;
}

// Address range: 0x1574 - 0x15a8
// Demangled:     leveldb::Status::ok() const
int32_t _ZNK7leveldb6Status2okEv(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = *a1; // 0x158e
    return (int32_t)(v1 == 0) | v1 & -256;
}

// Address range: 0x15a8 - 0x15e3
// Demangled:     leveldb::Status::IsNotFound() const
int32_t _ZNK7leveldb6Status10IsNotFoundEv(int32_t a1) {
    // 0x15a8
    g1 = a1;
    int32_t v1 = function_2c04(a1); // 0x15c5
    return (int32_t)(v1 == 1) | v1 & -256;
}

// Address range: 0x15e4 - 0x1618
// Demangled:     leveldb::Status::IsCorruption() const
int32_t _ZNK7leveldb6Status12IsCorruptionEv(int32_t a1) {
    // 0x15e4
    g1 = a1;
    int32_t v1 = function_2c40(a1); // 0x1601
    g1 = (int32_t)(v1 == 2) | v1 & -256;
    return function_161d();
}

// Address range: 0x161d - 0x161f
int32_t function_161d(void) {
    // 0x161d
    return g1;
}

// Address range: 0x1620 - 0x1654
// Demangled:     leveldb::Status::IsIOError() const
int32_t _ZNK7leveldb6Status9IsIOErrorEv(int32_t a1) {
    int32_t v1 = unknown_2c7c(a1); // 0x163d
    g1 = (int32_t)(v1 == 5) | v1 & -256;
    return function_1659();
}

// Address range: 0x1659 - 0x165b
int32_t function_1659(void) {
    // 0x1659
    return g1;
}

// Address range: 0x165c - 0x169d
// Demangled:     leveldb::Status::code() const
int32_t _ZNK7leveldb6Status4codeEv(int32_t * a1) {
    // 0x165c
    int32_t v1;
    if (*a1 != 0) {
        // 0x167c
        v1 = (int32_t)*(char *)(*a1 + 4);
        // branch -> 0x1691
    } else {
        v1 = 0;
    }
    // 0x1691
    g1 = v1;
    return function_16a2();
}

// Address range: 0x16a2 - 0x16a4
int32_t function_16a2(void) {
    // 0x16a2
    return g1;
}

// Address range: 0x16a4 - 0x16de
// Demangled:     leveldb::ReadOptions::ReadOptions()
int32_t _ZN7leveldb11ReadOptionsC1Ev(char * a1) {
    int32_t v1 = (int32_t)a1; // 0x16bb
    *a1 = 0;
    *(char *)(v1 + 1) = 1;
    *(int32_t *)(v1 + 4) = 0;
    g1 = 0;
    return function_16e3(v1);
}

// Address range: 0x16e3 - 0x16e5
int32_t function_16e3(int32_t a1) {
    // 0x16e3
    return g1;
}

// Address range: 0x16e6 - 0x1716
// Demangled:     leveldb::WriteOptions::WriteOptions()
int32_t _ZN7leveldb12WriteOptionsC1Ev(char * a1) {
    // 0x16e6
    *a1 = 0;
    return 0;
}

// Address range: 0x1716 - 0x1764
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g18;
    g1 = v1;
    function_2190(v1);
    g1 = 0;
    return function_1769();
}

// Address range: 0x1769 - 0x176b
int32_t function_1769(void) {
    // 0x1769
    return g1;
}

// Address range: 0x176c - 0x1794
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t result) {
    // 0x176c
    unknown_2e82(result);
    return result;
}

// Address range: 0x17a9 - 0x17ac
int32_t function_17a9(void) {
    // 0x17a9
    return 0;
}

// Address range: 0x17ac - 0x17de
// Demangled:     boost::system::error_category::operator==(boost::system::error_category const &) const
int32_t _ZNK5boost6system14error_categoryeqERKS1_(int32_t a1, int32_t a2) {
    // 0x17ac
    g1 = (int32_t)(bool)(a1 == a2) | a1 & -256;
    return function_17e3(a2, a1);
}

// Address range: 0x17e3 - 0x17e5
int32_t function_17e3(int32_t a1, int32_t a2) {
    // 0x17e3
    return g1;
}

// Address range: 0x17e6 - 0x1826
// Demangled:     boost::system::error_condition::error_condition(int, boost::system::error_category const &)
int32_t _ZN5boost6system15error_conditionC1EiRKNS0_14error_categoryE(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t v1 = (int32_t)a1;
    *a1 = a2;
    *(int32_t *)(v1 + 4) = a3;
    g1 = 0;
    return function_182b(a3, a2, v1);
}

// Address range: 0x182b - 0x182d
int32_t function_182b(int32_t a1, int32_t a2, int32_t a3) {
    // 0x182b
    return g1;
}

// Address range: 0x182d - 0x1880
// Demangled:     boost::system::operator==(boost::system::error_condition const &, boost::system::error_condition const &)
int32_t _ZN5boost6systemeqERKNS0_15error_conditionES3_(int32_t * a1, int32_t a2) {
    // 0x182d
    if (*(int32_t *)((int32_t)a1 + 4) != *(int32_t *)(a2 + 4)) {
        // 0x186f
        // branch -> 0x1874
        // 0x1874
        g1 = 0;
        return function_1885();
    }
    // 0x185a
    if (*a1 == *(int32_t *)a2) {
        // 0x1874
        g1 = 1;
        return function_1885();
    }
    // 0x186f
    // branch -> 0x1874
    // 0x1874
    g1 = 0;
    return function_1885();
}

// Address range: 0x1885 - 0x1887
int32_t function_1885(void) {
    // 0x1885
    return g1;
}

// Address range: 0x1888 - 0x18b0
// Demangled:     boost::system::error_code::value() const
int32_t _ZNK5boost6system10error_code5valueEv(int32_t * a1) {
    // 0x1888
    g1 = *a1;
    return function_18b5((int32_t)a1);
}

// Address range: 0x18b5 - 0x18b7
int32_t function_18b5(int32_t a1) {
    // 0x18b5
    return g1;
}

// Address range: 0x18b8 - 0x18e1
// Demangled:     boost::system::error_code::category() const
int32_t _ZNK5boost6system10error_code8categoryEv(int32_t a1) {
    // 0x18b8
    g1 = *(int32_t *)(a1 + 4);
    return function_18e6(a1);
}

// Address range: 0x18e6 - 0x18e8
int32_t function_18e6(int32_t a1) {
    // 0x18e6
    return g1;
}

// Address range: 0x18e8 - 0x1946
// Demangled:     boost::system::error_code::message() const
int32_t _ZNK5boost6system10error_code7messageEv(int32_t a1, int32_t a2) {
    int32_t v1 = unknown_3170(a2); // 0x1919
    g1 = a1;
    return function_194b(a1, *(int32_t *)(a2 + 4), v1);
}

// Address range: 0x194b - 0x1952
int32_t function_194b(int32_t a1, int32_t a2, int32_t a3) {
    // 0x194b
    return g1;
}

// Address range: 0x1952 - 0x1964
// Demangled:     boost::system::error_category::default_error_condition(int) const
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t a1, int32_t result) {
    // 0x1952
    return result;
}

// Address range: 0x1964 - 0x199d
int32_t function_1964(int32_t a1) {
    // 0x1964
    *(int32_t *)(g2 - 36) = *(int32_t *)(g2 + (int32_t)&g8);
    *(int32_t *)(g2 - 12) = -0x1bba7700;
    int32_t v1 = *(int32_t *)(g2 - 28); // 0x1983
    g1 = v1;
    function_3138(v1, *(int32_t *)(g2 - 36), *(int32_t *)(g2 - 32));
    int32_t result = *(int32_t *)(g2 - 28); // 0x198e
    g1 = result;
    if (*(int32_t *)(g2 - 12) == -0x1bba7700) {
        // bb
        result = function_19a2();
        // branch -> 0x199d
    }
    // 0x199d
    return result;
}

// Address range: 0x19a2 - 0x19a6
int32_t function_19a2(void) {
    // 0x19a2
    return g1;
}

// Address range: 0x19a6 - 0x1a0a
// Demangled:     boost::system::error_category::equivalent(int, boost::system::error_condition const &) const
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1, int32_t a2, int32_t a3) {
    // 0x19a6
    int32_t v1; // bp-24
    g1 = unknown_31d3((int32_t)&v1, a3, (int32_t)a1, a2);
    return function_1a0f();
}

// Address range: 0x1a0f - 0x1a11
int32_t function_1a0f(void) {
    // 0x1a0f
    return g1;
}

// Address range: 0x1a12 - 0x1a82
// Demangled:     boost::system::error_category::equivalent(boost::system::error_code const &, int) const
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = unknown_32ca(a2); // 0x1a3b
    if ((char)unknown_31be(a1, v1) == 0) {
        // 0x1a6a
        // branch -> 0x1a6f
        // 0x1a6f
        return 0;
    }
    // 0x1a53
    if (unknown_329a(a2) == a3) {
        // 0x1a6f
        return 1;
    }
    // 0x1a6a
    // branch -> 0x1a6f
    // 0x1a6f
    return 0;
}

// Address range: 0x1a82 - 0x1aad
// From class:    N5boost6system12system_errorE
// Type:          constructor
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1) {
    // 0x1a82
    *a1 = (int32_t)&g17;
    return (int32_t)a1 + (int32_t)&g8;
}

// Address range: 0x1ad4 - 0x1ad6
int32_t function_1ad4(void) {
    // 0x1ad4
    return function_1afe();
}

// Address range: 0x1afe - 0x1b0a
int32_t function_1afe(void) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x1b01
    g1 = v1;
    int32_t result = v1; // 0x1b08
    if (v1 == 0) {
        // bb
        result = function_1b0f();
        // branch -> 0x1b0a
    }
    // 0x1b0a
    return result;
}

// Address range: 0x1b0f - 0x1b16
int32_t function_1b0f(void) {
    // 0x1b0f
    return g1;
}

// Address range: 0x1b16 - 0x1b3e
// From class:    N5boost6system12system_errorE
// Type:          virtual member function
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD0Ev(int32_t result) {
    // 0x1b16
    unknown_3598(result);
    return result;
}

// Address range: 0x1b53 - 0x1b56
int32_t function_1b53(void) {
    // 0x1b53
    return 0;
}

// Address range: 0x1b56 - 0x1b77
// From class:    N5boost6system12system_errorE
// Type:          virtual member function
// Demangled:     boost::system::system_error::what() const
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1) {
    // 0x1b56
    return a1 + (int32_t)&g8;
}

// Address range: 0x1b90 - 0x1b96
int32_t function_1b90(void) {
    // 0x1b90
    return 0;
}

// Address range: 0x1c11 - 0x1c24
int32_t function_1c11(void) {
    int32_t * v1 = (int32_t *)-0x7427763d; // 0x1c11
    *v1 = *v1 - 1;
    // 0x1c22
    return function_1c66();
}

// Address range: 0x1c25 - 0x1c26
int32_t function_1c25(void) {
    // 0x1c25
    return 0;
}

// Address range: 0x1c31 - 0x1c38
int32_t function_1c31(void) {
    // 0x1c31
    return 0;
}

// Address range: 0x1c3a - 0x1c3b
int32_t function_1c3a(int32_t a1) {
    // 0x1c3a
    return g1;
}

// Address range: 0x1c49 - 0x1c4a
int32_t function_1c49(void) {
    // 0x1c49
    return 0;
}

// Address range: 0x1c4f - 0x1c51
int32_t function_1c4f(void) {
    // 0x1c4f
    return 0;
}

// Address range: 0x1c66 - 0x1c67
int32_t function_1c66(void) {
    // 0x1c66
    return g1;
}

// Address range: 0x1c6b - 0x1c70
int32_t function_1c6b(void) {
    // 0x1c6b
    return g1;
}

// Address range: 0x1c70 - 0x1c96
// Demangled:     boost::filesystem3::path::string() const
int32_t _ZNK5boost11filesystem34path6stringEv(int32_t a1) {
    // 0x1c70
    g1 = a1;
    return function_1c9b(a1);
}

// Address range: 0x1c9b - 0x1c9d
int32_t function_1c9b(int32_t a1) {
    // 0x1c9b
    return g1;
}

// Address range: 0x1c9e - 0x1cc8
// Demangled:     leveldb_error::leveldb_error(std::string const &)
int32_t _ZN13leveldb_errorC1ERKSs(int32_t result, int32_t a2) {
    // 0x1c9e
    return result;
}

// Address range: 0x1ce6 - 0x1ce9
int32_t function_1ce6(void) {
    // 0x1ce6
    return 0;
}

// Address range: 0x1cea - 0x1d58
// Demangled:     boost::exception::exception(boost::exception const &)
int32_t _ZN5boost9exceptionC1ERKS0_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g21;
    unknown_3e8c(v1 + 4, a2 + 4);
    *(int32_t *)(v1 + 8) = *(int32_t *)(a2 + 8);
    int32_t v2 = *(int32_t *)(a2 + (int32_t)&g24); // 0x1d37
    *(int32_t *)(v1 + (int32_t)&g24) = v2;
    int32_t v3 = *(int32_t *)(a2 + (int32_t)&g8); // 0x1d43
    *(int32_t *)(v1 + (int32_t)&g8) = v3;
    g1 = 0;
    return function_1d5d();
}

// Address range: 0x1d5d - 0x1d5f
int32_t function_1d5d(void) {
    // 0x1d5d
    return g1;
}

// Address range: 0x1d60 - 0x1d91
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::~shared_ptr()
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1) {
    // 0x1d60
    unknown_2f6a(a1 + 4);
    g1 = 0;
    return function_1d96();
}

// Address range: 0x1d96 - 0x1d98
int32_t function_1d96(void) {
    // 0x1d96
    return g1;
}

// Address range: 0x1d98 - 0x1de3
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::shared_ptr(boost::shared_ptr<boost::exception_detail::clone_base const> const &)
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1ERKS4_(int32_t * a1, int32_t a2) {
    // 0x1d98
    *a1 = *(int32_t *)a2;
    int32_t v1 = (int32_t)a1 + 4; // 0x1dc8
    g1 = v1;
    function_2fe2(v1, a2 + 4);
    g1 = 0;
    return function_1de8();
}

// Address range: 0x1de8 - 0x1dea
int32_t function_1de8(void) {
    // 0x1de8
    return g1;
}

// Address range: 0x1dea - 0x1e0f
// Demangled:     boost::filesystem3::create_directory(boost::filesystem3::path const &)
int32_t _ZN5boost11filesystem316create_directoryERKNS0_4pathE(int32_t result) {
    // 0x1dea
    return result;
}

// Address range: 0x1e24 - 0x1e27
int32_t function_1e24(void) {
    // 0x1e24
    return 0;
}

// Address range: 0x1e28 - 0x1e4e
// From class:    leveldb_error
// Type:          constructor
// Demangled:     leveldb_error::~leveldb_error()
int32_t _ZN13leveldb_errorD1Ev(int32_t * a1) {
    // 0x1e28
    *a1 = (int32_t)&g16;
    return (int32_t)a1;
}

// Address range: 0x1e7a - 0x1e7d
int32_t function_1e7a(void) {
    // 0x1e7a
    return 0;
}

// Address range: 0x1e7e - 0x1ea6
// From class:    leveldb_error
// Type:          virtual member function
// Demangled:     leveldb_error::~leveldb_error()
int32_t _ZN13leveldb_errorD0Ev(int32_t result) {
    // 0x1e7e
    unknown_3ca6(result);
    return result;
}

// Address range: 0x1ebb - 0x1ebe
int32_t function_1ebb(void) {
    // 0x1ebb
    return 0;
}

// Address range: 0x1ebe - 0x1eea
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::refcount_ptr()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1Ev(int32_t * a1) {
    // 0x1ebe
    *a1 = 0;
    g1 = 0;
    return function_1eef((int32_t)a1);
}

// Address range: 0x1eef - 0x1ef1
int32_t function_1eef(int32_t a1) {
    // 0x1eef
    return g1;
}

// Address range: 0x1ef2 - 0x1f20
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::~refcount_ptr()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t a1) {
    // 0x1ef2
    unknown_44d2(a1);
    g1 = 0;
    return function_1f25();
}

// Address range: 0x1f25 - 0x1f27
int32_t function_1f25(void) {
    // 0x1f25
    return g1;
}

// Address range: 0x1f28 - 0x1f50
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::get() const
int32_t _ZNK5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE3getEv(int32_t * a1) {
    // 0x1f28
    g1 = *a1;
    return function_1f55((int32_t)a1);
}

// Address range: 0x1f55 - 0x1f57
int32_t function_1f55(int32_t a1) {
    // 0x1f55
    return g1;
}

// Address range: 0x1f58 - 0x1f98
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::operator=(boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container> const &)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEaSERKS3_(int32_t a1, int32_t * a2) {
    // 0x1f58
    unknown_40ac(a1, *a2);
    g1 = a1;
    return function_1f9d();
}

// Address range: 0x1f9d - 0x1f9f
int32_t function_1f9d(void) {
    // 0x1f9d
    return g1;
}

// Address range: 0x1fa0 - 0x1fd2
// Demangled:     boost::exception_detail::clone_base::clone_base(boost::exception_detail::clone_base const &)
int32_t _ZN5boost16exception_detail10clone_baseC1ERKS1_(int32_t * a1, int32_t a2) {
    // 0x1fa0
    *a1 = (int32_t)&g20;
    g1 = 0;
    return function_1fd7(a2, (int32_t)a1);
}

// Address range: 0x1fd7 - 0x1fd9
int32_t function_1fd7(int32_t a1, int32_t a2) {
    // 0x1fd7
    return g1;
}

// Address range: 0x1fda - 0x1ffd
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi1EEC1Ev(int32_t a1) {
    // 0x1fda
    g1 = 0;
    return function_2002(a1);
}

// Address range: 0x2002 - 0x2004
int32_t function_2002(int32_t a1) {
    // 0x2002
    return g1;
}

// Address range: 0x2004 - 0x2027
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi2EEC1Ev(int32_t a1) {
    // 0x2004
    g1 = 0;
    return function_202c(a1);
}

// Address range: 0x202c - 0x202e
int32_t function_202c(int32_t a1) {
    // 0x202c
    return g1;
}

// Address range: 0x202e - 0x2051
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi3EEC1Ev(int32_t a1) {
    // 0x202e
    g1 = 0;
    return function_2056(a1);
}

// Address range: 0x2056 - 0x2058
int32_t function_2056(int32_t a1) {
    // 0x2056
    return g1;
}

// Address range: 0x2058 - 0x207b
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi4EEC1Ev(int32_t a1) {
    // 0x2058
    g1 = 0;
    return function_2080(a1);
}

// Address range: 0x2080 - 0x2082
int32_t function_2080(int32_t a1) {
    // 0x2080
    return g1;
}

// Address range: 0x2082 - 0x20a5
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi5EEC1Ev(int32_t a1) {
    // 0x2082
    g1 = 0;
    return function_20aa(a1);
}

// Address range: 0x20aa - 0x20ac
int32_t function_20aa(int32_t a1) {
    // 0x20aa
    return g1;
}

// Address range: 0x20ac - 0x20c3
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi6EEC1Ev(int32_t a1) {
    // 0x20ac
    return 0;
}

// Address range: 0x20c3 - 0x20cd
int32_t function_20c3(int32_t a1, int32_t a2) {
    // 0x20c3
    return *(int32_t *)(g2 - 12) ^ -0x1bba7700;
}

// Address range: 0x20ce - 0x20cf
int32_t function_20ce(int32_t a1) {
    // 0x20ce
    return g1;
}

// Address range: 0x20d5 - 0x20d6
int32_t function_20d5(int32_t a1) {
    // 0x20d5
    return g1;
}

// Address range: 0x20d6 - 0x20f9
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi7EEC1Ev(int32_t a1) {
    // 0x20d6
    g1 = 0;
    return function_20fe(a1);
}

// Address range: 0x20fe - 0x2100
int32_t function_20fe(int32_t a1) {
    // 0x20fe
    return g1;
}

// Address range: 0x2100 - 0x2123
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi8EEC1Ev(int32_t a1) {
    // 0x2100
    g1 = 0;
    return function_2128(a1);
}

// Address range: 0x2128 - 0x212a
int32_t function_2128(int32_t a1) {
    // 0x2128
    return g1;
}

// Address range: 0x212a - 0x212b
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi9EEC1Ev(void) {
    // 0x212a
    return 0;
}

// Address range: 0x212b - 0x214d
int32_t function_212b(int32_t a1, int32_t a2) {
    // 0x212b
    int32_t v1;
    g2 = &v1;
    g1 = 0;
    return function_2152(a1);
}

// Address range: 0x2152 - 0x2154
int32_t function_2152(int32_t a1) {
    // 0x2152
    return g1;
}

// Address range: 0x2154 - 0x218f
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::adopt(boost::exception_detail::error_info_container *)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE5adoptEPS2_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    unknown_4734(v1);
    *a1 = a2;
    return unknown_479a(v1);
}

// Address range: 0x2190 - 0x219b
int32_t function_2190(int32_t a1) {
    // 0x2190
    g2++;
    int32_t v1 = g1 ^ -0x1bba7700; // 0x2192
    g1 = v1;
    int32_t result = v1; // 0x2199
    if (v1 == 0) {
        // bb
        result = function_21a0();
        // branch -> 0x219b
    }
    // 0x219b
    return result;
}

// Address range: 0x21a0 - 0x21a2
int32_t function_21a0(void) {
    // 0x21a0
    return g1;
}

// Address range: 0x21a2 - 0x21e0
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::refcount_ptr(boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container> const &)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1ERKS3_(int32_t * a1, int32_t a2) {
    // 0x21a2
    *a1 = *(int32_t *)a2;
    unknown_47e8((int32_t)a1);
    g1 = 0;
    return function_21e5();
}

// Address range: 0x21e5 - 0x21e7
int32_t function_21e5(void) {
    // 0x21e5
    return g1;
}

// Address range: 0x21e8 - 0x2237
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::bad_alloc_::bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_C1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    unknown_2d34(v1);
    int32_t v2 = v1 + (int32_t)&g9; // 0x220d
    unknown_2c24(v2);
    *a1 = (int32_t)&g14;
    *(int32_t *)v2 = (int32_t)&g15;
    g1 = 0;
    return function_223c();
}

// Address range: 0x223c - 0x223e
int32_t function_223c(void) {
    // 0x223c
    return g1;
}

// Address range: 0x223e - 0x2248
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1) {
    // 0x223e
    return function_4486(a1 - (int32_t)&g9);
}

// Address range: 0x2248 - 0x227b
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1) {
    // 0x2248
    *a1 = (int32_t)&g14;
    int32_t result = (int32_t)a1 + (int32_t)&g9; // 0x226b
    *(int32_t *)result = (int32_t)&g15;
    return result;
}

// Address range: 0x22b2 - 0x22b5
int32_t function_22b2(void) {
    // 0x22b2
    return 0;
}

// Address range: 0x22b6 - 0x22bd
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1) {
    // 0x22b6
    return _ZN5boost16exception_detail10bad_alloc_D0Ev(a1 - (int32_t)&g9);
}

// Address range: 0x22be - 0x22ee
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          virtual member function
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t a1) {
    // 0x22be
    unknown_44fe(a1);
    return -0x1bba7700;
}

// Address range: 0x22f4 - 0x22f9
int32_t function_22f4(int32_t a1) {
    char * v1 = (char *)(g2 - 24 + g1); // 0x22f4
    *v1 = (char)(g5 / 256) + *v1;
    return g1;
}

// Address range: 0x22fb - 0x22fe
int32_t function_22fb(void) {
    // 0x22fb
    return 0;
}

// Address range: 0x22fe - 0x2349
// Demangled:     std::bad_alloc::bad_alloc(std::bad_alloc const &)
int32_t _ZNSt9bad_allocC1ERKS_(int32_t * a1, int32_t a2) {
    // 0x22fe
    unknown_37f8((int32_t)a1, a2);
    *a1 = 8;
    return 0;
}

// Address range: 0x234a - 0x2350
// Demangled:     boost::exception_detail::bad_alloc_::bad_alloc_(boost::exception_detail::bad_alloc_ const &)
int32_t _ZN5boost16exception_detail10bad_alloc_C1ERKS1_(void) {
    // 0x234a
    return 0;
}

// Address range: 0x2350 - 0x23b7
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
int32_t function_2350(int32_t a1) {
    // 0x2350
    *(int32_t *)(g2 - 28) = *(int32_t *)(g2 + 8);
    *(int32_t *)(g2 - 32) = *(int32_t *)(g2 + (int32_t)&g24);
    *(int32_t *)(g2 - 12) = -0x1bba7700;
    unknown_4034(*(int32_t *)(g2 - 28), *(int32_t *)(g2 - 32));
    int32_t v1 = *(int32_t *)(g2 - 32); // 0x2379
    int32_t v2 = *(int32_t *)(g2 - 28); // 0x237f
    unknown_4648(v2 + (int32_t)&g9, v1 + (int32_t)&g9);
    *(int32_t *)*(int32_t *)(g2 - 28) = (int32_t)&g14;
    int32_t v3 = *(int32_t *)(g2 - 28); // 0x239a
    *(int32_t *)(v3 + (int32_t)&g9) = (int32_t)&g15;
    return *(int32_t *)(g2 - 12) ^ -0x1bba7700;
}

// Address range: 0x23b8 - 0x2428
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &)
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS3_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    unknown_4702(v1, a2);
    int32_t v2 = v1 + 24; // 0x23f0
    unknown_4358(v2, a2 + 24);
    *a1 = (int32_t)&g11;
    *(int32_t *)(v1 + (int32_t)&g9) = (int32_t)&g12;
    *(int32_t *)v2 = (int32_t)&g13;
    g1 = 0;
    return function_242d();
}

// Address range: 0x242d - 0x242f
int32_t function_242d(void) {
    // 0x242d
    return g1;
}

// Address range: 0x2430 - 0x24e3
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t a1) {
    // 0x2430
    int32_t v1; // bp-68
    int32_t v2 = &v1; // 0x244a
    unknown_4618(v2);
    int32_t v3; // bp-96
    int32_t v4 = &v3; // 0x245c
    unknown_4af4(v4, v2);
    int32_t v5; // bp-44
    int32_t v6 = &v5; // 0x246f
    g1 = v6;
    function_2f44(v6, 81);
    int32_t v7; // bp-40
    int32_t v8 = &v7; // 0x2482
    unknown_2f0c(v8, (int32_t)"/usr/include/boost/exception/detail/exception_ptr.hpp");
    int32_t v9; // bp-36
    int32_t v10 = &v9; // 0x2495
    _ZTISt13runtime_error(v10, (int32_t)"boost::exception_ptr boost::exception_detail::get_bad_alloc() [with int Dummy = 42, boost::exception_ptr = boost::shared_ptr<const boost::exception_detail::clone_base>]");
    int32_t v11 = unknown_4c7a(v4, v10); // 0x24ad
    unknown_4cfe(unknown_4cbc(v11, v8), v6);
    return (int32_t)*(char *)0x2430;
}

// Address range: 0x2503 - 0x2504
int32_t function_2503(void) {
    // 0x2503
    return 0;
}

// Address range: 0x258f - 0x2596
int32_t function_258f(void) {
    int32_t * v1 = (int32_t *)-0x76fd1405; // 0x258f
    *v1 = *v1 - 1;
    return 0;
}

// Address range: 0x25a8 - 0x25aa
int32_t function_25a8(void) {
    // 0x25a8
    return function_25ac();
}

// Address range: 0x25aa - 0x25ac
int32_t function_25aa(void) {
    // 0x25aa
    return 0;
}

// Address range: 0x25ac - 0x25b9
int32_t function_25ac(void) {
    // 0x25ac
    unknown_4bb4(g2 - 92);
    return function_25bb();
}

// Address range: 0x25b9 - 0x25bb
int32_t function_25b9(void) {
    // 0x25b9
    return 0;
}

// Address range: 0x25bb - 0x25cb
int32_t function_25bb(void) {
    // 0x25bb
    unknown_4678(g2 - 64);
    return g3;
}

// Address range: 0x25d0 - 0x25d5
int32_t function_25d0(void) {
    // 0x25d0
    return 0;
}

// Address range: 0x25d5 - 0x25df
int32_t function_25d5(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x25d5
    return 0;
}

// Address range: 0x25e0 - 0x2646
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::release()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7releaseEv(int32_t * a1) {
    // 0x25e0
    if (*a1 == 0 || (char)*a1 == 0) {
        // 0x2626
        // branch -> 0x2633
        // 0x2633
        return 0;
    }
    // 0x262a
    *a1 = 0;
    // branch -> 0x2633
    // 0x2633
    return 0;
}

// Address range: 0x2646 - 0x2688
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::add_ref()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7add_refEv(int32_t * a1) {
    // 0x2646
    if (*a1 != 0) {
        // 0x2666
        // branch -> 0x267c
    }
    // 0x267c
    g1 = 0;
    return function_268d();
}

// Address range: 0x268d - 0x268f
int32_t function_268d(void) {
    // 0x268d
    return g1;
}

// Address range: 0x2690 - 0x26bc
// Demangled:     boost::exception_detail::clone_base::clone_base()
int32_t _ZN5boost16exception_detail10clone_baseC1Ev(int32_t * a1) {
    // 0x2690
    *a1 = (int32_t)&g20;
    g1 = 0;
    return function_26c1((int32_t)a1);
}

// Address range: 0x26c1 - 0x26c3
int32_t function_26c1(int32_t a1) {
    // 0x26c1
    return g1;
}

// Address range: 0x26c4 - 0x2733
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone_impl(boost::exception_detail::bad_alloc_ const &)
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS2_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    unknown_4a0e(v1, a2);
    int32_t v2 = v1 + 24; // 0x26f7
    unknown_4d54(v2);
    *a1 = (int32_t)&g11;
    *(int32_t *)(v1 + (int32_t)&g9) = (int32_t)&g12;
    *(int32_t *)v2 = (int32_t)&g13;
    unknown_3546(v1, a2);
    return function_2758();
}

// Address range: 0x2734 - 0x2735
int32_t function_2734(void) {
    // 0x2734
    return 0;
}

// Address range: 0x2758 - 0x2764
int32_t function_2758(void) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x275b
    g1 = v1;
    int32_t result = v1; // 0x2762
    if (v1 == 0) {
        // bb
        result = function_2769();
        // branch -> 0x2764
    }
    // 0x2764
    return result;
}

// Address range: 0x2769 - 0x276f
int32_t function_2769(void) {
    // 0x2769
    return g1;
}

// Address range: 0x276f - 0x2779
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1) {
    // 0x276f
    return function_4ef3(a1 - 24);
}

// Address range: 0x2779 - 0x2783
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1) {
    // 0x2779
    return function_4ef3(a1 - (int32_t)&g9);
}

// Address range: 0x2784 - 0x27e3
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g11;
    *(int32_t *)(result + (int32_t)&g9) = (int32_t)&g12;
    int32_t v1 = result + 24; // 0x27b1
    *(int32_t *)v1 = (int32_t)&g13;
    unknown_357c(v1);
    unknown_49cc(result);
    function_27e8();
    return result;
}

// Address range: 0x27e8 - 0x27f4
int32_t function_27e8(void) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x27eb
    g1 = v1;
    int32_t result = v1; // 0x27f2
    if (v1 == 0) {
        // bb
        result = function_27f9();
        // branch -> 0x27f4
    }
    // 0x27f4
    return result;
}

// Address range: 0x27f9 - 0x27fb
int32_t function_27f9(void) {
    // 0x27f9
    return g1;
}

// Address range: 0x27fc - 0x2803
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    // 0x27fc
    return _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(a1 - 24);
}

// Address range: 0x2803 - 0x280a
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    int32_t result = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(a1 - (int32_t)&g9); // 0x2808
    return result;
}

// Address range: 0x280a - 0x2832
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t result) {
    // 0x280a
    unknown_4f80(result);
    return result;
}

// Address range: 0x2847 - 0x284a
int32_t function_2847(void) {
    // 0x2847
    return 0;
}

// Address range: 0x284a - 0x2885
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_function_, char const *>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_function_, char const *> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_15throw_function_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2) {
    // 0x284a
    g1 = unknown_51d0(a1, a2);
    return function_288a();
}

// Address range: 0x288a - 0x288c
int32_t function_288a(void) {
    // 0x288a
    return g1;
}

// Address range: 0x288c - 0x28c7
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_file_, char const *>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_file_, char const *> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_file_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2) {
    // 0x288c
    g1 = unknown_5250(a1, a2);
    return function_28cc();
}

// Address range: 0x28cc - 0x28ce
int32_t function_28cc(void) {
    // 0x28cc
    return g1;
}

// Address range: 0x28ce - 0x2909
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_line_, int>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_line_, int> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_line_EiEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKS8_E4typeESB_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2) {
    // 0x28ce
    g1 = unknown_52d0(a1, a2);
    return function_290e();
}

// Address range: 0x290e - 0x2910
int32_t function_290e(void) {
    // 0x290e
    return g1;
}

// Address range: 0x2910 - 0x297f
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::shared_ptr<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1INS1_10clone_implINS1_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    int32_t v2;
    if (a2 != 0) {
        // 0x2933
        v2 = a2 + 24;
        // branch -> 0x2940
    } else {
        v2 = 0;
    }
    // 0x2940
    *a1 = v2;
    unknown_5350(v1 + 4, a2);
    unknown_3baa(v1, a2, a2);
    g1 = 0;
    return function_2984();
}

// Address range: 0x2984 - 0x2986
int32_t function_2984(void) {
    // 0x2984
    return g1;
}

// Address range: 0x2986 - 0x29bd
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_function_, char const *> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_15throw_function_EPKcEE(int32_t a1, int32_t * a2) {
    // 0x2986
    *(int32_t *)(a1 + 8) = *a2;
    g1 = a1;
    return function_29c2((int32_t)a2, a1);
}

// Address range: 0x29c2 - 0x29c4
int32_t function_29c2(int32_t a1, int32_t a2) {
    // 0x29c2
    return g1;
}

// Address range: 0x29c4 - 0x29fb
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_file_, char const *> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_file_EPKcEE(int32_t a1, int32_t * a2) {
    // 0x29c4
    *(int32_t *)(a1 + (int32_t)&g24) = *a2;
    g1 = a1;
    return function_2a00((int32_t)a2, a1);
}

// Address range: 0x2a00 - 0x2a02
int32_t function_2a00(int32_t a1, int32_t a2) {
    // 0x2a00
    return g1;
}

// Address range: 0x2a02 - 0x2a08
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_line_, int> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_line_EiEE(void) {
    // 0x2a02
    return 0;
}

// Address range: 0x2a0a - 0x2a39
int32_t function_2a0a(int32_t a1) {
    char * v1 = (char *)(g4 + 0x458be445); // 0x2a0a
    *v1 = *v1 | (char)g4;
    g1 |= 137;
    int32_t v2 = g2 + 1; // 0x2a12
    g2 = v2;
    int32_t v3 = v2; // 0x2a1a
    if (v2 != 0 && g4 != 1) {
        // bb
        function_2a7a();
        v3 = g2;
        // branch -> 0x2a15
    }
    // 0x2a15
    *(int32_t *)(v3 - 12) = -0x1bba7700;
    int32_t v4 = *(int32_t *)(g2 - 32); // 0x2a1f
    int32_t v5 = *(int32_t *)(g2 - 28); // 0x2a24
    *(int32_t *)(v5 + (int32_t)&g8) = *(int32_t *)v4;
    int32_t result = *(int32_t *)(g2 - 28); // 0x2a2a
    g1 = result;
    if (*(int32_t *)(g2 - 12) == -0x1bba7700) {
        // bb3
        result = function_2a3e();
        // branch -> 0x2a39
    }
    // 0x2a39
    return result;
}

// Address range: 0x2a3e - 0x2a40
int32_t function_2a3e(void) {
    // 0x2a3e
    return g1;
}

// Address range: 0x2a40 - 0x2a6e
// Demangled:     boost::detail::shared_count::shared_count<boost::exception_detail::clone_impl<boost::exception_detail::clone_impl::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::clone_impl::bad_alloc_> *)
int32_t _ZN5boost6detail12shared_countC1INS_16exception_detail10clone_implINS3_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2) {
    // 0x2a40
    *a1 = 0;
    return (int32_t)a1;
}

// Address range: 0x2a74 - 0x2a75
int32_t function_2a74(void) {
    // 0x2a74
    return 0;
}

// Address range: 0x2a7a - 0x2a97
int32_t function_2a7a(void) {
    // 0x2a7a
    unknown_550c(g3);
    *(int32_t *)*(int32_t *)(g2 - 28) = g3;
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x2a8c
    g1 = v1;
    if (v1 == 0) {
        // bb
        g1 = function_2ac5();
        // branch -> 0x2a95
    }
    // 0x2a95
    return function_2ac0();
}

// Address range: 0x2a98 - 0x2a99
int32_t function_2a98(void) {
    // 0x2a98
    return 0;
}

// Address range: 0x2a9e - 0x2aa3
int32_t function_2a9e(int32_t a1) {
    // 0x2a9e
    return g3;
}

// Address range: 0x2ac0 - 0x2ac1
int32_t function_2ac0(void) {
    // 0x2ac0
    return g1;
}

// Address range: 0x2ac5 - 0x2acb
int32_t function_2ac5(void) {
    // 0x2ac5
    return g1;
}

// Address range: 0x2acc - 0x2b12
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          constructor
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::sp_counted_impl_p(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEC1EPS5_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    unknown_3ac6(v1);
    *a1 = (int32_t)&g10;
    *(int32_t *)(v1 + (int32_t)&g24) = a2;
    g1 = 0;
    return function_2b17();
}

// Address range: 0x2b17 - 0x2b19
int32_t function_2b17(void) {
    // 0x2b17
    return g1;
}

// Address range: 0x2b19 - 0x2b54
// Demangled:     void boost::checked_delete<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost14checked_deleteINS_16exception_detail10clone_implINS1_10bad_alloc_EEEEEvPT_(int32_t * a1) {
    // 0x2b19
    if (a1 != NULL) {
        // 0x2b36
        // branch -> 0x2b48
    }
    // 0x2b48
    g1 = 0;
    return function_2b59();
}

// Address range: 0x2b59 - 0x2b5b
int32_t function_2b59(void) {
    // 0x2b59
    return g1;
}

// Address range: 0x2b7c - 0x2bb9
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          constructor
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g10;
    unknown_3bbe(result);
    function_2bbe();
    return result;
}

// Address range: 0x2bbe - 0x2bca
int32_t function_2bbe(void) {
    int32_t v1 = *(int32_t *)(g2 - 12) ^ -0x1bba7700; // 0x2bc1
    g1 = v1;
    int32_t result = v1; // 0x2bc8
    if (v1 == 0) {
        // bb
        result = function_2bcf();
        // branch -> 0x2bca
    }
    // 0x2bca
    return result;
}

// Address range: 0x2bcf - 0x2bd1
int32_t function_2bcf(void) {
    // 0x2bcf
    return g1;
}

// Address range: 0x2bd2 - 0x2bfa
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t result) {
    // 0x2bd2
    unknown_574e(result);
    return result;
}

// Address range: 0x2c04 - 0x2c0b
int32_t function_2c04(int32_t a1) {
    int32_t v1 = g1 + (int32_t)&g9; // 0x2c04
    g1 = v1;
    int32_t result = v1; // 0x2c09
    if (v1 == 0) {
        // bb
        result = function_2c10();
        // branch -> 0x2c0b
    }
    // 0x2c0b
    return result;
}

// Address range: 0x2c10 - 0x2c12
int32_t function_2c10(void) {
    // 0x2c10
    return g1;
}

// Address range: 0x2c40 - 0x2c41
int32_t function_2c40(int32_t a1) {
    // 0x2c40
    return g1;
}

// Address range: 0x2d74 - 0x2d75
int32_t function_2d74(int32_t a1) {
    // 0x2d74
    return g1;
}

// Address range: 0x2daa - 0x2dab
int32_t function_2daa(int32_t a1) {
    // 0x2daa
    return g1;
}

// Address range: 0x2f44 - 0x2f45
int32_t function_2f44(int32_t a1, int32_t a2) {
    // 0x2f44
    return g1;
}

// Address range: 0x2fc0 - 0x2fe0
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::dispose()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(int32_t a1) {
    // 0x2fc0
    return *(int32_t *)(a1 + (int32_t)&g24);
}

// Address range: 0x2fe2 - 0x2ff1
int32_t function_2fe2(int32_t a1, int32_t a2) {
    char * v1 = (char *)(g3 + 0x3365f445); // 0x2fe4
    *v1 = (char)g4 + *v1;
    int32_t v2 = (g1 & -256) + (int32_t)&g9; // 0x2fea
    g1 = v2;
    int32_t result = v2; // 0x2fef
    if (v2 == 0) {
        // bb
        result = function_2ff6();
        // branch -> 0x2ff1
    }
    // 0x2ff1
    return result;
}

// Address range: 0x2ff6 - 0x2ff8
int32_t function_2ff6(void) {
    // 0x2ff6
    return g1;
}

// Address range: 0x2ff8 - 0x3026
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::get_deleter(std::type_info const &)
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(int32_t a1, int32_t a2) {
    // 0x2ff8
    g1 = 0;
    return function_302b(a2, a1);
}

// Address range: 0x302b - 0x302d
int32_t function_302b(int32_t a1, int32_t a2) {
    // 0x302b
    return g1;
}

// Address range: 0x302e - 0x3035
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1) {
    // 0x302e
    return _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(a1 - 24);
}

// Address range: 0x3036 - 0x3056
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(int32_t a1) {
    // 0x3036
    return 0;
}

// Address range: 0x305a - 0x308a
int32_t function_305a(void) {
    int32_t * v1 = (int32_t *)-0x1bba743d; // 0x305a
    *v1 = *v1 - 1;
    int32_t v2 = 0; // ebx
    unknown_53e6(v2, 0);
    g1 = v2 == 0 ? 0 : v2 + 24;
    if (*(int32_t *)-12 == -0x1bba7700) {
        // bb
        g1 = function_30a3();
        // branch -> 0x3088
    }
    // 0x3088
    return function_309e();
}

// Address range: 0x309e - 0x309f
int32_t function_309e(void) {
    // 0x309e
    return g1;
}

// Address range: 0x30a3 - 0x30aa
int32_t function_30a3(void) {
    // 0x30a3
    return g1;
}

// Address range: 0x30aa - 0x30b1
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    // 0x30aa
    return _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(a1 - 24);
}

// Address range: 0x30b2 - 0x30d2
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::rethrow() const
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    // 0x30b2
    return 0;
}

// Address range: 0x30d8 - 0x30d9
int32_t function_30d8(void) {
    // 0x30d8
    return 0;
}

// Address range: 0x3138 - 0x3139
int32_t function_3138(int32_t a1, int32_t a2, int32_t a3) {
    // 0x3138
    return g1;
}

// Address range: 0x4486 - 0x4487
int32_t function_4486(int32_t a1) {
    // 0x4486
    return g1;
}

// Address range: 0x4ef3 - 0x4ef4
int32_t function_4ef3(int32_t a1) {
    // 0x4ef3
    return g1;
}

// Address range: 0x8d0000f7 - 0x8d0000f8
int32_t function_8d0000f7(void) {
    // 0x8d0000f7
    return g1;
}

// --------------- Dynamically Linked Functions ---------------

// int32_t __cxa_pure_virtual(int32_t a1);
// int32_t _ZTISt13runtime_error(int32_t a1, int32_t a2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected language: C++
// Detected functions: 315
// Decompilation date: 2018-06-10 00:06:10
