//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct vtable_1df4_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)();
    int32_t (*e3)();
    int32_t (*e4)(int32_t, int32_t);
};

struct vtable_1eac_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
};

struct vtable_1f14_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
    int32_t (*e2)(int32_t);
    int32_t (*e3)(int32_t);
};

struct vtable_1f74_type {
    int32_t (*e0)(int32_t *);
    int32_t (*e1)(int32_t);
};

// ------------------------- Classes --------------------------

// N5boost16exception_detail10bad_alloc_E
// N5boost16exception_detail10clone_baseE
// N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE (base classes: N5boost16exception_detail10bad_alloc_E, N5boost16exception_detail10clone_baseE)
// N5boost6detail15sp_counted_baseE
// N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE (base classes: N5boost6detail15sp_counted_baseE)
// N5boost6system12system_errorE
// N5boost9exceptionE

// ------------------- Function Prototypes --------------------

void _7e_clone_impl(int32_t this, int32_t __in_chrg);
void _GLOBAL__sub_I_sync_cpp(void);
int32_t _Z41__static_initialization_and_destruction_0ii(void);
int32_t _ZN5boost10error_infoINS_11throw_file_EPKcEC1ES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10error_infoINS_11throw_line_EiEC1Ei(int32_t * a1, int32_t a2);
int32_t _ZN5boost10error_infoINS_15throw_function_EPKcEC1ES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1ERKS4_(int32_t * a1, int32_t a2);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1INS1_10clone_implINS1_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t result);
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1);
int32_t _ZN5boost12noncopyable_11noncopyableD1Ev(int32_t a1);
int32_t _ZN5boost14checked_deleteINS_16exception_detail10clone_implINS1_10bad_alloc_EEEEEvPT_(int32_t * a1);
int32_t _ZN5boost16exception_detail10bad_alloc_C1ERKS1_(int32_t a1, int32_t a2);
int32_t _ZN5boost16exception_detail10bad_alloc_C1Ev(int32_t result);
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t result);
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseC1ERKS1_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_baseC1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t result);
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS2_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS3_(int32_t a1, int32_t a2);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t result);
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE5adoptEPS2_(int32_t a1, int32_t result);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7add_refEv(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7releaseEv(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEaSERKS3_(int32_t result, int32_t * a2);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1ERKS3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1Ev(int32_t * a1);
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t a1);
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t a1);
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t * a2);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_file_EPKcEE(int32_t a1, int32_t * a2);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_line_EiEE(int32_t a1, int32_t * a2);
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_15throw_function_EPKcEE(int32_t a1, int32_t * a2);
int32_t _ZN5boost3argILi1EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi2EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi3EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi4EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi5EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi6EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi7EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi8EEC1Ev(int32_t a1);
int32_t _ZN5boost3argILi9EEC1Ev(int32_t a1);
int32_t _ZN5boost6detail12shared_countC1ERKS1_(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail12shared_countC1INS_16exception_detail10clone_implINS3_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail12shared_countD1Ev(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_base12add_ref_copyEv(int32_t a1);
int32_t _ZN5boost6detail15sp_counted_base12weak_releaseEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(void);
int32_t _ZN5boost6detail15sp_counted_base7releaseEv(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseC1Ev(int32_t * a1);
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t result);
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1);
int32_t _ZN5boost6detail16atomic_incrementEPi(int32_t * a1);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(int32_t a1, int32_t a2);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(void);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEC1EPS5_(int32_t result, int32_t a2);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t result);
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1);
int32_t _ZN5boost6detail23atomic_exchange_and_addEPii(int32_t * a1, int32_t a2);
int32_t _ZN5boost6detail26sp_enable_shared_from_thisEz(void);
int32_t _ZN5boost6system12system_errorD0Ev(int32_t result);
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1);
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t result);
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1);
int32_t _ZN5boost6system15error_conditionC1EiRKNS0_14error_categoryE(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZN5boost6systemeqERKNS0_15error_conditionES3_(int32_t * a1, int32_t a2);
int32_t _ZN5boost9exceptionC1ERKS0_(int32_t * a1, int32_t a2);
int32_t _ZN5boost9exceptionC1Ev(int32_t * a1);
int32_t _ZN5boost9exceptionD0Ev(int32_t result);
int32_t _ZN5boost9exceptionD1Ev(void);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_file_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_line_EiEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKS8_E4typeESB_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2);
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_15throw_function_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t result, int32_t a2);
void _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t this);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(int32_t a1);
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
int32_t _ZNK5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE3getEv(int32_t * a1);
int32_t _ZNK5boost6system10error_code5valueEv(int32_t * a1);
int32_t _ZNK5boost6system10error_code7messageEv(int32_t a1, int32_t result);
int32_t _ZNK5boost6system10error_code8categoryEv(int32_t a1);
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1);
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1);
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t result, int32_t a2, int32_t a3);
int32_t _ZNK5boost6system14error_categoryeqERKS1_(int32_t a1, int32_t a2);
int32_t _ZNSt9bad_allocC1ERKS_(int32_t result, int32_t a2);
int32_t _ZNSt9bad_allocC1Ev(int32_t result);
int32_t _ZNSt9exceptionC1ERKS_(int32_t result, int32_t a2);
int32_t _ZNSt9exceptionC1Ev(int32_t result);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1);
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1);
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1);
int32_t _ZTSN5boost6system14error_categoryE(int32_t a1, int32_t a2);
int32_t function_1030(void);
int32_t function_106c(int32_t a1);
int32_t function_10a(void);
int32_t function_10b1(void);
int32_t function_10c5(void);
int32_t function_10c8(int32_t a1);
int32_t function_10d0(int32_t a1);
int32_t function_10e(void);
int32_t function_10e9(void);
int32_t function_10ef(void);
int32_t function_1106(void);
int32_t function_110b(void);
int32_t function_118(void);
int32_t function_11b1(void);
int32_t function_11e1(int32_t a1);
int32_t function_122(void);
int32_t function_128e(int32_t a1);
int32_t function_12e2(int32_t a1);
int32_t function_1336(int32_t a1);
int32_t function_138(void);
int32_t function_138a(int32_t a1);
int32_t function_13b4(int32_t a1);
int32_t function_13de(int32_t a1);
int32_t function_13f2(int32_t a1);
int32_t function_1402(int32_t a1);
int32_t function_142c(void);
int32_t function_146a(int32_t a1, int32_t a2);
int32_t function_1471(void);
int32_t function_1496(int32_t a1);
int32_t function_153e(void);
int32_t function_1587(void);
int32_t function_15d3(void);
int32_t function_161c(int32_t a1);
int32_t function_1641(void);
int32_t function_1643(void);
int32_t function_1688(int32_t a1);
int32_t function_16b9(void);
int32_t function_171(int32_t a1, int32_t a2);
int32_t function_178f(void);
int32_t function_17c2(int32_t a1);
int32_t function_17d8(void);
int32_t function_181b(void);
int32_t function_1834(void);
int32_t function_1836(void);
int32_t function_1838(void);
int32_t function_1845(void);
int32_t function_1847(void);
int32_t function_185c(void);
int32_t function_1861(void);
int32_t function_18d0(void);
int32_t function_1904(int32_t a1, int32_t a2);
int32_t function_1919(void);
int32_t function_193c(int32_t a1, int32_t a2);
int32_t function_194d(void);
int32_t function_19c0(void);
int32_t function_19e4(void);
int32_t function_19f5(void);
int32_t function_1a5(void);
int32_t function_1a74(void);
int32_t function_1a78(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1a85(void);
int32_t function_1ab0(int32_t a1);
int32_t function_1ad3(void);
int32_t function_1afe(int32_t a1, int32_t a2);
int32_t function_1b13(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1b16(void);
int32_t function_1b58(void);
int32_t function_1b9a(void);
int32_t function_1bda(int32_t a1);
int32_t function_1c0a(int32_t a1);
int32_t function_1c0f(void);
int32_t function_1c4e(int32_t a1, int32_t a2);
int32_t function_1c8c(int32_t a1, int32_t a2);
int32_t function_1cca(int32_t a1, int32_t a2);
int32_t function_1cfe(void);
int32_t function_1d24(void);
int32_t function_1d4c(void);
int32_t function_1d51(void);
int32_t function_1d7e(int32_t a1, int32_t a2);
int32_t function_1da3(void);
int32_t function_1de5(void);
int32_t function_1e4(void);
int32_t function_1e4a(void);
int32_t function_1e5b(void);
int32_t function_1e8e(int32_t a1, int32_t a2);
int32_t function_1e9c(void);
int32_t function_1ed8(int32_t a1);
int32_t function_1ee4(int32_t a1, int32_t a2);
int32_t function_20e(int32_t a1);
int32_t function_2220(int32_t a1, int32_t a2);
int32_t function_2232(void);
int32_t function_2267(int32_t a1, int32_t a2);
int32_t function_2296(void);
int32_t function_22da(void);
int32_t function_22df(void);
int32_t function_2314(void);
int32_t function_246(int32_t a1, int32_t a2);
int32_t function_27e(int32_t a1, int32_t a2);
int32_t function_299e(int32_t a1);
int32_t function_2b6(int32_t a1, int32_t a2);
int32_t function_31c(int32_t a1);
int32_t function_340b(int32_t a1);
int32_t function_35d(void);
int32_t function_374(void);
int32_t function_385(void);
int32_t function_4b1(void);
int32_t function_4eb(int32_t a1);
int32_t function_52a(void);
int32_t function_609(void);
int32_t function_618(void);
int32_t function_61a(void);
int32_t function_62f(void);
int32_t function_634(void);
int32_t function_67d(int32_t a1, int32_t a2);
int32_t function_6b4(int32_t a1);
int32_t function_6fb(int32_t a1);
int32_t function_735(int32_t a1);
int32_t function_746(void);
int32_t function_78(void);
int32_t function_785(void);
int32_t function_78c(int32_t a1);
int32_t function_800(int32_t a1);
int32_t function_867(void);
int32_t function_978(int32_t a1);
int32_t function_9b2(int32_t a1);
int32_t function_b29(void);
int32_t function_b62(void);
int32_t function_bb4(void);
int32_t function_bf8(void);
int32_t function_c09(void);
int32_t function_c49(void);
int32_t function_c83(int32_t a1, int32_t a2);
int32_t function_ccb(int32_t a1, int32_t a2, int32_t a3);
int32_t function_d25(void);
int32_t function_d55(int32_t a1);
int32_t function_d86(int32_t a1);
int32_t function_d9c(int32_t a1);
int32_t function_deb(int32_t a1, int32_t a2, int32_t a3);
int32_t function_e3b(int32_t a1, int32_t a2);
int32_t function_e42(void);
int32_t function_f74(void);
int32_t function_f9e(void);
int32_t function_faf(void);
int32_t function_fe2(void);
int32_t unknown_1ec4(int32_t a1);
int32_t unknown_24f2(int32_t a1, int32_t a2, int32_t a3);
int32_t unknown_2506(int32_t a1);
int32_t unknown_25c4(int32_t a1, int32_t a2);
int32_t unknown_269a(int32_t a1, int32_t a2);
int32_t unknown_29ea(int32_t a1);
int32_t unknown_2a16(int32_t a1);
int32_t unknown_2b30(int32_t a1);
int32_t unknown_2b90(int32_t a1);
int32_t unknown_2c1a(int32_t a1, int32_t a2);
int32_t unknown_2d00(int32_t a1);
int32_t unknown_2ee4(int32_t a1);
int32_t unknown_2f26(int32_t a1, int32_t a2);
int32_t unknown_300c(int32_t a1, int32_t a2);
int32_t unknown_30cc(int32_t a1);
int32_t unknown_3192(int32_t a1, int32_t a2);
int32_t unknown_31d4(int32_t a1, int32_t a2);
int32_t unknown_3216(int32_t a1, int32_t a2);
int32_t unknown_326c(int32_t a1);
int32_t unknown_3498(int32_t a1);
int32_t unknown_36e8(void);
int32_t unknown_3768(int32_t a1, int32_t a2);
int32_t unknown_37e8(int32_t a1, int32_t a2);
int32_t unknown_3868(int32_t a1, int32_t a2);
int32_t unknown_38ae(int32_t a1, int32_t a2);
int32_t unknown_3a24(int32_t a1, int32_t a2);
int32_t unknown_3c66(int32_t a1);

// --------------------- Global Variables ---------------------

bool g1 = false; // cf
int32_t g2 = 0; // eax
int32_t g3 = 0; // ebp
int32_t g4 = 0; // ebx
int32_t g5 = 0; // ecx
int32_t g6 = 0; // edi
int32_t g7 = 0; // edx
int32_t g8 = 0; // esp
int32_t g9 = -0x5e9a1fbb;
int32_t g10 = 20;
int32_t g11 = 0x65e44589;
int32_t g12 = 0x31f44589;
int32_t g15 = 2998;
char g22 = -28;
int32_t g17 = 0x1a05;
int32_t g18 = 0x226a;
int32_t g20 = 0x14ca;
int32_t g21 = 1790;
int32_t g23 = 0;
int32_t g24 = 0;
int32_t g25 = 0;
char * g26 = "\x55\x89\xe5\x83\xec\x38\x8b\x45\x08\x89\x45\xe4\x65\xa1\x14";
int32_t g27 = 0;
int32_t g28 = 372;
char g29 = 87;
bool g30 = false; // zf
struct vtable_1df4_type g13 = {
    .e0 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev,
    .e1 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev,
    .e2 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv,
    .e3 = _ZN5boost6detail15sp_counted_base7destroyEv,
    .e4 = _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info
};
struct vtable_1eac_type g14 = {
    .e0 = _ZN5boost6system12system_errorD1Ev,
    .e1 = _ZN5boost6system12system_errorD0Ev,
    .e2 = _ZNK5boost6system12system_error4whatEv
};
struct vtable_1f14_type g16 = {
    .e0 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev,
    .e1 = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev,
    .e2 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2,
    .e3 = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv
};
struct vtable_1f74_type g19 = {
    .e0 = _ZN5boost16exception_detail10bad_alloc_D1Ev,
    .e1 = _ZN5boost16exception_detail10bad_alloc_D0Ev
};

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x3
// Demangled:     __static_initialization_and_destruction_0(int, int)
int32_t _Z41__static_initialization_and_destruction_0ii(void) {
    // 0x0
    return 0;
}

// From module:   /usr/include/boost/exception/exception.hpp
// Address range: 0x8 - 0xe
// Line range:    411 - 92
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone() const
void _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t this) {
    int32_t v1 = 0; // ecx
    char * v2 = (char *)(v1 + 0x458be445);
    *v2 = *v2 | (char)v1;
}

// From module:   /usr/include/boost/exception/exception.hpp
// Address range: 0xe - 0x13
// Line range:    404 - 71
void _7e_clone_impl(int32_t this, int32_t __in_chrg) {
    // 0xe
    g1 = false;
    g2 = &g29;
    int32_t v1 = 1; // bp+10
    g30 = v1 == 0;
    g3 = v1;
    int32_t v2 = -1; // bp+11
    g5 = v2;
    if (v1 != 0 && v2 != 0) {
        // bb
        function_78();
        // branch -> 0x13
    }
}

// Address range: 0x78 - 0xf2
int32_t function_78(void) {
    int32_t result = g2; // bp+78
    if (g1 || g30) {
        // 0x7a
        return result;
    }
    unsigned char v1 = (char)(g5 / 256) + (char)result;
    char * v2 = (char *)((int32_t)v1 | result & -256);
    *v2 = *v2 + v1;
    _ZN5boost3argILi4EEC1Ev(376);
    _ZN5boost3argILi5EEC1Ev(377);
    _ZN5boost3argILi6EEC1Ev(378);
    _ZN5boost3argILi7EEC1Ev(379);
    _ZN5boost3argILi8EEC1Ev(380);
    _ZN5boost3argILi9EEC1Ev((int32_t)&g11);
    unsigned char v3 = *(char *)&g26;
    g2 = v3;
    if (v3 != 0) {
        // bb
        function_10a();
        // branch -> 0xd5
    }
    // 0xd5
    *(char *)&g26 = 1;
    _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv((int32_t)&g25);
    return 2860;
}

// Address range: 0x10a - 0x10b
int32_t function_10a(void) {
    // 0x10a
    return g2;
}

// Address range: 0x10e - 0x114
int32_t function_10e(void) {
    // 0x10e
    return 0;
}

// Address range: 0x118 - 0x11e
int32_t function_118(void) {
    // 0x118
    return 0;
}

// Address range: 0x122 - 0x128
int32_t function_122(void) {
    // 0x122
    return 0;
}

// Address range: 0x138 - 0x13b
int32_t function_138(void) {
    // 0x138
    return 0;
}

// Address range: 0x13b - 0x16c
// Line range:    0 - 82
void _GLOBAL__sub_I_sync_cpp(void) {
    // 0x13b
    g2 = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        function_171(1, 0xffff);
        // branch -> 0x16c
    }
}

// Address range: 0x171 - 0x173
int32_t function_171(int32_t a1, int32_t a2) {
    // 0x171
    return g2;
}

// Address range: 0x174 - 0x18e
// Demangled:     std::exception::exception()
int32_t _ZNSt9exceptionC1Ev(int32_t result) {
    // 0x174
    return result;
}

// Address range: 0x1a5 - 0x1a7
int32_t function_1a5(void) {
    // 0x1a5
    return 0;
}

// Address range: 0x1a8 - 0x1cd
// Demangled:     std::bad_alloc::bad_alloc()
int32_t _ZNSt9bad_allocC1Ev(int32_t result) {
    // 0x1a8
    function_31c(result);
    return result;
}

// Address range: 0x1e4 - 0x1e6
int32_t function_1e4(void) {
    // 0x1e4
    return 0;
}

// Address range: 0x1e6 - 0x209
// Demangled:     boost::noncopyable_::noncopyable::~noncopyable()
int32_t _ZN5boost12noncopyable_11noncopyableD1Ev(int32_t a1) {
    // 0x1e6
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // bp+207
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_20e(a1);
        // branch -> 0x209
    }
    // 0x209
    return result;
}

// Address range: 0x20e - 0x210
int32_t function_20e(int32_t a1) {
    // 0x20e
    return g2;
}

// Address range: 0x210 - 0x241
// Demangled:     boost::error_info<boost::throw_function_, char const *>::error_info(char const *)
int32_t _ZN5boost10error_infoINS_15throw_function_EPKcEC1ES3_(int32_t * a1, int32_t a2) {
    // 0x210
    *a1 = a2;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_246(a2, (int32_t)a1);
        // branch -> 0x241
    }
    // 0x241
    return result;
}

// Address range: 0x246 - 0x248
int32_t function_246(int32_t a1, int32_t a2) {
    // 0x246
    return g2;
}

// Address range: 0x248 - 0x279
// Demangled:     boost::error_info<boost::throw_file_, char const *>::error_info(char const *)
int32_t _ZN5boost10error_infoINS_11throw_file_EPKcEC1ES3_(int32_t * a1, int32_t a2) {
    // 0x248
    *a1 = a2;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // bp+277
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_27e(a2, (int32_t)a1);
        // branch -> 0x279
    }
    // 0x279
    return result;
}

// Address range: 0x27e - 0x280
int32_t function_27e(int32_t a1, int32_t a2) {
    // 0x27e
    return g2;
}

// Address range: 0x280 - 0x2b1
// Demangled:     boost::error_info<boost::throw_line_, int>::error_info(int)
int32_t _ZN5boost10error_infoINS_11throw_line_EiEC1Ei(int32_t * a1, int32_t a2) {
    // 0x280
    *a1 = a2;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_2b6(a2, (int32_t)a1);
        // branch -> 0x2b1
    }
    // 0x2b1
    return result;
}

// Address range: 0x2b6 - 0x2b8
int32_t function_2b6(int32_t a1, int32_t a2) {
    // 0x2b6
    return g2;
}

// Address range: 0x2b8 - 0x317
// Demangled:     boost::exception::exception()
int32_t _ZN5boost9exceptionC1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g24;
    int32_t v2 = v1 + 4;
    g2 = v2;
    function_1402(v2);
    *(int32_t *)(v1 + 8) = 0;
    *(int32_t *)(v1 + 12) = 0;
    *(int32_t *)(v1 + (int32_t)&g9) = -1;
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x318 - 0x31b
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD1Ev(void) {
    // 0x318
    return 0;
}

// Address range: 0x31c - 0x358
int32_t function_31c(int32_t a1) {
    // 0x31c
    *(int32_t *)(g3 - 12) = (int32_t)&g10;
    *(int32_t *)*(int32_t *)(g3 - 28) = (int32_t)&g24;
    function_1496(*(int32_t *)(g3 - 28) + 4);
    function_374();
    return *(int32_t *)(g3 - 28);
}

// Address range: 0x35d - 0x35f
int32_t function_35d(void) {
    // 0x35d
    return function_374();
}

// Address range: 0x374 - 0x380
int32_t function_374(void) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // bp+377
    g2 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_385();
        // branch -> 0x380
    }
    // 0x380
    return result;
}

// Address range: 0x385 - 0x387
int32_t function_385(void) {
    // 0x385
    return g2;
}

// Address range: 0x474 - 0x49c
// Demangled:     boost::exception::~exception()
int32_t _ZN5boost9exceptionD0Ev(int32_t result) {
    // 0x474
    function_78c(result);
    return result;
}

// Address range: 0x4b1 - 0x4b4
int32_t function_4b1(void) {
    // 0x4b1
    return 0;
}

// Address range: 0x4b4 - 0x4e6
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g23;
    function_4eb(result);
    return result;
}

// Address range: 0x4eb - 0x4fe
int32_t function_4eb(int32_t a1) {
    // 0x4eb
    return *(int32_t *)(g3 - 12) ^ 20;
}

// Address range: 0x4fe - 0x526
// Demangled:     boost::exception_detail::clone_base::~clone_base()
int32_t _ZN5boost16exception_detail10clone_baseD0Ev(int32_t result) {
    // 0x4fe
    g2 = result;
    function_9b2(result);
    return result;
}

// Address range: 0x52a - 0x53e
int32_t function_52a(void) {
    int32_t * v1 = (int32_t *)0x3365f445;
    *v1 = *v1 - 1;
    return &g10;
}

// Address range: 0x53e - 0x609
// Demangled:     boost::exception_detail::copy_boost_exception(boost::exception *, boost::exception const *)
int32_t _ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_(int32_t a1, int32_t * a2) {
    int32_t v1 = (int32_t)a2;
    g1 = false;
    int32_t v2; // bp-28
    int32_t v3 = &v2;
    g2 = v3;
    function_1688(v3);
    int32_t v4 = v1 + 4;
    int32_t v5; // bp+588
    if (v4 != 0) {
        // 0x57e
        g5 = *(int32_t *)(*(int32_t *)v4 + (int32_t)&g10);
        int32_t v6; // bp-24
        v5 = &v6;
        _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(v5);
        // branch -> 0x5b7
    }
    // 0x5b7
    *(int32_t *)(a1 + 12) = *(int32_t *)(v1 + 12);
    int32_t v7 = *(int32_t *)(v1 + (int32_t)&g9);
    *(int32_t *)(a1 + (int32_t)&g9) = v7;
    *(int32_t *)(a1 + 8) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g8 + 4) = v3;
    *(int32_t *)g8 = a1 + 4;
    *(int32_t *)g8 = v3;
    _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(v5);
    g2 = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        g2 = function_634();
        // branch -> 0x607
    }
    // 0x607
    return function_62f();
}

// Address range: 0x609 - 0x618
int32_t function_609(void) {
    // 0x609
    g4 = 0;
    _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(g3 - 20);
    return function_61a();
}

// Address range: 0x618 - 0x61a
int32_t function_618(void) {
    // 0x618
    return 0;
}

// Address range: 0x61a - 0x62a
int32_t function_61a(void) {
    // 0x61a
    _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(g3 - 24);
    return g4;
}

// Address range: 0x62f - 0x630
int32_t function_62f(void) {
    // 0x62f
    return g2;
}

// Address range: 0x634 - 0x639
int32_t function_634(void) {
    // 0x634
    return g2;
}

// Address range: 0x639 - 0x678
// Demangled:     boost::detail::atomic_exchange_and_add(int *, int)
int32_t _ZN5boost6detail23atomic_exchange_and_addEPii(int32_t * a1, int32_t a2) {
    int32_t result = *a1; // bp+662
    *a1 = result + a2;
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_67d(a2, (int32_t)a1);
        // branch -> 0x678
    }
    // 0x678
    return result;
}

// Address range: 0x67d - 0x683
int32_t function_67d(int32_t a1, int32_t a2) {
    // 0x67d
    return g2;
}

// Address range: 0x683 - 0x6af
// Demangled:     boost::detail::atomic_increment(int *)
int32_t _ZN5boost6detail16atomic_incrementEPi(int32_t * a1) {
    // 0x683
    *a1 = *a1 + 1;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_6b4((int32_t)a1);
        // branch -> 0x6af
    }
    // 0x6af
    return result;
}

// Address range: 0x6b4 - 0x6b6
int32_t function_6b4(int32_t a1) {
    // 0x6b4
    return g2;
}

// Address range: 0x6b6 - 0x6f6
// Demangled:     boost::detail::sp_counted_base::sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseC1Ev(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g21;
    *(int32_t *)(v1 + 4) = 1;
    *(int32_t *)(v1 + 8) = 1;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_6fb(v1);
        // branch -> 0x6f6
    }
    // 0x6f6
    return result;
}

// Address range: 0x6fb - 0x6fd
int32_t function_6fb(int32_t a1) {
    // 0x6fb
    return g2;
}

// Address range: 0x6fe - 0x730
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g21;
    function_735(result);
    return result;
}

// Address range: 0x735 - 0x741
int32_t function_735(int32_t a1) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // bp+738
    g2 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_746();
        // branch -> 0x741
    }
    // 0x741
    return result;
}

// Address range: 0x746 - 0x748
int32_t function_746(void) {
    // 0x746
    return g2;
}

// Address range: 0x748 - 0x770
// Demangled:     boost::detail::sp_counted_base::~sp_counted_base()
int32_t _ZN5boost6detail15sp_counted_baseD0Ev(int32_t result) {
    // 0x748
    _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE((int32_t *)result);
    return result;
}

// Address range: 0x785 - 0x788
int32_t function_785(void) {
    // 0x785
    return 0;
}

// Address range: 0x788 - 0x78b
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_base::destroy()
int32_t _ZN5boost6detail15sp_counted_base7destroyEv(void) {
    // 0x788
    return 0;
}

// Address range: 0x78c - 0x7ca
int32_t function_78c(int32_t a1) {
    // 0x78c
    *(int32_t *)(g3 - 12) = (int32_t)&g10;
    if (*(int32_t *)(g3 - 28) != 0) {
        // 0x7a5
        // branch -> 0x7b7
    }
    // 0x7b7
    return *(int32_t *)(g3 - 12) ^ 20;
}

// Address range: 0x7ca - 0x7fb
// Demangled:     boost::detail::sp_counted_base::add_ref_copy()
int32_t _ZN5boost6detail15sp_counted_base12add_ref_copyEv(int32_t a1) {
    // 0x7ca
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_800(a1 + 4);
        // branch -> 0x7fb
    }
    // 0x7fb
    return result;
}

// Address range: 0x800 - 0x802
int32_t function_800(int32_t a1) {
    // 0x800
    return g2;
}

// Address range: 0x802 - 0x862
// Demangled:     boost::detail::sp_counted_base::release()
int32_t _ZN5boost6detail15sp_counted_base7releaseEv(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = v1 + 4;
    g30 = v2 == 0;
    g2 = v2;
    if (function_e3b(v2, -1) == 1) {
        // 0x839
        function_106c(v1);
        // branch -> 0x856
    }
    // 0x856
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // bp+860
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_867();
        // branch -> 0x862
    }
    // 0x862
    return result;
}

// Address range: 0x867 - 0x869
int32_t function_867(void) {
    // 0x867
    return g2;
}

// Address range: 0x86a - 0x8c6
// Demangled:     boost::detail::sp_counted_base::weak_release()
int32_t _ZN5boost6detail15sp_counted_base12weak_releaseEv(int32_t * a1) {
    // 0x86a
    if (a1 == (int32_t *)-7) {
        // 0x8a1
        // branch -> 0x8b3
    }
    // 0x8b3
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x8c6 - 0x906
// Demangled:     boost::detail::shared_count::~shared_count()
int32_t _ZN5boost6detail12shared_countD1Ev(int32_t * a1) {
    // 0x8c6
    if (*a1 != 0) {
        int32_t v1 = *a1;
        g2 = v1;
        function_10c8(v1);
        // branch -> 0x8f3
    }
    // 0x8f3
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x906 - 0x956
// Demangled:     boost::detail::shared_count::shared_count(boost::detail::shared_count const &)
int32_t _ZN5boost6detail12shared_countC1ERKS1_(int32_t * a1, int32_t a2) {
    int32_t v1 = *(int32_t *)a2; // bp+926
    *a1 = v1;
    if (v1 != 0) {
        int32_t v2 = *a1; // bp+939
        g2 = v2;
        function_10d0(v2);
        // branch -> 0x943
    }
    // 0x943
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x956 - 0x973
// Demangled:     boost::detail::sp_enable_shared_from_this(ellipsis)
int32_t _ZN5boost6detail26sp_enable_shared_from_thisEz(void) {
    // 0x956
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // bp+971
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_978((int32_t)&g10);
        // branch -> 0x973
    }
    // 0x973
    return result;
}

// Address range: 0x978 - 0x97a
int32_t function_978(int32_t a1) {
    // 0x978
    return g2;
}

// Address range: 0x9b2 - 0x9b3
int32_t function_9b2(int32_t a1) {
    // 0x9b2
    return g2;
}

// Address range: 0xab6 - 0xb24
// Demangled:     boost::exception::exception(boost::exception const &)
int32_t _ZN5boost9exceptionC1ERKS0_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    *a1 = (int32_t)&g24;
    int32_t v2 = v1 + 4;
    g2 = v2;
    function_1ee4(v2, a2 + 4);
    *(int32_t *)(v1 + 8) = *(int32_t *)(a2 + 8);
    *(int32_t *)(v1 + 12) = *(int32_t *)(a2 + 12);
    int32_t v3 = *(int32_t *)(a2 + (int32_t)&g9);
    *(int32_t *)(v1 + (int32_t)&g9) = v3;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_b29();
        // branch -> 0xb24
    }
    // 0xb24
    return result;
}

// Address range: 0xb29 - 0xb2b
int32_t function_b29(void) {
    // 0xb29
    return g2;
}

// Address range: 0xb2c - 0xb5d
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::~shared_ptr()
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEED1Ev(int32_t a1) {
    // 0xb2c
    function_13f2(a1 + 4);
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_b62();
        // branch -> 0xb5d
    }
    // 0xb5d
    return result;
}

// Address range: 0xb62 - 0xb64
int32_t function_b62(void) {
    // 0xb62
    return g2;
}

// Address range: 0xb64 - 0xbaf
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::shared_ptr(boost::shared_ptr<boost::exception_detail::clone_base const> const &)
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1ERKS4_(int32_t * a1, int32_t a2) {
    // 0xb64
    *a1 = *(int32_t *)a2;
    int32_t v1 = (int32_t)a1 + 4;
    g30 = v1 == 0;
    g2 = v1;
    function_146a(v1, a2 + 4);
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_bb4();
        // branch -> 0xbaf
    }
    // 0xbaf
    return result;
}

// Address range: 0xbb4 - 0xbb6
int32_t function_bb4(void) {
    // 0xbb4
    return g2;
}

// Address range: 0xbb6 - 0xbf3
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g15;
    function_d9c(result);
    function_bf8();
    return result;
}

// Address range: 0xbf8 - 0xc04
int32_t function_bf8(void) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20;
    g2 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_c09();
        // branch -> 0xc04
    }
    // 0xc04
    return result;
}

// Address range: 0xc09 - 0xc0b
int32_t function_c09(void) {
    // 0xc09
    return g2;
}

// Address range: 0xc0c - 0xc34
// Demangled:     boost::system::error_category::~error_category()
int32_t _ZN5boost6system14error_categoryD0Ev(int32_t result) {
    // 0xc0c
    g2 = result;
    function_17c2(result);
    return result;
}

// Address range: 0xc49 - 0xc4c
int32_t function_c49(void) {
    // 0xc49
    return 0;
}

// Address range: 0xc4c - 0xc7e
// Demangled:     boost::system::error_category::operator==(boost::system::error_category const &) const
int32_t _ZNK5boost6system14error_categoryeqERKS1_(int32_t a1, int32_t a2) {
    int32_t result = (int32_t)(bool)(a1 == a2) | a1 & -256;
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_c83(a2, a1);
        // branch -> 0xc7e
    }
    // 0xc7e
    return result;
}

// Address range: 0xc83 - 0xc85
int32_t function_c83(int32_t a1, int32_t a2) {
    // 0xc83
    return g2;
}

// Address range: 0xc86 - 0xcc6
// Demangled:     boost::system::error_condition::error_condition(int, boost::system::error_category const &)
int32_t _ZN5boost6system15error_conditionC1EiRKNS0_14error_categoryE(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t v1 = (int32_t)a1;
    *a1 = a2;
    *(int32_t *)(v1 + 4) = a3;
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_ccb(a3, a2, v1);
        // branch -> 0xcc6
    }
    // 0xcc6
    return result;
}

// Address range: 0xccb - 0xccd
int32_t function_ccb(int32_t a1, int32_t a2, int32_t a3) {
    // 0xccb
    return g2;
}

// Address range: 0xccd - 0xd20
// Demangled:     boost::system::operator==(boost::system::error_condition const &, boost::system::error_condition const &)
int32_t _ZN5boost6systemeqERKNS0_15error_conditionES3_(int32_t * a1, int32_t a2) {
    // 0xccd
    int32_t v1;
    int32_t result;
    if (*(int32_t *)((int32_t)a1 + 4) != *(int32_t *)(a2 + 4)) {
        // 0xd0f
        v1 = 0;
        // branch -> 0xd14
        // 0xd14
        g2 = v1;
        result = v1;
        if (((int32_t)&g10 ^ 20) == 0) {
            // bb
            result = function_d25();
            // branch -> 0xd20
        }
        // 0xd20
        return result;
    }
    // 0xcfa
    if (*a1 == *(int32_t *)a2) {
        v1 = 1;
        // 0xd14
        g2 = v1;
        result = v1;
        if (((int32_t)&g10 ^ 20) == 0) {
            // bb
            result = function_d25();
            // branch -> 0xd20
        }
        // 0xd20
        return result;
    }
    // 0xd0f
    v1 = 0;
    // branch -> 0xd14
    // 0xd14
    g2 = v1;
    result = v1;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_d25();
        // branch -> 0xd20
    }
    // 0xd20
    return result;
}

// Address range: 0xd25 - 0xd27
int32_t function_d25(void) {
    // 0xd25
    return g2;
}

// Address range: 0xd28 - 0xd50
// Demangled:     boost::system::error_code::value() const
int32_t _ZNK5boost6system10error_code5valueEv(int32_t * a1) {
    int32_t result = *a1;
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_d55((int32_t)a1);
        // branch -> 0xd50
    }
    // 0xd50
    return result;
}

// Address range: 0xd55 - 0xd57
int32_t function_d55(int32_t a1) {
    // 0xd55
    return g2;
}

// Address range: 0xd58 - 0xd81
// Demangled:     boost::system::error_code::category() const
int32_t _ZNK5boost6system10error_code8categoryEv(int32_t a1) {
    int32_t result = *(int32_t *)(a1 + 4);
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_d86(a1);
        // branch -> 0xd81
    }
    // 0xd81
    return result;
}

// Address range: 0xd86 - 0xd88
int32_t function_d86(int32_t a1) {
    // 0xd86
    return g2;
}

// Address range: 0xd88 - 0xd9b
// Demangled:     boost::system::error_code::message() const
int32_t _ZNK5boost6system10error_code7messageEv(int32_t a1, int32_t result) {
    // 0xd88
    return result;
}

// Address range: 0xd9c - 0xde6
int32_t function_d9c(int32_t a1) {
    // 0xd9c
    *(int32_t *)(g3 - 12) = (int32_t)&g10;
    int32_t v1 = *(int32_t *)(g3 - 32);
    g2 = v1;
    int32_t v2 = function_1ab0(v1);
    int32_t v3 = *(int32_t *)(g3 - 28);
    g2 = v3;
    int32_t result = v3;
    if (*(int32_t *)(g3 - 12) == 20) {
        // bb
        result = function_deb(v3, *(int32_t *)(*(int32_t *)(g3 - 32) + 4), v2);
        // branch -> 0xde6
    }
    // 0xde6
    return result;
}

// Address range: 0xdeb - 0xdf2
int32_t function_deb(int32_t a1, int32_t a2, int32_t a3) {
    // 0xdeb
    return g2;
}

// Address range: 0xdf2 - 0xe3b
// Demangled:     boost::system::error_category::default_error_condition(int) const
int32_t _ZNK5boost6system14error_category23default_error_conditionEi(int32_t result, int32_t a2, int32_t a3) {
    // 0xdf2
    g2 = result;
    function_1a78(result, a3, a2);
    return result;
}

// Address range: 0xe3b - 0xe3d
int32_t function_e3b(int32_t a1, int32_t a2) {
    // 0xe3b
    int32_t result;
    if (g30) {
        // bb
        result = function_e42();
        // branch -> 0xe3d
    } else {
        // 0xe3b
        result = g2;
        // branch -> 0xe3d
    }
    // 0xe3d
    return result;
}

// Address range: 0xe42 - 0xe46
int32_t function_e42(void) {
    // 0xe42
    return g2;
}

// Address range: 0xe46 - 0xeb1
// Demangled:     boost::system::error_category::equivalent(int, boost::system::error_condition const &) const
int32_t _ZNK5boost6system14error_category10equivalentEiRKNS0_15error_conditionE(int32_t * a1) {
    // 0xe46
    int32_t v1; // bp-24
    int32_t v2 = &v1;
    g2 = v2;
    int32_t v3;
    int32_t v4;
    return function_1b13(v2, v3, (int32_t)a1, v4);
}

// Address range: 0xeb2 - 0xf22
// Demangled:     boost::system::error_category::equivalent(boost::system::error_code const &, int) const
int32_t _ZNK5boost6system14error_category10equivalentERKNS0_10error_codeEi(int32_t a1, int32_t a2, int32_t a3) {
    // 0xeb2
    g2 = a2;
    int32_t v1 = function_1c0a(a2);
    g2 = a1;
    if ((char)function_1afe(a1, v1) == 0) {
        // 0xf0a
        // branch -> 0xf0f
        // 0xf0f
        return 0;
    }
    // 0xef3
    g2 = a2;
    if (function_1bda(a2) == a3) {
        // 0xf0f
        return 1;
    }
    // 0xf0a
    // branch -> 0xf0f
    // 0xf0f
    return 0;
}

// Address range: 0xf22 - 0xf4d
// From class:    N5boost6system12system_errorE
// Type:          constructor
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD1Ev(int32_t * a1) {
    // 0xf22
    *a1 = (int32_t)&g14;
    return (int32_t)a1 + (int32_t)&g9;
}

// Address range: 0xf74 - 0xf76
int32_t function_f74(void) {
    // 0xf74
    return function_f9e();
}

// Address range: 0xf9e - 0xfaa
int32_t function_f9e(void) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20;
    g2 = v1;
    int32_t result = v1;
    if (v1 == 0) {
        // bb
        result = function_faf();
        // branch -> 0xfaa
    }
    // 0xfaa
    return result;
}

// Address range: 0xfaf - 0xfb6
int32_t function_faf(void) {
    // 0xfaf
    return g2;
}

// Address range: 0xfb6 - 0xfde
// From class:    N5boost6system12system_errorE
// Type:          virtual member function
// Demangled:     boost::system::system_error::~system_error()
int32_t _ZN5boost6system12system_errorD0Ev(int32_t result) {
    // 0xfb6
    g2 = result;
    function_1ed8(result);
    return result;
}

// Address range: 0xfe2 - 0xff6
int32_t function_fe2(void) {
    int32_t * v1 = (int32_t *)0x3365f445;
    *v1 = *v1 - 1;
    return &g10;
}

// Address range: 0xff6 - 0x1017
// From class:    N5boost6system12system_errorE
// Type:          virtual member function
// Demangled:     boost::system::system_error::what() const
int32_t _ZNK5boost6system12system_error4whatEv(int32_t a1) {
    // 0xff6
    return a1 + (int32_t)&g9;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(void) {
    // 0x1030
    return 0;
}

// Address range: 0x106c - 0x1094
int32_t function_106c(int32_t a1) {
    int32_t v1 = g3 - 16; // 0x1072
    g2 = v1;
    function_1d7e(v1, *(int32_t *)(g3 - 28) + 8);
    return g3 - 16;
}

// Address range: 0x10b1 - 0x10c4
int32_t function_10b1(void) {
    int32_t * v1 = (int32_t *)-0x7427763d; // 0x10b1
    *v1 = *v1 - 1;
    // 0x10c2
    return function_1106();
}

// Address range: 0x10c5 - 0x10c6
int32_t function_10c5(void) {
    // 0x10c5
    return 0;
}

// Address range: 0x10c8 - 0x10c9
int32_t function_10c8(int32_t a1) {
    // 0x10c8
    return g2;
}

// Address range: 0x10d0 - 0x10d8
int32_t function_10d0(int32_t a1) {
    int32_t * v1 = (int32_t *)(g5 - 0x76ff1428); // 0x10d0
    *v1 = *v1 - 1;
    int32_t v2 = g2; // 0x10d6
    return v2 + 36 & 255 | v2 & -256;
}

// Address range: 0x10e9 - 0x10ea
int32_t function_10e9(void) {
    // 0x10e9
    return 0;
}

// Address range: 0x10ef - 0x10f1
int32_t function_10ef(void) {
    // 0x10ef
    return 0;
}

// Address range: 0x1106 - 0x110b
int32_t function_1106(void) {
    // 0x1106
    return g2;
}

// Address range: 0x110b - 0x1110
int32_t function_110b(void) {
    // 0x110b
    return g2;
}

// Address range: 0x1110 - 0x1130
// Demangled:     std::exception::exception(std::exception const &)
int32_t _ZNSt9exceptionC1ERKS_(int32_t result, int32_t a2) {
    // 0x1110
    return result;
}

// Address range: 0x114a - 0x117d
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::refcount_ptr()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1Ev(int32_t * a1) {
    // 0x114a
    *a1 = 0;
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x117e - 0x11ac
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::~refcount_ptr()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEED1Ev(int32_t a1) {
    // 0x117e
    unknown_29ea(a1);
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x11aa
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_11b1();
        // branch -> 0x11ac
    }
    // 0x11ac
    return result;
}

// Address range: 0x11b1 - 0x11b3
int32_t function_11b1(void) {
    // 0x11b1
    return g2;
}

// Address range: 0x11b4 - 0x11dc
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::get() const
int32_t _ZNK5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE3getEv(int32_t * a1) {
    int32_t result = *a1; // 0x11ce
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_11e1((int32_t)a1);
        // branch -> 0x11dc
    }
    // 0x11dc
    return result;
}

// Address range: 0x11e1 - 0x11e3
int32_t function_11e1(int32_t a1) {
    // 0x11e1
    return g2;
}

// Address range: 0x11e4 - 0x122b
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::operator=(boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container> const &)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEaSERKS3_(int32_t result, int32_t * a2) {
    // 0x11e4
    unknown_25c4(result, *a2);
    return result;
}

// Address range: 0x122c - 0x1265
// Demangled:     boost::exception_detail::clone_base::clone_base(boost::exception_detail::clone_base const &)
int32_t _ZN5boost16exception_detail10clone_baseC1ERKS1_(int32_t * a1, int32_t a2) {
    // 0x122c
    *a1 = (int32_t)&g23;
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x1266 - 0x1289
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi1EEC1Ev(int32_t a1) {
    // 0x1266
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x1287
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_128e(a1);
        // branch -> 0x1289
    }
    // 0x1289
    return result;
}

// Address range: 0x128e - 0x1290
int32_t function_128e(int32_t a1) {
    // 0x128e
    return g2;
}

// Address range: 0x1290 - 0x12ba
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi2EEC1Ev(int32_t a1) {
    // 0x1290
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x12ba - 0x12dd
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi3EEC1Ev(int32_t a1) {
    // 0x12ba
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x12db
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_12e2(a1);
        // branch -> 0x12dd
    }
    // 0x12dd
    return result;
}

// Address range: 0x12e2 - 0x12e4
int32_t function_12e2(int32_t a1) {
    // 0x12e2
    return g2;
}

// Address range: 0x12e4 - 0x130e
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi4EEC1Ev(int32_t a1) {
    // 0x12e4
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x130e - 0x1331
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi5EEC1Ev(int32_t a1) {
    // 0x130e
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x132f
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1336(a1);
        // branch -> 0x1331
    }
    // 0x1331
    return result;
}

// Address range: 0x1336 - 0x1338
int32_t function_1336(int32_t a1) {
    // 0x1336
    return g2;
}

// Address range: 0x1338 - 0x1362
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi6EEC1Ev(int32_t a1) {
    // 0x1338
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x1362 - 0x1385
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi7EEC1Ev(int32_t a1) {
    // 0x1362
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x1383
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_138a(a1);
        // branch -> 0x1385
    }
    // 0x1385
    return result;
}

// Address range: 0x138a - 0x138c
int32_t function_138a(int32_t a1) {
    // 0x138a
    return g2;
}

// Address range: 0x138c - 0x13af
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi8EEC1Ev(int32_t a1) {
    // 0x138c
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x13ad
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_13b4(a1);
        // branch -> 0x13af
    }
    // 0x13af
    return result;
}

// Address range: 0x13b4 - 0x13b6
int32_t function_13b4(int32_t a1) {
    // 0x13b4
    return g2;
}

// Address range: 0x13b6 - 0x13d9
// Demangled:     boost::arg<>::arg()
int32_t _ZN5boost3argILi9EEC1Ev(int32_t a1) {
    // 0x13b6
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x13d7
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_13de(a1);
        // branch -> 0x13d9
    }
    // 0x13d9
    return result;
}

// Address range: 0x13de - 0x13e0
int32_t function_13de(int32_t a1) {
    // 0x13de
    return g2;
}

// Address range: 0x13e0 - 0x13f2
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::adopt(boost::exception_detail::error_info_container *)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE5adoptEPS2_(int32_t a1, int32_t result) {
    // 0x13e0
    return result;
}

// Address range: 0x13f2 - 0x1400
int32_t function_13f2(int32_t a1) {
    // 0x13f2
    *(int32_t *)(g3 - 12) = (int32_t)&g10;
    return *(int32_t *)(g3 - 28);
}

// Address range: 0x1402 - 0x1427
int32_t function_1402(int32_t a1) {
    int32_t v1 = g2; // 0x1402
    unsigned char v2 = (char)v1 & -24; // 0x1402
    int32_t v3 = (int32_t)v2 | v1 & -256; // 0x1402
    char * v4 = (char *)v3; // 0x1405
    *v4 = *v4 - v2;
    char * v5 = (char *)(g4 + 0x558be445); // 0x1407
    unsigned char v6 = *v5; // 0x1407
    unsigned char v7 = (char)g5 + v6; // 0x1407
    *v5 = v7;
    int32_t v8 = g5 - 1; // 0x140d
    char * v9 = (char *)(g4 + 0x489e445); // 0x140f
    *v9 = *v9 + (char)v8 + (char)(v7 < v6);
    *(char *)g6 = ((char)v3 & -24) - (char)g6;
    char * v10 = (char *)(g4 + 0x3365f445); // 0x141a
    *v10 = (char)v8 + *v10;
    int32_t v11 = g6 + (int32_t)&g10; // 0x1420
    g2 = v11;
    int32_t result = v11; // 0x1425
    if (v11 == 0) {
        // bb
        result = function_142c();
        // branch -> 0x1427
    }
    // 0x1427
    return result;
}

// Address range: 0x142c - 0x142e
int32_t function_142c(void) {
    // 0x142c
    return g2;
}

// Address range: 0x142e - 0x146a
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::refcount_ptr(boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container> const &)
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEEC1ERKS3_(int32_t * a1, int32_t a2) {
    // 0x142e
    *a1 = *(int32_t *)a2;
    unknown_2d00((int32_t)a1);
    return (int32_t)&g10 ^ 20;
}

// Address range: 0x146a - 0x146c
int32_t function_146a(int32_t a1, int32_t a2) {
    // 0x146a
    int32_t result; // 0x146a
    if (g30) {
        // bb
        result = function_1471();
        // branch -> 0x146c
    } else {
        // 0x146a
        result = g2;
        // branch -> 0x146c
    }
    // 0x146c
    return result;
}

// Address range: 0x1471 - 0x1473
int32_t function_1471(void) {
    // 0x1471
    return g2;
}

// Address range: 0x1474 - 0x1496
// Demangled:     boost::exception_detail::bad_alloc_::bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_C1Ev(int32_t result) {
    // 0x1474
    return result;
}

// Address range: 0x1496 - 0x14ca
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
int32_t function_1496(int32_t a1) {
    int32_t v1 = *(int32_t *)(g3 - 28) + (int32_t)&g10; // 0x1499
    g2 = v1;
    function_161c(v1);
    *(int32_t *)*(int32_t *)(g3 - 28) = (int32_t)&g19;
    int32_t v2 = *(int32_t *)(g3 - 28); // 0x14ad
    *(int32_t *)(v2 + (int32_t)&g10) = (int32_t)&g20;
    return *(int32_t *)(g3 - 12) ^ 20;
}

// Address range: 0x14ca - 0x14d4
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D1Ev(int32_t a1) {
    // 0x14ca
    return function_299e(a1 - (int32_t)&g10);
}

// Address range: 0x14d4 - 0x1507
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          constructor
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D1Ev(int32_t * a1) {
    // 0x14d4
    *a1 = (int32_t)&g19;
    int32_t result = (int32_t)a1 + (int32_t)&g10; // 0x14f7
    *(int32_t *)result = (int32_t)&g20;
    return result;
}

// Address range: 0x153e - 0x1541
int32_t function_153e(void) {
    // 0x153e
    return 0;
}

// Address range: 0x1542 - 0x1549
int32_t _ZThn20_N5boost16exception_detail10bad_alloc_D0Ev(int32_t a1) {
    // 0x1542
    return _ZN5boost16exception_detail10bad_alloc_D0Ev(a1 - (int32_t)&g10);
}

// Address range: 0x154a - 0x1572
// From class:    N5boost16exception_detail10bad_alloc_E
// Type:          virtual member function
// Demangled:     boost::exception_detail::bad_alloc_::~bad_alloc_()
int32_t _ZN5boost16exception_detail10bad_alloc_D0Ev(int32_t result) {
    // 0x154a
    unknown_2a16(result);
    return result;
}

// Address range: 0x1587 - 0x158a
int32_t function_1587(void) {
    // 0x1587
    return 0;
}

// Address range: 0x158a - 0x15bc
// Demangled:     std::bad_alloc::bad_alloc(std::bad_alloc const &)
int32_t _ZNSt9bad_allocC1ERKS_(int32_t result, int32_t a2) {
    // 0x158a
    unknown_269a(result, a2);
    return result;
}

// Address range: 0x15d3 - 0x15d5
int32_t function_15d3(void) {
    // 0x15d3
    return 0;
}

// Address range: 0x15d6 - 0x1618
// Demangled:     boost::exception_detail::bad_alloc_::bad_alloc_(boost::exception_detail::bad_alloc_ const &)
int32_t _ZN5boost16exception_detail10bad_alloc_C1ERKS1_(int32_t a1, int32_t a2) {
    // 0x15d6
    g2 = a1;
    _ZTSN5boost6system14error_categoryE(a1, a2);
    return a1 + (int32_t)&g10;
}

// Address range: 0x161c - 0x163c
int32_t function_161c(int32_t a1) {
    char * v1 = (char *)(g4 + 0xc7e445); // 0x161c
    char v2 = (char)g5 + *v1; // 0x161c
    *v1 = v2;
    int32_t v3; // 0x1624
    char v4; // 0x1624
    if (v2 == 0) {
        int32_t v5 = function_1643(); // 0x1622
        v3 = v5;
        v4 = v5;
        // branch -> 0x1624
    } else {
        // 0x161c
        v3 = g2;
        v4 = *(char *)&g2;
        // branch -> 0x1624
    }
    // 0x1624
    *(char *)v3 = (char)v3 + v4;
    int32_t v6 = *(int32_t *)(g3 - 28); // 0x1626
    *(int32_t *)(v6 + (int32_t)&g10) = (int32_t)&g20;
    int32_t v7 = *(int32_t *)(g3 - 12) ^ 20; // 0x1633
    g2 = v7;
    int32_t result = v7; // 0x163a
    if (v7 == 0) {
        // bb4
        result = function_1641();
        // branch -> 0x163c
    }
    // 0x163c
    return result;
}

// Address range: 0x1641 - 0x1643
int32_t function_1641(void) {
    // 0x1641
    return g2;
}

// Address range: 0x1643 - 0x1644
int32_t function_1643(void) {
    // 0x1643
    return g2;
}

// Address range: 0x1644 - 0x1686
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &)
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS3_(int32_t a1, int32_t a2) {
    // 0x1644
    unknown_2c1a(a1, a2);
    return a1 + (int32_t)&g12;
}

// Address range: 0x1688 - 0x16b4
int32_t function_1688(int32_t a1) {
    uint32_t v1 = g2; // 0x1688
    *(int32_t *)v1 = (int32_t)g1 | 2 * v1;
    char * v2 = (char *)(g4 + 0xc7e445); // 0x168a
    unsigned char v3 = *v2; // 0x168a
    unsigned char v4 = (char)g5 + v3; // 0x168a
    *v2 = v4;
    int32_t v5 = g2; // 0x1690
    char v6 = v4 < v3; // 0x1690
    unsigned char v7 = (char)v5 + (char)&g22 + v6; // 0x1690
    char * v8 = (char *)((int32_t)v7 | v5 & -256); // 0x1692
    *v8 = *v8 + v7;
    int32_t v9 = *(int32_t *)(g3 - 28); // 0x1694
    *(int32_t *)(v9 + (int32_t)&g10) = (int32_t)&g17;
    int32_t v10 = *(int32_t *)(g3 - 28); // 0x169e
    *(int32_t *)(v10 + (int32_t)&g12) = (int32_t)&g18;
    int32_t v11 = *(int32_t *)(g3 - 12) ^ 20; // 0x16ab
    g2 = v11;
    int32_t result = v11; // 0x16b2
    if (v11 == 0) {
        // bb
        result = function_16b9();
        // branch -> 0x16b4
    }
    // 0x16b4
    return result;
}

// Address range: 0x16b9 - 0x16bb
int32_t function_16b9(void) {
    // 0x16b9
    return g2;
}

// Address range: 0x16bc - 0x176f
int32_t _ZN5boost16exception_detail13get_bad_allocILi42EEENS_10shared_ptrIKNS0_10clone_baseEEEv(int32_t a1) {
    // 0x16bc
    int32_t v1; // bp-68
    int32_t v2 = &v1; // 0x16d6
    unknown_2b30(v2);
    int32_t v3; // bp-96
    int32_t v4 = &v3; // 0x16e8
    unknown_300c(v4, v2);
    int32_t v5; // bp-44
    int32_t v6 = &v5; // 0x16fb
    function_193c(v6, (int32_t)&g28);
    int32_t v7; // bp-40
    int32_t v8 = &v7; // 0x170e
    g2 = v8;
    function_1904(v8, (int32_t)"/usr/include/boost/exception/detail/exception_ptr.hpp");
    int32_t v9; // bp-36
    int32_t v10 = &v9; // 0x1721
    __stack_chk_fail(v10, (int32_t)"boost::exception_ptr boost::exception_detail::get_bad_alloc() [with int Dummy = 42, boost::exception_ptr = boost::shared_ptr<const boost::exception_detail::clone_base>]");
    int32_t v11 = unknown_3192(v4, v10); // 0x1739
    unknown_3216(unknown_31d4(v11, v8), v6);
    unsigned char v12 = *(char *)0x16bc; // 0x1761
    int32_t result = v12; // 0x1768
    if (v12 != 0) {
        // bb
        result = function_17d8();
        // branch -> 0x1768
    }
    // 0x1768
    return result;
}

// Address range: 0x178f - 0x1790
int32_t function_178f(void) {
    // 0x178f
    return 0;
}

// Address range: 0x17c2 - 0x17c4
int32_t function_17c2(int32_t a1) {
    // 0x17c2
    return g2 & -248;
}

// Address range: 0x17d8 - 0x1812
int32_t function_17d8(void) {
    int32_t v1 = *(int32_t *)(g3 - 108); // 0x17e0
    g2 = v1;
    function_2220(v1, (int32_t)&g27);
    unknown_30cc(g3 - 92);
    unknown_2b90(g3 - 64);
    g2 = *(int32_t *)(g3 - 108);
    if (*(int32_t *)(g3 - 28) == 20) {
        // bb
        g2 = function_1861();
        // branch -> 0x1810
    }
    // 0x1810
    return function_185c();
}

// Address range: 0x181b - 0x1822
int32_t function_181b(void) {
    int32_t * v1 = (int32_t *)-0x76fd1405; // 0x181b
    *v1 = *v1 - 1;
    return 0;
}

// Address range: 0x1834 - 0x1836
int32_t function_1834(void) {
    // 0x1834
    return function_1838();
}

// Address range: 0x1836 - 0x1838
int32_t function_1836(void) {
    // 0x1836
    return 0;
}

// Address range: 0x1838 - 0x1845
int32_t function_1838(void) {
    // 0x1838
    unknown_30cc(g3 - 92);
    return function_1847();
}

// Address range: 0x1845 - 0x1847
int32_t function_1845(void) {
    // 0x1845
    return 0;
}

// Address range: 0x1847 - 0x1857
int32_t function_1847(void) {
    // 0x1847
    unknown_2b90(g3 - 64);
    return g4;
}

// Address range: 0x185c - 0x185d
int32_t function_185c(void) {
    // 0x185c
    return g2;
}

// Address range: 0x1861 - 0x186b
int32_t function_1861(void) {
    // 0x1861
    return g2;
}

// Address range: 0x186c - 0x18cb
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::release()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7releaseEv(int32_t * a1) {
    // 0x186c
    int32_t result; // 0x18c9
    if (*a1 == 0 || (char)*a1 == 0) {
        // 0x18b2
        // branch -> 0x18bf
        // 0x18bf
        g2 = (int32_t)&g10 ^ 20;
        result = (int32_t)&g10 ^ 20;
        if (((int32_t)&g10 ^ 20) == 0) {
            // bb
            result = function_18d0();
            // branch -> 0x18cb
        }
        // 0x18cb
        return result;
    }
    // 0x18b6
    *a1 = 0;
    // branch -> 0x18bf
    // 0x18bf
    g2 = (int32_t)&g10 ^ 20;
    result = (int32_t)&g10 ^ 20;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_18d0();
        // branch -> 0x18cb
    }
    // 0x18cb
    return result;
}

// Address range: 0x18d0 - 0x18d2
int32_t function_18d0(void) {
    // 0x18d0
    return g2;
}

// Address range: 0x18d2 - 0x1903
// Demangled:     boost::exception_detail::refcount_ptr<boost::exception_detail::error_info_container>::add_ref()
int32_t _ZN5boost16exception_detail12refcount_ptrINS0_20error_info_containerEE7add_refEv(int32_t * a1) {
    // 0x18d2
    return *a1;
}

// Address range: 0x1904 - 0x1914
int32_t function_1904(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // 0x190b
    g2 = v1;
    int32_t result = v1; // 0x1912
    if (v1 == 0) {
        // bb
        result = function_1919();
        // branch -> 0x1914
    }
    // 0x1914
    return result;
}

// Address range: 0x1919 - 0x191b
int32_t function_1919(void) {
    // 0x1919
    return g2;
}

// Address range: 0x191c - 0x193c
// Demangled:     boost::exception_detail::clone_base::clone_base()
int32_t _ZN5boost16exception_detail10clone_baseC1Ev(int32_t * a1) {
    // 0x191c
    *a1 = (int32_t)&g23;
    return (int32_t)a1;
}

// Address range: 0x193c - 0x1948
int32_t function_193c(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // 0x193f
    g2 = v1;
    int32_t result = v1; // 0x1946
    if (v1 == 0) {
        // bb
        result = function_194d();
        // branch -> 0x1948
    }
    // 0x1948
    return result;
}

// Address range: 0x194d - 0x194f
int32_t function_194d(void) {
    // 0x194d
    return g2;
}

// Address range: 0x1950 - 0x19bf
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::clone_impl(boost::exception_detail::bad_alloc_ const &)
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EEC1ERKS2_(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    unknown_2f26(v1, a2);
    int32_t v2 = v1 + (int32_t)&g12; // 0x1983
    unknown_326c(v2);
    *a1 = (int32_t)&g16;
    *(int32_t *)(v1 + (int32_t)&g10) = (int32_t)&g17;
    *(int32_t *)v2 = (int32_t)&g18;
    g2 = v1;
    function_1e8e(v1, a2);
    return function_19e4();
}

// Address range: 0x19c0 - 0x19c1
int32_t function_19c0(void) {
    // 0x19c0
    return 0;
}

// Address range: 0x19e4 - 0x19f0
int32_t function_19e4(void) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // 0x19e7
    g2 = v1;
    int32_t result = v1; // 0x19ee
    if (v1 == 0) {
        // bb
        result = function_19f5();
        // branch -> 0x19f0
    }
    // 0x19f0
    return result;
}

// Address range: 0x19f5 - 0x19fb
int32_t function_19f5(void) {
    // 0x19f5
    return g2;
}

// Address range: 0x19fb - 0x1a05
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1) {
    // 0x19fb
    return function_340b(a1 - (int32_t)&g12);
}

// Address range: 0x1a05 - 0x1a0f
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t a1) {
    // 0x1a05
    return function_340b(a1 - (int32_t)&g10);
}

// Address range: 0x1a10 - 0x1a6f
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          constructor
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g16;
    *(int32_t *)(result + (int32_t)&g10) = (int32_t)&g17;
    int32_t v1 = result + (int32_t)&g12; // 0x1a3d
    *(int32_t *)v1 = (int32_t)&g18;
    unknown_1ec4(v1);
    unknown_2ee4(result);
    function_1a74();
    return result;
}

// Address range: 0x1a74 - 0x1a77
int32_t function_1a74(void) {
    // 0x1a74
    return *(int32_t *)(g3 - 12);
}

// Address range: 0x1a78 - 0x1a80
int32_t function_1a78(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = g2 ^ 20; // 0x1a78
    g2 = v1;
    int32_t result = v1; // 0x1a7e
    if (v1 == 0) {
        // bb
        result = function_1a85();
        // branch -> 0x1a80
    }
    // 0x1a80
    return result;
}

// Address range: 0x1a85 - 0x1a87
int32_t function_1a85(void) {
    // 0x1a85
    return g2;
}

// Address range: 0x1a88 - 0x1a8f
int32_t _ZThn24_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    int32_t result = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(a1 - (int32_t)&g12); // 0x1a8d
    return result;
}

// Address range: 0x1a8f - 0x1a96
int32_t _ZThn20_N5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t a1) {
    int32_t result = _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(a1 - (int32_t)&g10); // 0x1a94
    return result;
}

// Address range: 0x1a96 - 0x1ab0
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::~clone_impl()
int32_t _ZN5boost16exception_detail10clone_implINS0_10bad_alloc_EED0Ev(int32_t result) {
    // 0x1a96
    return result;
}

// Address range: 0x1ab0 - 0x1abe
int32_t function_1ab0(int32_t a1) {
    // 0x1ab0
    unknown_3498(g2);
    return *(int32_t *)(g3 - 28);
}

// Address range: 0x1ad3 - 0x1ad6
int32_t function_1ad3(void) {
    // 0x1ad3
    return 0;
}

// Address range: 0x1ad6 - 0x1afd
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_function_, char const *>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_function_, char const *> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_15throw_function_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t result, int32_t a2) {
    // 0x1ad6
    return result;
}

// Address range: 0x1afe - 0x1b11
int32_t function_1afe(int32_t a1, int32_t a2) {
    int32_t result = unknown_36e8(); // 0x1b00
    g2 = result;
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // 0x1b08
    g7 = v1;
    if (v1 == 0) {
        // bb
        result = function_1b16();
        // branch -> 0x1b11
    }
    // 0x1b11
    return result;
}

// Address range: 0x1b13 - 0x1b14
int32_t function_1b13(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x1b13
    return g2;
}

// Address range: 0x1b16 - 0x1b18
int32_t function_1b16(void) {
    // 0x1b16
    return g2;
}

// Address range: 0x1b18 - 0x1b53
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_file_, char const *>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_file_, char const *> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_file_EPKcEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKSA_E4typeESD_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2) {
    int32_t result = unknown_3768(a1, a2); // 0x1b42
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1b58();
        // branch -> 0x1b53
    }
    // 0x1b53
    return result;
}

// Address range: 0x1b58 - 0x1b5a
int32_t function_1b58(void) {
    // 0x1b58
    return g2;
}

// Address range: 0x1b5a - 0x1b95
// Demangled:     boost::enable_if<boost::exception_detail::derives_boost_exception<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >, boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &>::type boost::operator<<<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>, boost::throw_line_, int>(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_line_, int> const &)
int32_t _ZN5boostlsINS_16exception_detail10clone_implINS1_10bad_alloc_EEENS_11throw_line_EiEENS_9enable_ifINS1_23derives_boost_exceptionIT_EERKS8_E4typeESB_RKNS_10error_infoIT0_T1_EE(int32_t a1, int32_t a2) {
    int32_t result = unknown_37e8(a1, a2); // 0x1b84
    g2 = result;
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1b9a();
        // branch -> 0x1b95
    }
    // 0x1b95
    return result;
}

// Address range: 0x1b9a - 0x1b9c
int32_t function_1b9a(void) {
    // 0x1b9a
    return g2;
}

// Address range: 0x1b9c - 0x1bda
// Demangled:     boost::shared_ptr<boost::exception_detail::clone_base const>::shared_ptr<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost10shared_ptrIKNS_16exception_detail10clone_baseEEC1INS1_10clone_implINS1_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t result) {
    // 0x1b9c
    int32_t v1;
    if (result != 0) {
        // 0x1bbf
        v1 = result + (int32_t)&g12;
        // branch -> 0x1bcc
    } else {
        v1 = 0;
    }
    // 0x1bcc
    *a1 = v1;
    return result;
}

// Address range: 0x1bda - 0x1c09
int32_t function_1bda(int32_t a1) {
    // 0x1bda
    unknown_3868(g7, g2);
    int32_t v1 = *(int32_t *)(g3 - 32); // 0x1be6
    unknown_24f2(*(int32_t *)(g3 - 28), v1, v1);
    return *(int32_t *)(g3 - 12) ^ 20;
}

// Address range: 0x1c0a - 0x1c0b
int32_t function_1c0a(int32_t a1) {
    // 0x1c0a
    return g2;
}

// Address range: 0x1c0f - 0x1c12
int32_t function_1c0f(void) {
    // 0x1c0f
    return 0;
}

// Address range: 0x1c12 - 0x1c49
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_function_, char const *> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_15throw_function_EPKcEE(int32_t a1, int32_t * a2) {
    // 0x1c12
    *(int32_t *)(a1 + 8) = *a2;
    g2 = a1;
    int32_t result = a1; // 0x1c47
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1c4e((int32_t)a2, a1);
        // branch -> 0x1c49
    }
    // 0x1c49
    return result;
}

// Address range: 0x1c4e - 0x1c50
int32_t function_1c4e(int32_t a1, int32_t a2) {
    // 0x1c4e
    return g2;
}

// Address range: 0x1c50 - 0x1c87
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_file_, char const *> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_file_EPKcEE(int32_t a1, int32_t * a2) {
    // 0x1c50
    *(int32_t *)(a1 + 12) = *a2;
    g2 = a1;
    int32_t result = a1; // 0x1c85
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1c8c((int32_t)a2, a1);
        // branch -> 0x1c87
    }
    // 0x1c87
    return result;
}

// Address range: 0x1c8c - 0x1c8e
int32_t function_1c8c(int32_t a1, int32_t a2) {
    // 0x1c8c
    return g2;
}

// Address range: 0x1c8e - 0x1cc5
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const & boost::exception_detail::set_info<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> const &, boost::error_info<boost::throw_line_, int> const &)
int32_t _ZN5boost16exception_detail8set_infoINS0_10clone_implINS0_10bad_alloc_EEEEERKT_S7_RKNS_10error_infoINS_11throw_line_EiEE(int32_t a1, int32_t * a2) {
    // 0x1c8e
    *(int32_t *)(a1 + (int32_t)&g9) = *a2;
    g2 = a1;
    int32_t result = a1; // 0x1cc3
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1cca((int32_t)a2, a1);
        // branch -> 0x1cc5
    }
    // 0x1cc5
    return result;
}

// Address range: 0x1cca - 0x1ccc
int32_t function_1cca(int32_t a1, int32_t a2) {
    // 0x1cca
    return g2;
}

// Address range: 0x1ccc - 0x1cfa
// Demangled:     boost::detail::shared_count::shared_count<boost::exception_detail::clone_impl<boost::exception_detail::clone_impl::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::clone_impl::bad_alloc_> *)
int32_t _ZN5boost6detail12shared_countC1INS_16exception_detail10clone_implINS3_10bad_alloc_EEEEEPT_(int32_t * a1, int32_t a2) {
    // 0x1ccc
    *a1 = 0;
    return (int32_t)a1;
}

// Address range: 0x1cfe - 0x1d23
int32_t function_1cfe(void) {
    int32_t * v1 = (int32_t *)-0x1fba743d; // 0x1cfe
    *v1 = *v1 - 1;
    int32_t v2 = 0; // ebx
    unknown_3a24(v2, 0);
    int32_t v3 = 0; // ebp
    *(int32_t *)*(int32_t *)(v3 - 28) = v2;
    int32_t v4 = *(int32_t *)(v3 - 12) ^ 20; // 0x1d18
    g2 = v4;
    if (v4 == 0) {
        // bb
        g2 = function_1d51();
        // branch -> 0x1d21
    }
    // 0x1d21
    return function_1d4c();
}

// Address range: 0x1d24 - 0x1d25
int32_t function_1d24(void) {
    // 0x1d24
    return 0;
}

// Address range: 0x1d4c - 0x1d4d
int32_t function_1d4c(void) {
    // 0x1d4c
    return g2;
}

// Address range: 0x1d51 - 0x1d57
int32_t function_1d51(void) {
    // 0x1d51
    return g2;
}

// Address range: 0x1d58 - 0x1d7b
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::sp_counted_impl_p(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEC1EPS5_(int32_t result, int32_t a2) {
    // 0x1d58
    return result;
}

// Address range: 0x1d7e - 0x1d9e
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          constructor
int32_t function_1d7e(int32_t a1, int32_t a2) {
    int32_t v1 = g2; // 0x1d7e
    *(char *)v1 = (char)v1 + *(char *)&g2;
    *(int32_t *)*(int32_t *)(g3 - 28) = (int32_t)&g13;
    *(int32_t *)(*(int32_t *)(g3 - 28) + 12) = *(int32_t *)(g3 - 32);
    int32_t v2 = *(int32_t *)(g3 - 12) ^ 20; // 0x1d95
    g2 = v2;
    int32_t result = v2; // 0x1d9c
    if (v2 == 0) {
        // bb
        result = function_1da3();
        // branch -> 0x1d9e
    }
    // 0x1d9e
    return result;
}

// Address range: 0x1da3 - 0x1da5
int32_t function_1da3(void) {
    // 0x1da3
    return g2;
}

// Address range: 0x1da5 - 0x1de0
// Demangled:     void boost::checked_delete<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >(boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> *)
int32_t _ZN5boost14checked_deleteINS_16exception_detail10clone_implINS1_10bad_alloc_EEEEEvPT_(int32_t * a1) {
    // 0x1da5
    if (a1 != NULL) {
        // 0x1dc2
        // branch -> 0x1dd4
    }
    // 0x1dd4
    g2 = (int32_t)&g10 ^ 20;
    int32_t result = (int32_t)&g10 ^ 20; // 0x1dde
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_1de5();
        // branch -> 0x1de0
    }
    // 0x1de0
    return result;
}

// Address range: 0x1de5 - 0x1de7
int32_t function_1de5(void) {
    // 0x1de5
    return g2;
}

// Address range: 0x1e08 - 0x1e45
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          constructor
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED1Ev(int32_t * a1) {
    int32_t result = (int32_t)a1;
    *a1 = (int32_t)&g13;
    unknown_2506(result);
    function_1e4a();
    return result;
}

// Address range: 0x1e4a - 0x1e56
int32_t function_1e4a(void) {
    int32_t v1 = *(int32_t *)(g3 - 12) ^ 20; // 0x1e4d
    g2 = v1;
    int32_t result = v1; // 0x1e54
    if (v1 == 0) {
        // bb
        result = function_1e5b();
        // branch -> 0x1e56
    }
    // 0x1e56
    return result;
}

// Address range: 0x1e5b - 0x1e5d
int32_t function_1e5b(void) {
    // 0x1e5b
    return g2;
}

// Address range: 0x1e5e - 0x1e86
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::~sp_counted_impl_p()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEED0Ev(int32_t result) {
    // 0x1e5e
    unknown_3c66(result);
    return result;
}

// Address range: 0x1e8e - 0x1e97
int32_t function_1e8e(int32_t a1, int32_t a2) {
    int32_t v1 = g2 ^ 20; // 0x1e8e
    g2 = v1;
    int32_t result = v1; // 0x1e95
    if (v1 == 0) {
        // bb
        result = function_1e9c();
        // branch -> 0x1e97
    }
    // 0x1e97
    return result;
}

// Address range: 0x1e9c - 0x1e9e
int32_t function_1e9c(void) {
    // 0x1e9c
    return g2;
}

// Address range: 0x1ed8 - 0x1ed9
int32_t function_1ed8(int32_t a1) {
    // 0x1ed8
    return g2;
}

// Address range: 0x1ee4 - 0x1ee5
int32_t function_1ee4(int32_t a1, int32_t a2) {
    // 0x1ee4
    return g2;
}

// Address range: 0x208c - 0x208d
int32_t _ZTSN5boost6system14error_categoryE(int32_t a1, int32_t a2) {
    // 0x208c
    return g2;
}

// Address range: 0x21fc - 0x21fd
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::dispose()
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE7disposeEv(void) {
    // 0x21fc
    return 0;
}

// Address range: 0x2220 - 0x222d
int32_t function_2220(int32_t a1, int32_t a2) {
    char * v1 = (char *)(g4 + 0x3365f445); // 0x2220
    *v1 = (char)g5 + *v1;
    int32_t v2 = g2 + (int32_t)&g10; // 0x2226
    g2 = v2;
    int32_t result = v2; // 0x222b
    if (v2 == 0) {
        // bb
        result = function_2232();
        // branch -> 0x222d
    }
    // 0x222d
    return result;
}

// Address range: 0x2232 - 0x2234
int32_t function_2232(void) {
    // 0x2232
    return g2;
}

// Address range: 0x2234 - 0x2262
// From class:    N5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEEE
// Type:          virtual member function
// Demangled:     boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >::get_deleter(std::type_info const &)
int32_t _ZN5boost6detail17sp_counted_impl_pINS_16exception_detail10clone_implINS2_10bad_alloc_EEEE11get_deleterERKSt9type_info(int32_t a1, int32_t a2) {
    // 0x2234
    g2 = 0;
    int32_t result = 0; // 0x2260
    if (((int32_t)&g10 ^ 20) == 0) {
        // bb
        result = function_2267(a2, a1);
        // branch -> 0x2262
    }
    // 0x2262
    return result;
}

// Address range: 0x2267 - 0x2269
int32_t function_2267(int32_t a1, int32_t a2) {
    // 0x2267
    return g2;
}

// Address range: 0x226a - 0x2271
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv(int32_t a1) {
    int32_t result = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(a1 - (int32_t)&g12); // 0x226f
    return result;
}

// Address range: 0x2272 - 0x2292
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE5cloneEv2(int32_t a1) {
    // 0x2272
    return 0;
}

// Address range: 0x2296 - 0x22c6
int32_t function_2296(void) {
    int32_t * v1 = (int32_t *)-0x1bba743d; // 0x2296
    *v1 = *v1 - 1;
    int32_t v2 = 0; // ebx
    unknown_38ae(v2, 0);
    int32_t v3 = 0;
    if (v2 != 0) {
        // 0x22ae
        v3 = v2 + (int32_t)&g12;
        // branch -> 0x22b8
    }
    // 0x22b8
    g2 = v3;
    if (*(int32_t *)-12 == 20) {
        // bb
        g2 = function_22df();
        // branch -> 0x22c4
    }
    // 0x22c4
    return function_22da();
}

// Address range: 0x22da - 0x22db
int32_t function_22da(void) {
    // 0x22da
    return g2;
}

// Address range: 0x22df - 0x22e6
int32_t function_22df(void) {
    // 0x22df
    return g2;
}

// Address range: 0x22e6 - 0x22ed
int32_t _ZThn24_NK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    int32_t result = _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(a1 - (int32_t)&g12); // 0x22eb
    return result;
}

// Address range: 0x22ee - 0x230e
// From class:    N5boost16exception_detail10clone_implINS0_10bad_alloc_EEE
// Type:          virtual member function
// Demangled:     boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>::rethrow() const
int32_t _ZNK5boost16exception_detail10clone_implINS0_10bad_alloc_EE7rethrowEv(int32_t a1) {
    // 0x22ee
    return 0;
}

// Address range: 0x2314 - 0x2315
int32_t function_2314(void) {
    // 0x2314
    return 0;
}

// Address range: 0x299e - 0x299f
int32_t function_299e(int32_t a1) {
    // 0x299e
    return g2;
}

// Address range: 0x340b - 0x340c
int32_t function_340b(int32_t a1) {
    // 0x340b
    return g2;
}

// --------------- Dynamically Linked Functions ---------------

// int32_t __stack_chk_fail(int32_t a1, int32_t a2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected language: C++
// Detected functions: 244
// Decompilation date: 2018-06-10 00:51:03
